### ISSUE TITLE
Training: RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by RauchLukas** [Pointcept/Pointcept#101]
If i run the `tools/test.py`,  the programm right after initializing the first Evaluation (see Console Output). 

## Debugging
1. The training worked out as expected. The `train_batchloss` is convergering and checkpoints are saved regularly. 
2. The validation (Evaluation)  while training went through without a hitch, as i set the batch size small enough.
3. To avoid user error, I tested this with the S3DIS dataset (downloaded your prerocessed files). 
4. According to the responds in #91, I used the SpuNet (as it is supposed to be less memory hungry) 
5. I tried to set the `grid_size=0.1` in the config dict. 

## My Setup: 
- Dataset: S3DIS 
- Graphics Card: 1 x  RTX 3090  (24GB V-Ram) 
- Models: [semseg-spunet-v1m1-0-base.py, semseg-pt-v1-0-base.py] 

## Questions
1. Do you have any experience of whether the model needs more video memory for the test than during training? 
2. should the model be able to run in training on an NVidia RTX 3090 (24GB)?
3. Any further this how to get the test up and running? 

## Console Output

```bash
root@573adcbe456e:/home/Pointcept# python tools/test.py --config-file configs/s3dis/semseg-spunet-v1m1-0-base.py --options weight="exp/spunet-v1m1/model/model_best.pth"
[2023-11-15 13:36:20,434 INFO test.py line 38 38174] => Loading config ...
[2023-11-15 13:36:20,434 INFO test.py line 39 38174] Save path: exp/default
[2023-11-15 13:36:20,719 INFO test.py line 40 38174] Config:
weight = 'exp/spunet-v1m1/model/model_best.pth'
resume = False
evaluate = True
test_only = False
seed = 20108604
save_path = 'exp/default'
num_worker = 16
batch_size = 4
batch_size_val = None
batch_size_test = None
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
mix_prob = 0.8
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
test = dict(type='SemSegTester')
model = dict(
    type='DefaultSegmentor',
    backbone=dict(
        type='SpUNet-v1m1',
        in_channels=6,
        num_classes=13,
        channels=(32, 64, 128, 256, 256, 128, 96, 96),
        layers=(2, 3, 4, 6, 2, 2, 2, 2)),
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(
    type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001, nesterov=True)
scheduler = dict(type='PolyLR')
dataset_type = 'S3DISDataset'
data_root = 'data/s3dis'
data = dict(
    num_classes=13,
    ignore_index=-1,
    names=[
        'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
        'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter'
    ],
    train=dict(
        type='S3DISDataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='RandomDropout',
                dropout_ratio=0.2,
                dropout_application_ratio=0.2),
            dict(
                type='RandomRotate',
                angle=[-1, 1],
                axis='z',
                center=[0, 0, 0],
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='x',
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='y',
                p=0.5),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(
                type='ElasticDistortion',
                distortion_params=[[0.2, 0.4], [0.8, 1.6]]),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.05,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='SphereCrop', point_max=100000, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ShufflePoint'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='GridSample',
                grid_size=0.05,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False),

test=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.1,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_discrete_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'discrete_coord', 'index'),
                    feat_keys=('coord', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 16
batch_size_per_gpu = 4
batch_size_val_per_gpu = 1
batch_size_test_per_gpu = 1

[2023-11-15 13:36:20,720 INFO test.py line 44 38174] => Building model ...
[2023-11-15 13:36:21,277 INFO test.py line 47 38174] Num params: 39157165
[2023-11-15 13:36:21,555 INFO test.py line 66 38174] => Loaded weight 'exp/spunet-v1m1/model/model_best.pth' (epoch 2)
[2023-11-15 13:36:21,555 INFO test.py line 74 38174] => Building test dataset & dataloader ...
[2023-11-15 13:36:21,557 INFO s3dis.py line 55 38174] Totally 68 x 1 samples in Area_5 set.
[2023-11-15 13:36:21,558 INFO test.py line 39 38174] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/home/Pointcept/tools/test.py", line 107, in <module>
    main()
  File "/home/Pointcept/tools/test.py", line 96, in main
    launch(
  File "/home/Pointcept/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "/home/Pointcept/tools/test.py", line 89, in main_worker
    tester(cfg, test_loader, model)
  File "/home/Pointcept/pointcept/engines/test.py", line 76, in __call__
    for idx, data_dict in enumerate(test_loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 34, in do_one_step
    data = pin_memory(data, device)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 70, in pin_memory
    return type(data)([pin_memory(sample, device) for sample in data])  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 70, in <listcomp>
    return type(data)([pin_memory(sample, device) for sample in data])  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 60, in pin_memory
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 60, in <dictcomp>
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 70, in pin_memory
    return type(data)([pin_memory(sample, device) for sample in data])  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 70, in <listcomp>
    return type(data)([pin_memory(sample, device) for sample in data])  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 60, in pin_memory
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 60, in <dictcomp>
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return data.pin_memory(device)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by Gofinge** [comment]
Hi, my apology for the late response.

R1: Test and eval should not cost more memory, especially since the batch size for test and eval is fixed to 1.
R2: I am not sure, but reducing batch size usually causes a performance drop, SpUNet is memory efficient it might can be run with the original bs with a single 3090.
R3: Could you profile your memory consumption during testing? The case is quite rare. (I will update a more faster testing strategy in the next version)

BTW: It is suggest that train and test with a different grid size which will significant harm the performance.
