### ISSUE TITLE
problem with S3SIS

### ISSUE THREAD

**Issue by lucasi-max** [Pointcept/Pointcept#102]
What are the requirements for preprocessing the S3DIS dataset
ERROR：ValueError：zero-size array to reduction operation maximum which has no identity

**Comment by Gofinge** [comment]
Could you provide more detailed information to help me figure out the issue?

**Comment by lucasi-max** [comment]
error: 
Loading room information ...
Loading raw mesh file ...
[Open3D WARNING] Unable to load file None/area_1/3d/rgb.obj with ASSIMP
Area_1 mesh is loaded
[Open3D WARNING] Unable to load file None/area_2/3d/rgb.obj with ASSIMP
Area_2 mesh is loaded
[Open3D WARNING] Unable to load file None/area_3/3d/rgb.obj with ASSIMP
Area_3 mesh is loaded
[Open3D WARNING] Unable to load file None/area_4/3d/rgb.obj with ASSIMP
Area_4 mesh is loaded
[Open3D WARNING] Unable to load file None/area_5a/3d/rgb.obj with ASSIMP
[Open3D WARNING] Unable to load file None/area_5b/3d/rgb.obj with ASSIMP
Area_5 mesh is loaded
[Open3D WARNING] Unable to load file None/area_6/3d/rgb.obj with ASSIMP
Area_6 mesh is loaded
Processing scenes...
Parsing: Area_1/conferenceRoom_1
Parsing: Area_1/conferenceRoom_2
Parsing: Area_1/copyRoom_1
Parsing: Area_1/hallway_1
Parsing: Area_1/hallway_2
Parsing: Area_1/hallway_4
Parsing: Area_1/hallway_5
Parsing: Area_1/hallway_3
Parsing: Area_1/hallway_6
Parsing: Area_1/hallway_7
Parsing: Area_1/hallway_8
Parsing: Area_1/office_1
Parsing: Area_1/office_2
Parsing: Area_1/office_3
Parsing: Area_1/office_4
Parsing: Area_1/office_5
Parsing: Area_1/office_6
Parsing: Area_1/office_7
Parsing: Area_1/office_8
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 107, in parse_room
    room_mesh = trimesh.Trimesh(
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/site-packages/trimesh/base.py", line 169, in __init__
    self.vertex_normals = vertex_normals
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/site-packages/trimesh/base.py", line 507, in vertex_normals
    if values.ptp() < tol.merge:
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/site-packages/numpy/core/_methods.py", line 283, in _ptp
    umr_maximum(a, axis, None, out, keepdims),
ValueError: zero-size array to reduction operation maximum which has no identity
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 234, in <module>
    main_process()
  File "pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 220, in main_process
    _ = list(
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/my/anaconda3/envs/pointnet/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: zero-size array to reduction operation maximum which has no identity
Parsing: Area_1/office_9
Parsing: Area_1/office_10
Parsing: Area_1/office_11
Parsing: Area_1/office_12
Parsing: Area_1/office_13
Parsing: Area_1/office_14
Parsing: Area_1/office_15
Parsing: Area_1/office_16
Parsing: Area_1/office_17

**Comment by Gofinge** [comment]
You can download my processed version for v1.5.2 from here (https://huggingface.co/datasets/Pointcept/s3dis-compressed)

**Comment by Ann1339629** [comment]
I have the same problem. Have you solved it？

**Comment by Jaeger416** [comment]
This problem is caused by the split name using "Area_*" but the folder name in downloaded dataset is "area_*. It can be simply solved by changing "mesh_dir = os.path.join(args.raw_root, split, "3d", "rgb.obj")" to "mesh_dir = os.path.join(args.raw_root, split.lower(), "3d", "rgb.obj")" in pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py
