### ISSUE TITLE
UnicodeEncodeError when using s3dis dataset

### ISSUE THREAD

**Issue by GurveerSohal** [Pointcept/Pointcept#106]
I get the following error when using the s3dis dataset

UnicodeEncodeError: 'latin-1' codec can't encode character '\u949b' in position 9258297 : ordinal not in range(256)

Could it be some problem with the data? 

I'm using:
  2 2080 Tis
  Ubuntu 18.04
  CUDA 12.1
  torch==2.1.0
  torch_geometric==2.4.0
  torchaudio==2.1.0
  torchvision==0.16.0

traceback:

Traceback (most recent call last):
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 156, in train
    for (
  File "anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/_utils.py", line 693, in reraise
    raise RuntimeError(msg) from None
RuntimeError: Caught UnicodeEncodeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Desktop/Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/datasets/s3dis.py", line 149, in __getitem__
    return self.prepare_train_data(idx)
  File "/Desktop/Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/datasets/s3dis.py", line 115, in prepare_train_data
    data_dict = self.get_data(idx)
  File "/Desktop/Pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/datasets/s3dis.py", line 75, in get_data
    data = torch.load(data_path)
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u049b' in position 9258297: ordinal not in range(256)

**Comment by Gofinge** [comment]
Hi, try to use `utf-8` format.

**Comment by GurveerSohal** [comment]
Thanks, but I'm not sure how to do that.

Passing encoding='utf-8' (or any other encoding) doesn't seem to matter, it always uses 'latin-1'. The default by torch is supposed to be 'utf-8' but it still uses 'latin-1'.

**Comment by GurveerSohal** [comment]
It may be a problem with the data itself, I'm training on a custom dataset, and the issue was with the data. It may be the same with s3dis, I may have changed it while inspecting it. If I run into this again I will open the issue again
