### ISSUE TITLE
ModuleNotFoundError: No module named 'pointgroup_ops'

### ISSUE THREAD

**Issue by LeslauD** [Pointcept/Pointcept#114]
ModuleNotFoundError: No module named 'pointgroup_ops'

**Comment by KLM1109** [comment]
i have same problem: ModuleNotFoundError: No module named 'pointgroup_ops'.
when i try to install this module ,i have another problem:
:~/Pointcept/libs/pointgroup_ops$ python setup.py install
RuntimeError: Error compiling objects for extension

**Comment by dolhasz** [comment]
Can confirm this is an issue for me too. Installed `pointops` - PyTorch matches cuda too.

**Comment by Gofinge** [comment]
> Can confirm this is an issue for me too. Installed `pointops` - PyTorch matches cuda too.
> 
> I get this when doing `pip install .` in the `pointgroup_ops` directory:
> 
> ```
> bfs_cluster.cpp:86:17: error: variable-sized object may not be initialized
> ```

Hi, could you check the output of `nvcc -V`?

**Comment by zhangkai07** [comment]
How do I resolve this error when I execute the following command

cd libs/pointops
python setup.py install

Traceback (most recent call last):
  File "F:\Python_project\Pointcept-main\libs\pointops2\setup.py", line 8, in <module>
    flag for flag in opt.split() if flag != "-Wstrict-prototypes"
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by darissa** [comment]
I have the same problem...anyone have solved this error?

**Comment by Gofinge** [comment]
> How do I resolve this error when I execute the following command
> 
> cd libs/pointops python setup.py install
> 
> Traceback (most recent call last): File "F:\Python_project\Pointcept-main\libs\pointops2\setup.py", line 8, in flag for flag in opt.split() if flag != "-Wstrict-prototypes" AttributeError: 'NoneType' object has no attribute 'split'

It might be because there is no split comment on the Windows system, try to remove the usage of split. (Our codebase is only tested on Linux system)

**Comment by hpc100** [comment]
see #122

**Comment by dwjvbh** [comment]
有人解决ModuleNotFoundError: No module named 'pointgroup_ops'
这个问题了吗
(pointcept) sxx-205@sxx-205:/data/Pointcept-main$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

**Comment by dwjvbh** [comment]
太坑了这个东西

**Comment by Gofinge** [comment]
Follow here (https://github.com/Pointcept/Pointcept?tab=readme-ov-file#pointgroup) to install pointgroup_ops, but pointgroup ops is optional.

**Comment by bututoubaobei-0108** [comment]
i have encounted the similar problem but for pointops._C. I solved using the following steps:

1.  change the name pointops._C to something not with dot, such as "pointops_cuda" being what i have used
2. change the  pointops._C in directory "functions/" to "pointops_cuda"
3. in functions/utils.py, change "from pointops import knn_query, ball_query, grouping" to "from .query import knn_query, ball_query" and "from .grouping import grouping"

after the above procedure, my code works.
Hope that the answer helps you :)
