### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by yyashpatel** [Pointcept/Pointcept#12]
Hi, when I run the command -

python setup.py install

here is the error stack trace - 

running install
running bdist_egg
running egg_info
writing pointops.egg-info/PKG-INFO
writing dependency_links to pointops.egg-info/dependency_links.txt
writing requirements to pointops.egg-info/requires.txt
writing top-level names to pointops.egg-info/top_level.txt
reading manifest file 'pointops.egg-info/SOURCES.txt'
writing manifest file 'pointops.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'pointops._C' extension
Emitting ninja build file /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
[1/15] /usr/local/cuda/bin/nvcc  -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/TH -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/scratch/smg8252/miniconda3/envs/ml_project/include/python3.8 -c -c /scratch/smg8252/point_transformer/Pointcept/libs/pointops/src/ball_query/ball_query_cuda_kernel.cu -o /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/ball_query/ball_query_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
FAILED: /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/ball_query/ball_query_cuda_kernel.o 
/usr/local/cuda/bin/nvcc  -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/TH -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/scratch/smg8252/miniconda3/envs/ml_project/include/python3.8 -c -c /scratch/smg8252/point_transformer/Pointcept/libs/pointops/src/ball_query/ball_query_cuda_kernel.cu -o /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/ball_query/ball_query_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

nvcc error   : 'cicc' died due to signal 9 (Kill signal)
[2/15] c++ -MMD -MF /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/grouping/grouping_cuda.o.d -pthread -B /scratch/smg8252/miniconda3/envs/ml_project/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/TH -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/scratch/smg8252/miniconda3/envs/ml_project/include/python3.8 -c -c /scratch/smg8252/point_transformer/Pointcept/libs/pointops/src/grouping/grouping_cuda.cpp -o /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/grouping/grouping_cuda.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[3/15] /usr/local/cuda/bin/nvcc  -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/TH -I/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/scratch/smg8252/miniconda3/envs/ml_project/include/python3.8 -c -c /scratch/smg8252/point_transformer/Pointcept/libs/pointops/src/attention/attention_cuda_kernel.cu -o /scratch/smg8252/point_transformer/Pointcept/libs/pointops/build/temp.linux-x86_64-cpython-38/src/attention/attention_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/include/c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/smg8252/point_transformer/Pointcept/libs/pointops/setup.py", line 16, in <module>
    setup(
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/scratch/smg8252/miniconda3/envs/ml_project/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=32314835.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by Gofinge** [comment]
Hi, I have never seen such an error, It seems that caused by OOM. Could you check whether your GPU is occupied?

**Comment by yyashpatel** [comment]
Hi , seems it was some gpu problem , installed everything again !

Thanks

**Comment by darissa** [comment]
Hi @yyashpatel 

How u solve this problem? I face the same thing. Can u share how u solve it?

**Comment by Gofinge** [comment]
> Hi @yyashpatel
> 
> How u solve this problem? I face the same thing. Can u share how u solve it?

Hi, did you retry to build the ops on the manager node of a slurm (https://stackoverflow.com/questions/52421068/error-in-slurm-cluster-detected-1-oom-kill-events-how-to-improve-running-jo)? If so, try to run it with computation node.
