### ISSUE TITLE
shapenet_part seg: 'ShapeNetPartDataset' object has no attribute 'data_idx'

### ISSUE THREAD

**Issue by KLM1109** [Pointcept/Pointcept#123]
Thanks to your contributes. I try to training PTv1 for ShapeNetPart and the config is using #46 . But I have a problem about data_idx.

more detail: 
```python
sh scripts/train.sh -g 1 -d shapenet_part -c partseg-pt-v1-0-base -n partseg-pt-v1-0-base
Experiment name: partseg-pt-v1-0-base
Python interpreter dir: python
Dataset: shapenet_part
Config: partseg-pt-v1-0-base
GPU Num: 1
 =========> CREATE EXP DIR <=========
Experiment dir: /home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base
Loading config in: configs/shapenet_part/partseg-pt-v1-0-base.py
Running code in: exp/shapenet_part/partseg-pt-v1-0-base/code
 =========> RUN TASK <=========
[2024-01-09 16:58:44,056 INFO train.py line 128 473363] => Loading config ...
[2024-01-09 16:58:44,056 INFO train.py line 130 473363] Save path: exp/shapenet_part/partseg-pt-v1-0-base
[2024-01-09 16:58:44,735 INFO train.py line 131 473363] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 43774843
save_path = 'exp/shapenet_part/partseg-pt-v1-0-base'
num_worker = 16
batch_size = 32
batch_size_val = 8
batch_size_test = None
epoch = 100
eval_epoch = 100
sync_bn = False
enable_amp = False
empty_cache = False
find_unused_parameters = False
mix_prob = 0
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
train = dict(type='DefaultTrainer')
test = dict(type='SemSegTester', verbose=True)
metric = 'cat_mIoU'
epochs = 100
start_epoch = 0
optimizer = dict(
    type='SGD', lr=0.5, momentum=0.9, weight_decay=0.0001, nesterov=True)
scheduler = dict(
    type='MultiStepLR', milestones=[60.0, 80.0], steps_per_epoch=1, gamma=0.1)
model = dict(
    type='PointTransformer-PartSeg50',
    num_shape_classes=16,
    in_channels=6,
    num_classes=50)
dataset_type = 'ShapeNetPartDataset'
data_root = 'data/shapenetcore_partanno_segmentation_benchmark_v0_normal'
cache_data = False
names = [
    'Airplane_0', 'Airplane_1', 'Airplane_2', 'Airplane_3', 'Bag_0', 'Bag_1',
    'Cap_0', 'Cap_1', 'Car_0', 'Car_1', 'Car_2', 'Car_3', 'Chair_0', 'Chair_1',
    'Chair_2', 'Chair_3', 'Earphone_0', 'Earphone_1', 'Earphone_2', 'Guitar_0',
    'Guitar_1', 'Guitar_2', 'Knife_0', 'Knife_1', 'Lamp_0', 'Lamp_1', 'Lamp_2',
    'Lamp_3', 'Laptop_0', 'Laptop_1', 'Motorbike_0', 'Motorbike_1',
    'Motorbike_2', 'Motorbike_3', 'Motorbike_4', 'Motorbike_5', 'Mug_0',
    'Mug_1', 'Pistol_0', 'Pistol_1', 'Pistol_2', 'Rocket_0', 'Rocket_1',
    'Rocket_2', 'Skateboard_0', 'Skateboard_1', 'Skateboard_2', 'Table_0',
    'Table_1', 'Table_2'
]
data = dict(
    num_classes=50,
    ignore_label=-1,
    names=[
        'Airplane_0', 'Airplane_1', 'Airplane_2', 'Airplane_3', 'Bag_0',
        'Bag_1', 'Cap_0', 'Cap_1', 'Car_0', 'Car_1', 'Car_2', 'Car_3',
        'Chair_0', 'Chair_1', 'Chair_2', 'Chair_3', 'Earphone_0', 'Earphone_1',
        'Earphone_2', 'Guitar_0', 'Guitar_1', 'Guitar_2', 'Knife_0', 'Knife_1',
        'Lamp_0', 'Lamp_1', 'Lamp_2', 'Lamp_3', 'Laptop_0', 'Laptop_1',
        'Motorbike_0', 'Motorbike_1', 'Motorbike_2', 'Motorbike_3',
        'Motorbike_4', 'Motorbike_5', 'Mug_0', 'Mug_1', 'Pistol_0', 'Pistol_1',
        'Pistol_2', 'Rocket_0', 'Rocket_1', 'Rocket_2', 'Skateboard_0',
        'Skateboard_1', 'Skateboard_2', 'Table_0', 'Table_1', 'Table_2'
    ],
    train=dict(
        type='ShapeNetPartDataset',
        split=['train', 'val'],
        data_root='data/shapenetcore_partanno_segmentation_benchmark_v0_normal',
        transform=[
            dict(type='NormalizeCoord'),
            dict(type='ShufflePoint'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'cls_token', 'label'),
                feat_keys=('coord', 'norm'))
        ],
        loop=1,
        test_mode=False),
    val=dict(
        type='ShapeNetPartDataset',
        split='test',
        data_root='data/shapenetcore_partanno_segmentation_benchmark_v0_normal',
        transform=[
            dict(type='NormalizeCoord'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'cls_token', 'label'),
                feat_keys=('coord', 'norm'))
        ],
        loop=1,
        test_mode=False),
    test=dict(
        type='ShapeNetPartDataset',
        split='test',
        data_root='data/shapenetcore_partanno_segmentation_benchmark_v0_normal',
        transform=[dict(type='NormalizeCoord')],
        loop=1,
        test_mode=True,
        test_cfg=dict(
            post_transform=[
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'cls_token'),
                    feat_keys=('coord', 'norm'))
            ],
            aug_transform=[[{
                'type': 'RandomShift2',
                'shift': ((0, 0), (0, 0), (0, 0))
            }]])))
criteria = [dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)]
num_worker_per_gpu = 16
batch_size_per_gpu = 32
batch_size_val_per_gpu = 8
batch_size_test_per_gpu = 1

[2024-01-09 16:58:44,736 INFO train.py line 132 473363] => Building model ...
[2024-01-09 16:58:44,844 INFO train.py line 209 473363] Num params: 8310646
[2024-01-09 16:58:46,599 INFO train.py line 134 473363] => Building writer ...
[2024-01-09 16:58:46,601 INFO train.py line 219 473363] Tensorboard writer logging dir: exp/shapenet_part/partseg-pt-v1-0-base
[2024-01-09 16:58:46,601 INFO train.py line 136 473363] => Building train dataset & dataloader ...
Traceback (most recent call last):
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/datasets/shapenet_part.py", line 89, in __init__
    len(self.data_idx), self.loop, split
AttributeError: 'ShapeNetPartDataset' object has no attribute 'data_idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/train.py", line 137, in __init__
    self.train_loader = self.build_train_loader()
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/train.py", line 223, in build_train_loader
    train_data = build_dataset(self.cfg.data.train)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/datasets/builder.py", line 16, in build_dataset
    return DATASETS.build(cfg)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
AttributeError: ShapeNetPartDataset: 'ShapeNetPartDataset' object has no attribute 'data_idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 19, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
AttributeError: Trainer: ShapeNetPartDataset: 'ShapeNetPartDataset' object has no attribute 'data_idx'
```

**Comment by Gofinge** [comment]
Hi, I am still on holiday, I will handle the issue when I am back (within one week). Thanks for being interested in our work.

**Comment by ChrisChenYh** [comment]
I generate the data_idx by adding the code below in __init__, and it seems work.
`        self.data_idx = []
        for i in range(len(self.data_list)):
            self.data_idx.append(i)`

**Comment by KLM1109** [comment]
@ChrisChenYh thank you for your proposal, it does work!
