### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by Wang-zhenyan** [Pointcept/Pointcept#147]
你好，很感谢你们的优秀的文章
我在处理scannet数据集的时候，出现这个问题的报错
NotADirectoryError: [Errno 20] Not a directory: '/home/wzy/code/Pointceptmain/pointcept/datasets/raw/scannet/train/scene0000_00.pth/scene0000_00_vh_clean_2.ply'
这看起来好像是将pth文件作为目录，它的底下没有.ply文件。但是数据集中pth文件是一个压缩文件，没有子文件。如何获取到这个ply文件提供给后续函数？
另外，mesh_path = os.path.join(scene_path, f"{scene_id}{CLOUD_FILE_PFIX}.ply")程序中的这一行，为pth文件拼接.ply文件是什么意思？

**Comment by Gofinge** [comment]
你好，看起来似乎是你将已经处理后的ScanNet文件夹作为预处理的Raw（dataset_root）了。可能你下载的是我提供的已处理好的scannet数据集，而不是官方的原始数据集。

**Comment by Squirrel-code** [comment]
> 你好，看起来似乎是你将已经处理后的ScanNet文件夹作为预处理的Raw（dataset_root）了。可能你下载的是我提供的已处理好的scannet数据集，而不是官方的原始数据集。

所以请问如果是使用处理好的数据集，应该放在什么路径下使用呢？

**Comment by Squirrel-code** [comment]
感谢你迅速的回复，我使用的是S3DIS数据集，我将已经处理好的数据集参考README文档，放置在了“Pointcept/data/s3dis”下，
文件结构是这样的：
Pointcept
|--data
—|--s3dis
——|--Area_1
———|--office_1.pth

似乎是正确的路径（只是没有使用软链接），但是还是出现了类似的报错：
```
NotADirectoryError: Caught NotADirectoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ai/miniconda3/envs/pointcept/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ai/miniconda3/envs/pointcept/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ai/miniconda3/envs/pointcept/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in &lt;listcomp&gt;
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/datasets/defaults.py", line 172, in __getitem__
    return self.prepare_train_data(idx)
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/datasets/defaults.py", line 131, in prepare_train_data
    data_dict = self.get_data(idx)
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/datasets/defaults.py", line 93, in get_data
    assets = os.listdir(data_path)
NotADirectoryError: [Errno 20] Not a directory: 'data/s3dis/Area_4/office_5.pth'
```
当尝试更换数据集的路径到其他地方后，出现了这样的报错：
```
Traceback (most recent call last):
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/engines/train.py", line 137, in __init__
    self.train_loader = self.build_train_loader()
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/engines/train.py", line 248, in build_train_loader
    train_loader = torch.utils.data.DataLoader(
  File "/home/ai/miniconda3/envs/pointcept/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/ai/miniconda3/envs/pointcept/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/tools/train.py", line 40, in <module>
    main()
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/tools/train.py", line 29, in main
    launch(
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/tools/train.py", line 21, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ai/myCode/Pointcept/exp/s3dis/semseg-spunet-v1m1-0-base/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
ValueError: Trainer: num_samples should be a positive integer value, but got num_samples=0
```
我认为第一次的路径是相对正确的，但是不知道为什么还会报错

**Comment by Gofinge** [comment]
第一次的相对路径是正确的，可以去检测第一次路径下，报错文件目录是否可以正确读取。

**Comment by Gabonlee** [comment]
需要将官方给的.pth文件转成.npy的格式，可以参考以下代码：
`
import os
import torch
import numpy as np

# 定义s3dis文件夹路径
s3dis_folder = 's3dis'

# 定义保存目录路径
export_folder = 's3dis_export'

# 遍历s3dis文件夹下的每个文件夹
for folder_name in os.listdir(s3dis_folder):
    folder_path = os.path.join(s3dis_folder, folder_name)
    
    # 检查文件夹是否存在并且是一个目录
    if os.path.isdir(folder_path):
        # 遍历文件夹中的每个.pth文件
        for file_name in os.listdir(folder_path):
            if file_name.endswith('.pth'):
                file_path = os.path.join(folder_path, file_name)
                
                # 加载PyTorch模型
                model = torch.load(file_path)
                
                # 创建目录并保存模型参数为.npy文件
                directory = os.path.splitext(file_name)[0]
                directory_path = os.path.join(export_folder, folder_name, directory)
                if not os.path.exists(directory_path):
                    os.makedirs(directory_path)
                for key, value in model.items():
                    np.save(os.path.join(directory_path, f'{key}.npy'), value)
`
顺便吐槽一下官方有些粗心了

**Comment by Squirrel-code** [comment]
> 需要将官方给的.pth文件转成.npy的格式，可以参考以下代码：
> 
> ```
> import os
> import torch
> import numpy as np
> 
> # 定义s3dis文件夹路径
> s3dis_folder = 's3dis'
> 
> # 定义保存目录路径
> export_folder = 's3dis_export'
> 
> # 遍历s3dis文件夹下的每个文件夹
> for folder_name in os.listdir(s3dis_folder):
>     folder_path = os.path.join(s3dis_folder, folder_name)
>     
>     # 检查文件夹是否存在并且是一个目录
>     if os.path.isdir(folder_path):
>         # 遍历文件夹中的每个.pth文件
>         for file_name in os.listdir(folder_path):
>             if file_name.endswith('.pth'):
>                 file_path = os.path.join(folder_path, file_name)
>                 
>                 # 加载PyTorch模型
>                 model = torch.load(file_path)
>                 
>                 # 创建目录并保存模型参数为.npy文件
>                 directory = os.path.splitext(file_name)[0]
>                 directory_path = os.path.join(export_folder, folder_name, directory)
>                 if not os.path.exists(directory_path):
>                     os.makedirs(directory_path)
>                 for key, value in model.items():
>                     dtype = None
>                     if key == 'color':
>                         dtype = np.uint8
>                     elif key == 'coord':
>                         dtype = np.float32
>                     elif key == 'instance_gt':
>                         dtype = np.uint16
>                         key = 'instance'
>                     elif key == 'semantic_gt':
>                         dtype = np.uint16
>                         key = 'segment'
>                     elif key == 'normal':
>                         dtype = np.float32
>                     
>                     np.save(os.path.join(directory_path, f'{key}.npy'), np.array(value, dtype=dtype))
> ```
> 
> 顺便吐槽一下官方有些粗心了


是我没注意到官方更新了处理好的数据集地址：
https://huggingface.co/datasets/Pointcept/s3dis-compressed
里面是npy文件，现在问题解决了^0^，喜提OOM（是我显存的问题了o_o ....）
