### ISSUE TITLE
How to use my dataset to run semseg-ppt-v1m1-0-s3-sc-st-spunet.py？

### ISSUE THREAD

**Issue by Novmaple** [Pointcept/Pointcept#163]
I have made two datasets in the same format as S3DIS, and they work on spunet, ptv1, ptv2 and other models. Now I try to use the ppt to improve the effect, but I don't know how to change the config of this model. What's the meaning of 'valid_index'? Does my dataset have to have normal vectors to run on this model?

**Comment by Gofinge** [comment]
Here (https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-ppt-v1m1-0-sc-st-spunet.py#L41) we maintain a union set of all class_name from each dataset. Then the "valid_index"  for one of these datasets indicates the location index of the given class name in the union class name set. 

For example, the class_name for single s3dis is:
```
names=["ceiling", "floor", "wall", "beam", "column", "window", 
"door", "table", "chair", "sofa", "bookcase", "board", "clutter"],
```
And the union class name list is:
```
 class_name=(
        "wall", "floor", "cabinet", "bed", "chair", "sofa", "table", "door",
        "window", "bookshelf", "bookcase", "picture", "counter", "desk", "shelves", "curtain",
        "dresser", "pillow", "mirror", "ceiling", "refrigerator", "television", "shower curtain", "nightstand",
        "toilet", "sink", "lamp", "bathtub", "garbagebin", "board", "beam", "column",
        "clutter", "otherstructure", "otherfurniture", "otherprop",
    )
```
Then for the class name `"ceiling"`, is located in the 19th index of the union class name set, hence the overall valid_index for s3dis (3th dataset) should be:
```
(19, 1, 0, 30, 31, 8, 7, 6, 4, 5, 10, 29, 32)
```
(It seems that I set the valid id of S3DIS as  (0, 1, 4, 5, 6, 7, 8, 10, 19, 29, 30, 31, 32) in the wrong order, yet it seems that It won't affect the strong performance, I will ablate it later.)

Another more simple way to enable categorical alignment is the union strategy in our paper. You can refer configs for outdoor datasets. (https://github.com/Pointcept/Pointcept/blob/main/configs/nuscenes/semseg-ppt-v1m2-0-nu-sk-wa-spunet.py)

**Comment by Novmaple** [comment]
Thank you for your answer. I understand the meaning of 'valid_index'. I changed the class_name, valid_index and dataset config
```
        datasets=[
            # S3DIS
            dict(
                type="S3DISDataset",
                split=("Area_1", "Area_5", "Area_6", "Area_7", "Area_8", "Area_9", "Area_10",
                       "Area_11"),
                data_root="data/s3dis",
                transform=[
                    dict(type="CenterShift", apply_z=True),
                    dict(
                        type="RandomDropout",
                        dropout_ratio=0.2,
                        dropout_application_ratio=0.2,
                    ),
                    # dict(type="RandomRotateTargetAngle", angle=(1/2, 1, 3/2), center=[0, 0, 0], axis="z", p=0.75),
                    dict(
                        type="RandomRotate",
                        angle=[-1, 1],
                        axis="z",
                        center=[0, 0, 0],
                        p=0.5,
                    ),
                    dict(type="RandomRotate", angle=[-1 / 64, 1 / 64], axis="x", p=0.5),
                    dict(type="RandomRotate", angle=[-1 / 64, 1 / 64], axis="y", p=0.5),
                    dict(type="RandomScale", scale=[0.9, 1.1]),
                    # dict(type="RandomShift", shift=[0.2, 0.2, 0.2]),
                    dict(type="RandomFlip", p=0.5),
                    dict(type="RandomJitter", sigma=0.005, clip=0.02),
                    dict(
                        type="ElasticDistortion",
                        distortion_params=[[0.2, 0.4], [0.8, 1.6]],
                    ),
                    dict(type="ChromaticAutoContrast", p=0.2, blend_factor=None),
                    dict(type="ChromaticTranslation", p=0.95, ratio=0.05),
                    dict(type="ChromaticJitter", p=0.95, std=0.05),
                    # dict(type="HueSaturationTranslation", hue_max=0.2, saturation_max=0.2),
                    # dict(type="RandomColorDrop", p=0.2, color_augment=0.0),
                    dict(
                        type="GridSample",
                        grid_size=0.02,
                        hash_type="fnv",
                        mode="train",
                        return_grid_coord=True,
                    ),
                    dict(type="SphereCrop", sample_rate=0.6, mode="random"),
                    dict(type="CenterShift", apply_z=False),
                    dict(type="NormalizeColor"),
                    dict(type="ShufflePoint"),
                    dict(type="Add", keys_dict={"condition": "S3DIS"}),
                    dict(type="ToTensor"),
                    dict(
                        type="Collect",
                        keys=("coord", "grid_coord", "segment", "condition"),
                        feat_keys=("color", "normal"),
                    ),
                ],
                test_mode=False,
                loop=1,  # sampling weight
            ),
            # S3DIS
            dict(
                type="S3DISDataset",
                split=("Area_1", "Area_2", "Area_3", "Area_4", "Area_5"),
                data_root="data/gs3dis",
                transform=[
                    dict(type="CenterShift", apply_z=True),
                    dict(
                        type="RandomDropout",
                        dropout_ratio=0.2,
                        dropout_application_ratio=0.2,
                    ),
                    # dict(type="RandomRotateTargetAngle", angle=(1/2, 1, 3/2), center=[0, 0, 0], axis="z", p=0.75),
                    dict(
                        type="RandomRotate",
                        angle=[-1, 1],
                        axis="z",
                        center=[0, 0, 0],
                        p=0.5,
                    ),
                    dict(type="RandomRotate", angle=[-1 / 64, 1 / 64], axis="x", p=0.5),
                    dict(type="RandomRotate", angle=[-1 / 64, 1 / 64], axis="y", p=0.5),
                    dict(type="RandomScale", scale=[0.9, 1.1]),
                    # dict(type="RandomShift", shift=[0.2, 0.2, 0.2]),
                    dict(type="RandomFlip", p=0.5),
                    dict(type="RandomJitter", sigma=0.005, clip=0.02),
                    dict(
                        type="ElasticDistortion",
                        distortion_params=[[0.2, 0.4], [0.8, 1.6]],
                    ),
                    dict(type="ChromaticAutoContrast", p=0.2, blend_factor=None),
                    dict(type="ChromaticTranslation", p=0.95, ratio=0.05),
                    dict(type="ChromaticJitter", p=0.95, std=0.05),
                    # dict(type="HueSaturationTranslation", hue_max=0.2, saturation_max=0.2),
                    # dict(type="RandomColorDrop", p=0.2, color_augment=0.0),
                    dict(
                        type="GridSample",
                        grid_size=0.02,
                        hash_type="fnv",
                        mode="train",
                        return_grid_coord=True,
                    ),
                    dict(type="SphereCrop", sample_rate=0.6, mode="random"),
                    dict(type="CenterShift", apply_z=False),
                    dict(type="NormalizeColor"),
                    dict(type="ShufflePoint"),
                    dict(type="Add", keys_dict={"condition": "S3DIS"}),
                    dict(type="ToTensor"),
                    dict(
                        type="Collect",
                        keys=("coord", "grid_coord", "segment", "condition"),
                        feat_keys=("color", "normal"),
                    ),
                ],
                test_mode=False,
                loop=1,  # sampling weight
            ),
        ],
    ),
```
But it not works.
```
[2024-03-12 18:07:50,045 INFO train.py line 132 6212] => Building model ...
[2024-03-12 18:07:52,102 INFO train.py line 209 6212] Num params: 43631296
[2024-03-12 18:07:53,383 INFO train.py line 134 6212] => Building writer ...
[2024-03-12 18:07:53,384 INFO train.py line 219 6212] Tensorboard writer logging dir: exp/s3dis/semseg-ppt-v1m1-0-s3-sc-st-spunet
[2024-03-12 18:07:53,384 INFO train.py line 136 6212] => Building train dataset & dataloader ...
[2024-03-12 18:07:53,385 INFO s3dis.py line 55 6212] Totally 8 x 1 samples in ('Area_1', 'Area_5', 'Area_6', 'Area_7', 'Area_8', 'Area_9', 'Area_10', 'Area_11') set.
[2024-03-12 18:07:53,385 INFO s3dis.py line 55 6212] Totally 5 x 1 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_5') set.
[2024-03-12 18:07:53,385 INFO defaults.py line 149 6212] Totally 13 x 1 samples in the concat set.
[2024-03-12 18:07:53,385 INFO train.py line 138 6212] => Building val dataset & dataloader ...
[2024-03-12 18:07:53,385 INFO s3dis.py line 55 6212] Totally 3 x 1 samples in ('Area_2', 'Area_3', 'Area_4') set.
[2024-03-12 18:07:53,386 INFO train.py line 140 6212] => Building optimize, scheduler, scaler(amp) ...
Traceback (most recent call last):
  File "/home/yuwanchen/pointcept-val/exp/s3dis/semseg-ppt-v1m1-0-s3-sc-st-spunet/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/yuwanchen/pointcept-val/exp/s3dis/semseg-ppt-v1m1-0-s3-sc-st-spunet/code/pointcept/utils/scheduler.py", line 128, in __init__
    super().__init__(
  File "/home/yuwanchen/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 1474, in __init__
    raise ValueError("Expected positive integer total_steps, but got {}".format(total_steps))
ValueError: Expected positive integer total_steps, but got 0
```
When I change the scheduler to MultiStepLR (the same as other model), KeyError: 'normal' occurred, even if I delete all the 'normal' in config file. Are normal vectors required?

**Comment by Gofinge** [comment]
If your target dataset does not have normal information, please also disable it in other datasets.

**Comment by Novmaple** [comment]
Both of my datasets only have xyzrgb information, how to disable it?

**Comment by Gofinge** [comment]
Remove "Normal" in each `feat_key` list of `"Collect"` function, also don't forget to reduce the in_channel of the model config.

**Comment by Novmaple** [comment]
Thank you, I add '''keys=("coord", "color", "segment"),''' to the '''GridSample''' function. When I use OneCycleLR, '''ValueError: MultiDatasetTrainer: OneCycleLR: Expected positive integer total_steps, but got 0'' will occur. When I use MultiStepLR, it skips the training. What's the problem?
'''
[2024-03-13 12:53:44,475 INFO train.py line 132 12514] => Building model ...
[2024-03-13 12:53:46,544 INFO train.py line 209 12514] Num params: 43682752
[2024-03-13 12:53:47,893 INFO train.py line 134 12514] => Building writer ...
[2024-03-13 12:53:47,894 INFO train.py line 219 12514] Tensorboard writer logging dir: exp/s3dis/semseg-ppt-v1m1-0-s3-sc-st-spunet
[2024-03-13 12:53:47,894 INFO train.py line 136 12514] => Building train dataset & dataloader ...
[2024-03-13 12:53:47,895 INFO s3dis.py line 55 12514] Totally 8 x 1 samples in ('Area_1', 'Area_5', 'Area_6', 'Area_7', 'Area_8', 'Area_9', 'Area_10', 'Area_11') set.
[2024-03-13 12:53:47,895 INFO s3dis.py line 55 12514] Totally 5 x 1 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_5') set.
[2024-03-13 12:53:47,895 INFO defaults.py line 149 12514] Totally 13 x 1 samples in the concat set.
[2024-03-13 12:53:47,895 INFO train.py line 138 12514] => Building val dataset & dataloader ...
[2024-03-13 12:53:47,896 INFO s3dis.py line 55 12514] Totally 3 x 1 samples in ('Area_2', 'Area_3', 'Area_4') set.
[2024-03-13 12:53:47,896 INFO train.py line 140 12514] => Building optimize, scheduler, scaler(amp) ...
[2024-03-13 12:53:47,897 INFO train.py line 144 12514] => Building hooks ...
[2024-03-13 12:53:47,897 INFO misc.py line 215 12514] => Loading checkpoint & weight ...
[2024-03-13 12:53:47,897 INFO misc.py line 252 12514] No weight found at: None
[2024-03-13 12:53:47,897 INFO train.py line 151 12514] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
[2024-03-13 12:53:48,370 INFO misc.py line 136 12514] Train result: 
[2024-03-13 12:53:48,371 INFO evaluator.py line 112 12514] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-03-13 12:53:49,629 INFO evaluator.py line 159 12514] Test: [1/3] Loss 0.7105 
[2024-03-13 12:53:49,731 INFO evaluator.py line 159 12514] Test: [2/3] Loss 0.7718 
[2024-03-13 12:53:49,796 INFO evaluator.py line 159 12514] Test: [3/3] Loss 0.6703 
[2024-03-13 12:53:49,816 INFO evaluator.py line 174 12514] Val result: mIoU/mAcc/allAcc 0.3541/0.4967/0.5755.
[2024-03-13 12:53:49,816 INFO evaluator.py line 180 12514] Class_0-Pipe Result: iou/accuracy 0.1747/0.2928
[2024-03-13 12:53:49,816 INFO evaluator.py line 180 12514] Class_1-Other Result: iou/accuracy 0.5336/0.7006
[2024-03-13 12:53:49,817 INFO evaluator.py line 194 12514] <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
[2024-03-13 12:53:49,817 INFO misc.py line 160 12514] Best validation mIoU updated to: 0.3541
[2024-03-13 12:53:49,817 INFO misc.py line 165 12514] Currently Best mIoU: 0.3541
[2024-03-13 12:53:49,817 INFO misc.py line 174 12514] Saving checkpoint to: exp/s3dis/semseg-ppt-v1m1-0-s3-sc-st-spunet/model/model_last.pth
'''

**Comment by Novmaple** [comment]
Thank you very much for your patient answer, now I can run it.

**Comment by lemon44567** [comment]
Hello, I would like to know how you create the "Area_1_alignmentAngle.txt" file when creating the dataset, I am also making the data set.. Thank you very much!

**Comment by Gofinge** [comment]
Hi, save the pose here (https://github.com/Pointcept/Pointcept/blob/main/pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py#L116) is all you need.

**Comment by lemon44567** [comment]
Thank you for your answer. I have read the code you mentioned, and here is my understanding. I hope you can advise me whether my idea is correct. Taking two rooms as an example, the alignmentAngle calculation is used to convert two rooms with different coordinates to the same coordinate. If two rooms are shown in coordinates at the same time, they will be shown at the center of the coordinates at the same time, and there may be some overlap.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pointcept/Pointcept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pointcept/Pointcept] How to use my dataset to run semseg-ppt-v1m1-0-s3-sc-st-spunet.py？ (Issue #163)





 
Hi, save the pose here (https://github.com/Pointcept/Pointcept/blob/main/pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py#L116) is all you need.

**Comment by Gofinge** [comment]
> te the "Area_1_alignmentAngle.txt" file when creating the dataset, I am also making the data set.. Thank you very much!

Hi, do you mean that you want to know how we align all the rooms in such as Area 1 to the same coordinate system?

**Comment by lemon44567** [comment]
> Hi, do you mean that you want to know how we align all the rooms in such as Area 1 to the same coordinate system?

Thank you for your response. Yes, I would like to know if the alignment of the rooms in Area 1 to the same coordinate system is accomplished using the angles provided in the file "Area_1_alignmentAngle.txt," and how to achieve this alignment.

**Comment by lemon44567** [comment]
> I think this is an alignment file. Since my point clouds are all oriented correctly, I generated this file modeled after the format of the standard dataset and set each scene to 0.

Thank you very much for your response, it's very helpful to me.

**Comment by Gofinge** [comment]
> ow if the alignment of th

Yes, I think this is exactly the answer you want.

**Comment by lemon44567** [comment]
> Yes, I think this is exactly the answer you want.
Thank you very much for your patient response, it's very helpful to me.

**Comment by lemon44567** [comment]
> Yes, I think this is exactly the answer you want.
Thank you very much for your patient answer. I have no problem.
