### ISSUE TITLE
How do I train a custom dataset ?

### ISSUE THREAD

**Issue by adamvln** [Pointcept/Pointcept#188]
Hi ! First of all thank you for your work and for answering the questions of everybody.
I would like to train my dataset and I made it to the Scannet format : 
Own Dataset
    |- train
        |- bb_1.pth
        |- bb_2.pth
        |- ......
    |- val
    |- test
    
    Afterwards, I created a /datasets/custom_dataset.py file based on the defaults.py model. However, now I am a bit lost to pursue my objective, should I then write a config file to fit my dataset? Can you please explain very succintly the steps to finally train the model on my data ? Thank you

**Comment by Gofinge** [comment]
Hi, as you align your data with a ScanNet format, I think you can directly modify your config from ScanNet (https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-pt-v3m1-0-base.py), just align the num_classes, class_name, data_root as your custom dataset.

**Comment by adamvln** [comment]
Hi, thank you for your answer it seems that everything is in place now. I do have another problem now and would appreciate some guidance. 

I installed the environment correctly and I am trying to train my model but I run into this error : 
```plaintext
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from pointcept.engines.train import TRAINERS
  # ... more traceback ...
  File "/gpfs/home4/avalin/CityThesis/Pointcept/pointcept/models/point_group/point_group_v1m1_base.py", line 13, in <module>
    from pointgroup_ops import ballquery_batch_p, bfs_cluster
ModuleNotFoundError: No module named 'pointgroup_ops'
```

According to the readme, I ran the setup.py install file located in the lib/pointops folder but not the one in lib/pointgroup_ops. 
Hence, I tried to install the setup.py file located in pointgroup_ops but got this problem that I am investigating right now : 

```
running install
running bdist_egg
running egg_info
creating pointgroup_ops.egg-info
writing pointgroup_ops.egg-info/PKG-INFO
writing dependency_links to pointgroup_ops.egg-info/dependency_links.txt
writing top-level names to pointgroup_ops.egg-info/top_level.txt
writing manifest file 'pointgroup_ops.egg-info/SOURCES.txt'
reading manifest file 'pointgroup_ops.egg-info/SOURCES.txt'
writing manifest file 'pointgroup_ops.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/pointgroup_ops
copying functions/__init__.py -> build/lib.linux-x86_64-cpython-38/pointgroup_ops
copying functions/functions.py -> build/lib.linux-x86_64-cpython-38/pointgroup_ops
running build_ext
building 'pointgroup_ops_cuda' extension
creating /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38
creating /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src
/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
Emitting ninja build file /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /sw/arch/RHEL8/EB_production/2022/software/CUDA/11.7.0/bin/nvcc  -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/TH -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/THC -I/sw/arch/RHEL8/EB_production/2022/software/CUDA/11.7.0/include -I/home/avalin/.conda/envs/pointcept/include/python3.8 -c -c /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/src/bfs_cluster_kernel.cu -o /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointgroup_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=sm_80 -std=c++14
[2/2] c++ -MMD -MF /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster.o.d -pthread -B /home/avalin/.conda/envs/pointcept/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/TH -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/THC -I/sw/arch/RHEL8/EB_production/2022/software/CUDA/11.7.0/include -I/home/avalin/.conda/envs/pointcept/include/python3.8 -c -c /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/src/bfs_cluster.cpp -o /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointgroup_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster.o 
c++ -MMD -MF /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster.o.d -pthread -B /home/avalin/.conda/envs/pointcept/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/TH -I/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/include/THC -I/sw/arch/RHEL8/EB_production/2022/software/CUDA/11.7.0/include -I/home/avalin/.conda/envs/pointcept/include/python3.8 -c -c /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/src/bfs_cluster.cpp -o /gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/build/temp.linux-x86_64-cpython-38/src/bfs_cluster.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointgroup_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/gpfs/home4/avalin/CityThesis/Pointcept/libs/pointgroup_ops/src/bfs_cluster.cpp:15:10: fatal error: google/dense_hash_map: No such file or directory
 #include <google/dense_hash_map>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    setup(
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/avalin/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Do i need to install the second setup file ?

**Comment by Gofinge** [comment]
Hi, I think for the latest version of Pointcept pointgroup_ops has already become an optional install. Here are my two suggestions for this issue:
1. Install pointgroup_ops with following readme (https://github.com/Pointcept/Pointcept?tab=readme-ov-file#pointgroup)
2. Or directly commit import code for PointGroup in pointcept.model.__init__

**Comment by Gofinge** [comment]
Hi, for the bug you mentioned, the solution is: `("color")` -> `("color",)` as `("color")` is euqal to `"color"`.

Also, I think `intensity` is similar to the concept of "strength" in our codebase, you can refer our configs for outdoor datasets.

**Comment by adamvln** [comment]
Hi,
Thanks again for your previous comments. I think that I am now really close. 
I still have a problem, it feels that after all the transforms, the segment values of my data all become -1. 

```
L input du model est  {'coord': tensor([[ 0.0771,  0.4932,  0.8126],
        [ 0.0203,  0.3226,  1.3666],
        [-0.2112,  0.1075,  5.2908],
        ...,
        [ 0.2122, -0.0066,  4.0391],
        [ 0.4521,  0.1313,  0.9356],
        [ 0.4733,  0.1140,  0.5891]], device='cuda:0'), 'grid_coord': tensor([[ 28,  57,  49],
        [ 25,  48,  77],
        [ 14,  37, 273],
        ...,
        [ 45,  15, 189],
        [ 57,  21,  34],
        [ 58,  21,  17]], device='cuda:0'), 'segment': tensor([-1, -1, -1,  ..., -1, -1, -1], device='cuda:0'), 'offset': tensor([4727], device='cuda:0'), 'feat': tensor([[ 0.0771,  0.4932,  0.8126, -1.0000, -1.0000, -1.0000],
        [ 0.0203,  0.3226,  1.3666, -1.0000, -1.0000, -1.0000],
        [-0.2112,  0.1075,  5.2908, -1.0000, -1.0000, -1.0000],
        ...,
        [ 0.2122, -0.0066,  4.0391,  0.8588,  0.9686,  1.0000],
        [ 0.4521,  0.1313,  0.9356,  0.8588,  0.8902,  1.0000],
        [ 0.4733,  0.1140,  0.5891,  0.9373,  0.8745,  0.8353]],
       device='cuda:0')}
```
I tried to see what transform would cause that but I can not print the data_dict after transformation. I do not know where the data is loaded, I tried several prints in several files but nothing conclusive. Do you have an idea of what could cause the all -1 segment ? Given that my segment values are before processing 0 and 1. If not, do you have an idea on how to debug it ? Thank you

**Comment by Gofinge** [comment]
So, if your point cloud is labelled sparsely, you might lose them during Random GridSampling and SphereCrop. If they are sparse, I think you can modify these sampling strategies, and make them more likely to be sampled during these augmentations.

**Comment by adamvln** [comment]
Hi, 
My point cloud is not sparsely labeled. All the points have a label !

**Comment by adamvln** [comment]
Hi, 
I have another problem which might be caused by class imbalance and wanted to have your opinions. As the network trains, it only learns to predict the second class of my binary semantic segmentation problem. This second class having 10 times less points than the first class. For somer reason, the accuracy of my smallest class is really good during training while the IOUs are small. 

```
[2024-04-16 13:57:22,180 INFO evaluator.py line 174 2155671] Val result: mIoU/mAcc/allAcc 0.2084/0.5206/0.3475.
[2024-04-16 13:57:22,180 INFO evaluator.py line 180 2155671] Class_0-unlabelled Result: iou/accuracy 0.2472/0.2582
[2024-04-16 13:57:22,180 INFO evaluator.py line 180 2155671] Class_1-light source Result: iou/accuracy 0.1695/0.7831
[2024-04-16 13:57:22,180 INFO evaluator.py line 194 2155671] <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
[2024-04-16 13:57:22,181 INFO misc.py line 165 2155671] Currently Best mIoU: 0.2087
```
Here is also an example of an output tensor of the model, seems that it is only predicting label 1, so my smallest class : 

```
tensor([[-3.7656,  2.2266],
        [-4.3164,  2.2422],
        [-4.9219,  3.9297],
        ...,
        [-4.6875,  2.8613],
        [-3.7598,  3.8594],
        [-3.7871,  3.3594]], device='cuda:0', dtype=torch.float16,
       grad_fn=<AddmmBackward0>)
```


I added class weights to the Cross-Entropy Loss in the config file. No matter the weights that I input, the model always learn to only predict the second class for some reason. I will keep experimenting, but wondered first if you had an idea to help ? 
Thank you

**Comment by Gofinge** [comment]
> Hi, I have another problem which might be caused by class imbalance and wanted to have your opinions. As the network trains, it only learns to predict the second class of my binary semantic segmentation problem. This second class having 10 times less points than the first class. For somer reason, the accuracy of my smallest class is really good during training while the IOUs are small.
> 
> ```
> [2024-04-16 13:57:22,180 INFO evaluator.py line 174 2155671] Val result: mIoU/mAcc/allAcc 0.2084/0.5206/0.3475.
> [2024-04-16 13:57:22,180 INFO evaluator.py line 180 2155671] Class_0-unlabelled Result: iou/accuracy 0.2472/0.2582
> [2024-04-16 13:57:22,180 INFO evaluator.py line 180 2155671] Class_1-light source Result: iou/accuracy 0.1695/0.7831
> [2024-04-16 13:57:22,180 INFO evaluator.py line 194 2155671] <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
> [2024-04-16 13:57:22,181 INFO misc.py line 165 2155671] Currently Best mIoU: 0.2087
> ```
> 
> Here is also an example of an output tensor of the model, seems that it is only predicting label 1, so my smallest class :
> 
> ```
> tensor([[-3.7656,  2.2266],
>         [-4.3164,  2.2422],
>         [-4.9219,  3.9297],
>         ...,
>         [-4.6875,  2.8613],
>         [-3.7598,  3.8594],
>         [-3.7871,  3.3594]], device='cuda:0', dtype=torch.float16,
>        grad_fn=<AddmmBackward0>)
> ```
> 
> I added class weights to the Cross-Entropy Loss in the config file. No matter the weights that I input, the model always learn to only predict the second class for some reason. I will keep experimenting, but wondered first if you had an idea to help ? Thank you

Hi, check the additional LovaszLoss we used (https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-pt-v3m1-0-base.py#L50).

**Comment by Mehrdad-Hosseini1992** [comment]
Hello Mr @Gofinge , thanks for your response
this is the distribution of my data:

Other	                 12,042,142 
Sidewalk	                 86,440,848 
Road and asphalt	 160,843,736 
Curb cut	                  6,167,570 
Vegetation	          8,958,736 
Tree	                         10,952,274 
Post	                         4,101,434 
Ramp	                 217,978 
Road-sign	         724,858 
Building	                 88,872,444 
Step	                        490,386 
Door	                1,441,536

As you can see, I have an aggressive class imbalance in my data, and I imagine that with the GridSample function, it will be very hard to determine these minority classes. I want to know what is your suggestions ??

**Comment by Gofinge** [comment]
I think this is not related to GridSample, as it is just faith to sample point with an even density.  From the learning aspect, we usually optimize criteria like weighed CE or LovaszLoss to make the situation better. Or some guys do some augmentation like placing more rare cases in the scene.

**Comment by Mehrdad-Hosseini1992** [comment]
Okay, I knew that this was unrelated to the GridSample Function. However, I noticed that in my point clouds after sampling, I lost a significant number of points from my minority class. This loss indicates that I'm losing key geometric features.
By the way, I use the RTX 4090 GPU (24 GB memory), and with this distribution of data, I have a problem with grid_size. I cannot set the number below 0.9

**Comment by Gofinge** [comment]
> I noticed that in my point clouds after sampling, I lost a significant number of points from my minority class.

This means that the unsampled reign of the minority class is too dense. It doesn't mean more point contains more information and you can easily adjust the weight of minority class in CE loss.

> By the way, I use the RTX 4090 GPU (24 GB memory), and with this distribution of data, I have a problem with grid_size. I cannot set the number below 0.9

I think, maybe you need to chunk the data as replied in another issue. The grid_size should be determined by the granularity of perception. Maybe 0.9 is too sparse for a good perception.

**Comment by softword-tt** [comment]
@adamvln  Hi, do you solve this problem about only predicting the second class? I have the same mode output, and for my dataset, label 0 is the background while label 1 is the moving object. I also tried the weighted Cross-Entropy Loss, LovaszLoss, and FocalLoss, but they did not work. 

> tensor([[-3.8189,  2.5940],
        [-4.8542,  3.2902],
        [-3.8579,  3.6308],
        [-3.4078,  3.1766],
        [-3.9245,  3.1049]], device='cuda:4')
tensor([[-4.8246,  2.8890],
        [-4.3802,  3.6335],
        [-4.2589,  4.9231],
        [-4.7732,  4.6433],
        [-4.5124,  3.9538]], device='cuda:2')
tensor([[-3.9236,  2.6669],
        [-4.2826,  3.3870],
        [-3.0169,  3.9278],
        [-3.9116,  2.9352],
        [-4.7799,  3.6003]], device='cuda:6')
