### ISSUE TITLE
Error when parsing normal on S3DIS

### ISSUE THREAD

**Issue by Ma-Weijian** [Pointcept/Pointcept#23]
Hi,

Reallly fantastic codebase.

However, I've met some issues on processing S3DIS data.

When i use the following command,
`
python pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR} --raw_root ${RAW_S3DIS_DIR} --align_angle --parse_normal
`

I've met the following error report.
```
Loading room information ...
Loading raw mesh file ...
[Open3D WARNING] Read OBJ failed: Cannot open file [/hy-tmp/s3dis_raw/Stanford3dDataset_v1.2/area_1/3d/rgb.obj]

Traceback (most recent call last):
  File "pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 169, in <module>
    main_process()
  File "pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 142, in main_process
    mesh.triangle_uvs.clear()
AttributeError: 'open3d.open3d_pybind.utility.Vector2dVector' object has no attribute 'clear'
```
I‘ve installed all packages as is mentioned in README.md and the version of open3d is 0.10.0.

I wonder if there is anything wrong with it.

Anyting helps!

Thanks a lot!

Weijian

**Comment by Gofinge** [comment]
Hi, the error seems to occur because `'open3d.open3d_pybind.utility.Vector2dVector' object has no attribute 'clear'`. But I checked the latest o3d docs, and `clear` is an attribute of `Vector2dVector`, could you provide your installed o3d version, and then I will further check the reason.

<img width="1051" alt="image" src="https://github.com/Pointcept/Pointcept/assets/39218229/f563a2f4-af03-486e-a7b5-1c9a1251f290">

**Comment by Ma-Weijian** [comment]
It is 0.10.0.0 as mentioned above

**Comment by Ma-Weijian** [comment]
I tried to upgrade my open3d version, but there's still an error report that it is not compatible with torch-points3d whose version is 1.3.0. Here's the entire result of conda list.
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
addict                    2.4.0              pyhd8ed1ab_2    conda-forge
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
bleach                    6.0.0                    pypi_0    pypi
blinker                   1.6.2                    pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
c-ares                    1.19.0               hd590300_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
ccimport                  0.4.2                    pypi_0    pypi
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h5eee18b_3    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
click                     8.1.3                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3                    pypi_0    pypi
configargparse            1.5.3                    pypi_0    pypi
configparser              5.3.0                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1           py38h9ce1e76_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
cudatoolkit               11.3.1               h2bc3f7f_2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
cumm-cu113                0.4.9                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dash                      2.9.3                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.1              pyhd8ed1ab_0    conda-forge
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
fire                      0.5.0                    pypi_0    pypi
flask                     2.3.2                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
fsspec                    2023.5.0           pyh1a96a4e_0    conda-forge
ftfy                      6.1.1                    pypi_0    pypi
gdown                     3.15.0                   pypi_0    pypi
giflib                    5.2.1                h5eee18b_3    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
gnutls                    3.6.15               he1e5248_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
google-sparsehash         2.0.3                         1    bioconda
googledrivedownloader     0.4                      pypi_0    pypi
gql                       0.2.0                    pypi_0    pypi
graphql-core              1.1                      pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h5py                      2.10.0           py38h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
huggingface_hub           0.14.1             pyhd8ed1ab_0    conda-forge
hydra-core                0.11.3                   pypi_0    pypi
idna                      3.4              py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
imageio                   2.28.1                   pypi_0    pypi
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
ipykernel                 6.23.1                   pypi_0    pypi
ipython                   8.12.2                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
jsonpatch                 1.32                     pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.5.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
lark                      1.1.5                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
lerc                      3.0                  h295c915_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libblas                   3.9.0           1_h6e990d7_netlib    conda-forge
libcblas                  3.9.0           3_h893e4fe_netlib    conda-forge
libdeflate                1.17                 h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libgcc                    7.2.0                h69d50b8_2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libgfortran4              7.5.0               ha8ba4b0_17    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libiconv                  1.16                 h7f8727e_2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libidn2                   2.3.4                h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
liblapack                 3.9.0           3_h893e4fe_netlib    conda-forge
libpng                    1.6.39               h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libprotobuf               3.15.8               h780b84a_1    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libtasn1                  4.19.0               h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libtiff                   4.5.0                h6a678d5_2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libunistring              0.9.10               h27cfd23_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libwebp                   1.2.4                h11a3e52_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libwebp-base              1.2.4                h5eee18b_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
llvm-openmp               14.0.6               h9e868ea_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
llvmlite                  0.33.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
markdown                  3.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2            py38h1de0b5d_0    conda-forge
matplotlib                3.6.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mkl                       2020.2                      256    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py38he904b0f_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.4.0                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
nest-asyncio              1.5.6                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
ninja-base                1.10.2               hd09550d_5    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.50.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 1.4.1                    pypi_0    pypi
open3d                    0.10.0.0                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
openssl                   1.1.1t               h0b41bf4_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pccm                      0.4.7                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.4.0            py38h6a678d5_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pip                       23.0.1           py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.5.1                    pypi_0    pypi
plotly                    5.14.1                   pypi_0    pypi
plyfile                   0.7.4                    pypi_0    pypi
pointgroup-ops            0.0.0                    pypi_0    pypi
pointops                  1.0                      pypi_0    pypi
pointops2                 1.0                      pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.23.1                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pybind11                  2.10.4                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.0.0           py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pyparsing                 3.0.9                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
python                    3.8.16               h7a1cb2a_3    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-louvain            0.16                     pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-cluster           1.6.0           py38_torch_1.12.0_cu113    pyg
pytorch-metric-learning   0.9.99                   pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.1.0           py38_torch_1.12.0_cu113    pyg
pytorch-sparse            0.6.16          py38_torch_1.12.0_cu113    pyg
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0              py38h5eee18b_1    anaconda
pyzmq                     25.0.2                   pypi_0    pypi
rdflib                    6.3.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
regex                     2023.5.5                 pypi_0    pypi
requests                  2.29.0           py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.3.1            py38h0cc4f7c_0    conda-forge
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.5.3            py38h828c644_0    conda-forge
send2trash                1.8.2                    pypi_0    pypi
sentry-sdk                1.23.1                   pypi_0    pypi
setuptools                66.0.0           py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
sharedarray               3.2.1                    pypi_0    pypi
shortuuid                 1.0.11                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
spconv-cu113              2.3.6                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
stack-data                0.6.2                    pypi_0    pypi
subprocess32              3.5.4                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboardx              2.5.1              pyhd8ed1ab_0    conda-forge
termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
timm                      0.9.2              pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torch-geometric           1.7.2                    pypi_0    pypi
torch-points-kernels      0.6.10                   pypi_0    pypi
torch-points3d            1.3.0                    pypi_0    pypi
torchaudio                0.12.1               py38_cu113    pytorch
torchnet                  0.0.4                    pypi_0    pypi
torchsparse               2.0.0b0                  pypi_0    pypi
torchvision               0.13.1               py38_cu113    pytorch
tornado                   6.3.2                    pypi_0    pypi
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0                    pypi_0    pypi
trimesh                   3.21.7             pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0            py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
typing_extensions         4.5.0            py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
tzdata                    2023.3                   pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.15          py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
visdom                    0.2.4                    pypi_0    pypi
wandb                     0.8.36                   pypi_0    pypi
watchdog                  3.0.0                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.3.4              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4           py38h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
widgetsnbextension        4.0.7                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
yaml                      0.2.5                h7b6447c_0    anaconda
yapf                      0.33.0             pyhd8ed1ab_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
zstd                      1.5.5                hc292b87_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
```

**Comment by Gofinge** [comment]
V0.10.0.0 seems to be a really old version.  And torch-points3d is not necessary, you can uninstall it.
