### ISSUE TITLE
Missing dependency "clip" for PPT training

### ISSUE THREAD

**Issue by xjh19971** [Pointcept/Pointcept#235]
Hi, thanks for your impressive work on PTv3 and PPT. I am trying to train with PTv3 and PPT settings while finding that the following error raises

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/scratch/jx1190/Pointcept/exp/scannet/semseg-pt-v3m1-1-ppt-extreme/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "/scratch/jx1190/Pointcept/exp/scannet/semseg-pt-v3m1-1-ppt-extreme/code/pointcept/models/point_prompt_training/point_prompt_training_v1m1_language_guided.py", line 61, in __init__
    import clip
ModuleNotFoundError: No module named 'clip'
```

I think this is because the "clip" dependency is missing from the environment setup. Thank you!

**Comment by Gofinge** [comment]
Oh, thanks for your kind reminder. This is an additional dependence from Point Prompt Training
