### ISSUE TITLE
KeyError: 'No history metric available for val_loss!'

### ISSUE THREAD

**Issue by Ma-Weijian** [Pointcept/Pointcept#24]
Hi, 

When I run the training script below
`
sh scripts/train.sh -d s3dis -c semseg-ptv2m2-0-base -n semseg-ptv2m2-0-base-test -g 3
`

I have met the following error.
```
Experiment name: semseg-ptv2m2-0-base-test
Python interpreter dir: python
Dataset: s3dis
Config: semseg-ptv2m2-0-base
GPU Num: 3
 =========> CREATE EXP DIR <=========
Experiment dir: /root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test
Loading config in: configs/s3dis/semseg-ptv2m2-0-base.py
Running code in: exp/s3dis/semseg-ptv2m2-0-base-test/code
 =========> RUN TASK <=========
[2023-05-22 12:12:53,447 INFO train.py line 112 15561] => Loading config ...
[2023-05-22 12:12:53,447 INFO train.py line 114 15561] Save path: exp/s3dis/semseg-ptv2m2-0-base-test
[2023-05-22 12:12:54,249 INFO train.py line 115 15561] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 41401978
save_path = 'exp/s3dis/semseg-ptv2m2-0-base-test'
num_worker = 16
batch_size = 12
batch_size_val = 3
batch_size_test = 1
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
max_batch_points = 100000000.0
mix_prob = 0.8
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None)
]
test = dict(type='SemSegTester')
model = dict(
......
)
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(type='MultiStepLR', milestones=[0.6, 0.8], gamma=0.1)
dataset_type = 'S3DISDataset'
data_root = 'data/s3dis'
data = dict(
,,,,,,
)
num_worker_per_gpu = 5
batch_size_per_gpu = 4
batch_size_val_per_gpu = 1

[2023-05-22 12:12:54,249 INFO train.py line 116 15561] => Building model ...
[2023-05-22 12:12:54,348 INFO train.py line 190 15561] Num params: 3908641
[2023-05-22 12:12:54,433 INFO train.py line 118 15561] => Building writer ...
[2023-05-22 12:12:54,434 INFO train.py line 198 15561] Tensorboard writer logging dir: exp/s3dis/semseg-ptv2m2-0-base-test
[2023-05-22 12:12:54,434 INFO train.py line 120 15561] => Building train dataset & dataloader ...
[2023-05-22 12:12:54,435 INFO s3dis.py line 49 15561] Totally 0 x 30 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6') set.
[2023-05-22 12:12:54,435 INFO train.py line 122 15561] => Building val dataset & dataloader ...
[2023-05-22 12:12:54,435 INFO s3dis.py line 49 15561] Totally 0 x 1 samples in Area_5 set.
[2023-05-22 12:12:54,436 INFO train.py line 124 15561] => Building optimize, scheduler, scaler(amp) ...
[2023-05-22 12:12:54,438 INFO train.py line 128 15561] => Building hooks ...
[2023-05-22 12:12:54,438 INFO misc.py line 175 15561] => Loading checkpoint & weight ...
[2023-05-22 12:12:54,438 INFO misc.py line 194 15561] No weight found at: None
[2023-05-22 12:12:54,438 INFO train.py line 135 15561] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
[2023-05-22 12:12:54,631 INFO misc.py line 124 15561] Train result: 
[2023-05-22 12:12:54,631 INFO evaluator.py line 83 15561] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "exp/s3dis/semseg-ptv2m2-0-base-test/code/tools/train.py", line 34, in <module>
    main()
  File "exp/s3dis/semseg-ptv2m2-0-base-test/code/tools/train.py", line 23, in main
    launch(
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/launch.py", line 72, in launch
    mp.spawn(
  File "/usr/local/miniconda3/envs/point2cadseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/miniconda3/envs/point2cadseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/miniconda3/envs/point2cadseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/point2cadseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/launch.py", line 131, in _distributed_worker
    main_func(*cfg)
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/tools/train.py", line 16, in main_worker
    trainer.train()
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/train.py", line 153, in train
    self.after_epoch()
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/train.py", line 93, in after_epoch
    h.after_epoch()
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/hooks/evaluator.py", line 80, in after_epoch
    self.eval()
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/engines/hooks/evaluator.py", line 117, in eval
    loss_avg = self.trainer.storage.history("val_loss").avg
  File "/root/Pointcept/exp/s3dis/semseg-ptv2m2-0-base-test/code/pointcept/utils/events.py", line 378, in history
    raise KeyError("No history metric available for {}!".format(name))
KeyError: 'No history metric available for val_loss!'
```

Does anyone know how to fix it?

A million thanks.

Weijian

**Comment by Gofinge** [comment]
```
Totally 0 x 30 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6') set.
```

Please check if you have linked the data to `data/s3dis/`.

**Comment by Ma-Weijian** [comment]
Okay, thanks, i linked the data and it works fine
