### ISSUE TITLE
Runtime error (size mismatch) when running the test on a custom dataset

### ISSUE THREAD

**Issue by FSet89** [Pointcept/Pointcept#254]
I successfully trained a semantic segmentation model for my custom dataset using the default segmentor and Point Transformer V3. The train and test datasets are two point clouds files with 8M and 5M points, respectively. When I try to run the test script I get the error below. The config for train and test data was the same that I used in #253 

> Traceback (most recent call last):
>   File "tools/test.py", line 38, in <module>
>     main()
>   File "tools/test.py", line 27, in main
>     launch(
>   File "/home/utente/Projects/Pointcept/pointcept/engines/launch.py", line 89, in launch
>     main_func(*cfg)
>   File "tools/test.py", line 20, in main_worker
>     tester.test()
>   File "/home/utente/Projects/Pointcept/pointcept/engines/test.py", line 160, in test
>     for idx, data_dict in enumerate(self.test_loader):
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
>     data = self._next_data()
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
>     return self._process_data(data)
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
>     data.reraise()
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
>     raise exception
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/utente/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/utente/Projects/Pointcept/pointcept/datasets/custom.py", line 126, in __getitem__
>     return self.prepare_test_data(idx)
>   File "/home/utente/Projects/Pointcept/pointcept/datasets/custom.py", line 112, in prepare_test_data
>     input_dict_list[i] = self.post_transform(input_dict_list[i])
>   File "/home/utente/Projects/Pointcept/pointcept/datasets/transform.py", line 1150, in __call__
>     data_dict = t(data_dict)
>   File "/home/utente/Projects/Pointcept/pointcept/datasets/transform.py", line 51, in __call__
>     data[name] = torch.cat([data_dict[key].float() for key in keys], dim=1)
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 474426 but got size 5026134 for tensor number 1 in the list.

Here is my custom dataset:

```
import os
import numpy as np
from torch.utils.data import Dataset
from copy import deepcopy
from pointcept.utils.logger import get_root_logger
from .builder import DATASETS
from .transform import Compose, TRANSFORMS


@DATASETS.register_module()
class CustomDataset(Dataset):
    def __init__(
        self,
        split="train",
        data_root="data/custom",
        class_names=None,
        transform=None,
        test_mode=False,
        test_cfg=None,
        cache_data=False,
        loop=1,
    ):
        super(CustomDataset, self).__init__()
        self.data_root = data_root
        self.split = split
        self.transform = Compose(transform)
        self.loop = (
            loop if not test_mode else 1
        )  # force make loop = 1 while in test mode
        self.cache_data = cache_data
        self.test_mode = test_mode
        self.test_cfg = test_cfg if test_mode else None
        self.cache = {}
        if test_mode:
            self.test_voxelize = TRANSFORMS.build(self.test_cfg.voxelize)
            self.test_crop = (
                TRANSFORMS.build(self.test_cfg.crop) if self.test_cfg.crop else None
            )
            self.post_transform = Compose(self.test_cfg.post_transform)
            self.aug_transform = [Compose(aug) for aug in self.test_cfg.aug_transform]

        self.data_list = self.get_data_list()
        logger = get_root_logger()
        logger.info(
            "Totally {} x {} samples in {} set.".format(
                len(self.data_list), self.loop, split
            )
        )

    def get_data_list(self):
        # split: train/val 
        data_list = os.listdir(os.path.join(self.data_root, self.split))
        data_list = [os.path.join(self.data_root, self.split, f) for f in data_list]

        return data_list

    def get_data(self, idx):
        data_idx = idx % len(self.data_list)
        if self.cache_data:
            coord, color, segment = self.cache[data_idx]
        else:            
            data_path = self.data_list[data_idx]           
            data = np.loadtxt(data_path, delimiter=",").astype(np.float32)
            coord, color, normals, segment = data[:, 0:3], \
                                            data[:, 3:6], \
                                            data[:, 6:9], \
                                            data[:, 9]
            segment = segment.astype(np.uint8)
            if self.cache_data:
                self.cache[data_idx] = (coord, color, segment)

        data_dict = dict(coord=coord, 
                        segment=segment,
                        normal=normals,
                        color=color)
        return data_dict

    def prepare_train_data(self, idx):
        data_dict = self.get_data(idx)
        data_dict = self.transform(data_dict)
        return data_dict

    def prepare_test_data(self, idx):
        data_dict = self.get_data(idx)
        segment = data_dict.pop("segment")
        data_dict = self.transform(data_dict)
        data_dict_list = []
        for aug in self.aug_transform:
            data_dict_list.append(aug(deepcopy(data_dict)))

        input_dict_list = []
        for data in data_dict_list:
            data_part_list = self.test_voxelize(data)
            for data_part in data_part_list:
                if self.test_crop:
                    data_part = self.test_crop(data_part)
                else:
                    data_part = [data_part]
                input_dict_list += data_part

        for i in range(len(input_dict_list)):
            input_dict_list[i] = self.post_transform(input_dict_list[i])
        data_dict = dict(
            fragment_list=input_dict_list, segment=segment, 
            name=self.get_data_name(idx)
        )
        return data_dict
        

    def get_data_name(self, idx):
        data_idx = idx % len(self.data_list)
        return self.data_list[data_idx]

    def __getitem__(self, idx):
        if self.test_mode:
            return self.prepare_test_data(idx)
        else:
            return self.prepare_train_data(idx)

    def __len__(self):
        return len(self.data_list) * self.loop
```

The error is raised when calling `Collect` and the mismatching features are color and normal:
`[torch.Size([474426, 3]), torch.Size([5026134, 3])]`

The problem is generated by `test_voxelize().` Here are the keys and shapes before and after.
```
dict_keys(['coord', 'normal', 'color']) [(5026134, 3), (5026134, 3), (5026134, 3)]
dict_keys(['index', 'grid_coord', 'coord', 'normal', 'color']) [(519029,), (519029, 3), (519029, 3), (5026134, 3), (519029, 3)]
```

**Comment by FSet89** [comment]
My bad. I had to include `normal` in voxelize keys in the config file.
