### ISSUE TITLE
Error during train "AttributeError: Caught AttributeError in DataLoader worker process 0.   RuntimeError: Trying to resize storage that is not resizable"

### ISSUE THREAD

**Issue by fine4546** [Pointcept/Pointcept#26]
I use s3dis dataset and going to check the train.

command
python tools/train.py --num-gpus 4 --config-file "configs/s3dis/semseg-ptv1-0-base.py"

Why is the error occurring?

Maybe you can't get the data?

[2023-05-23 20:27:08,227 INFO train.py line 135 744929] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>

Traceback (most recent call last):
  File "tools/train.py", line 38, in <module>
    main()
  File "tools/train.py", line 27, in main
    launch(
  File "/raid/Pointcept/pointcept/engines/launch.py", line 72, in launch
    mp.spawn(
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/raid/Pointcept/pointcept/engines/launch.py", line 131, in _distributed_worker
    main_func(*cfg)
  File "/raid/Pointcept/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/raid/Pointcept/pointcept/engines/train.py", line 147, in train
    for self.comm_info["iter"], self.comm_info["input_dict"] in self.data_iterator:
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/raid/Pointcept/pointcept/datasets/utils.py", line 46, in point_collate_fn
    batch = collate_fn(batch)
  File "/raid/Pointcept/pointcept/datasets/utils.py", line 35, in collate_fn
    batch = {key: collate_fn([d[key] for d in batch]) for key in batch[0]}
  File "/raid/Pointcept/pointcept/datasets/utils.py", line 35, in <dictcomp>
    batch = {key: collate_fn([d[key] for d in batch]) for key in batch[0]}
  File "/raid/Pointcept/pointcept/datasets/utils.py", line 41, in collate_fn
    return default_collate(batch)
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/nvadmin/anaconda3/envs/pc38/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 140, in default_collate
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable

**Comment by Gofinge** [comment]
Hi, I am sorry that I can't figure out the reason. But I notice that the error occurs in 'torch/utils/data/dataloader', maybe reinstalling the environment can solve the problem.
