### ISSUE TITLE
CUDA Error: Device-Side Assert Triggered 

### ISSUE THREAD

**Issue by adamvln** [Pointcept/Pointcept#282]
My training runs but on the 10th epochs I have this error. I tried using different python versions but seem to always have that error stopping the training. I purposefully did not paste all the '/opt/conda/conda-bld/pytorch_1678402379298/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [3,0,0], thread: [125,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.' as there are way more. 

`
/opt/conda/conda-bld/pytorch_1678402379298/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [3,0,0], thread: [125,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1678402379298/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [3,0,0], thread: [126,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1678402379298/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [3,0,0], thread: [127,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
[W CUDAGuardImpl.h:124] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
Traceback (most recent call last):
  File "tools/train.py", line 42, in <module>
    main()
  File "tools/train.py", line 31, in main
    launch(
  File "/gpfs/home4/avalin/CityThesis/Pointcept/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/gpfs/home4/avalin/CityThesis/Pointcept/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/gpfs/home4/avalin/CityThesis/Pointcept/tools/train.py", line 24, in main_worker
    trainer.train()
  File "/gpfs/home4/avalin/CityThesis/Pointcept/pointcept/engines/train.py", line 168, in train
    self.run_step()
  File "/gpfs/home4/avalin/CityThesis/Pointcept/pointcept/engines/train.py", line 186, in run_step
    self.scaler.scale(loss).backward()
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/avalin/.conda/envs/pointcept_117/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`

**Comment by xjh19971** [comment]
I have a similar issue when I enabled AMP and trained with PTv3 + PPT. See Issue https://github.com/Pointcept/Pointcept/issues/249#issue-2289986447.

**Comment by SpeedyGonzales949** [comment]
Mine crashes after 3 epochs on the same line `self.scaler.scale(loss).backward()`.

**Comment by Gofinge** [comment]
Yes, one known issue. Two suggestions:
1. disable AMP;
2. Enable clip on gradient. (I haven't try this)

**Comment by 1301358882** [comment]
> 当我启用 AMP 并使用 PTv3 + PPT 进行训练时，我遇到了类似的问题。请参阅问题[#249（评论）](https://github.com/Pointcept/Pointcept/issues/249#issue-2289986447)。

Hello, I set enable_amp to False and still get the error RuntimeError: CUDA error: device-side assert triggered. Is there any other solution?

**Comment by magical1998** [comment]
> > 当我启用 AMP 并使用 PTv3 + PPT 进行训练时，我遇到了类似的问题。请参阅问题[#249（评论）](https://github.com/Pointcept/Pointcept/issues/249#issue-2289986447)。
> 
> Hello, I set enable_amp to False and still get the error RuntimeError: CUDA error: device-side assert triggered. Is there any other solution?您好，我将 enable_amp 设置为 False，但仍然收到错误 RuntimeError： CUDA error： device-side assert triggered。还有其他解决方案吗？

Have you solved this problem yet?

**Comment by cnmicha** [comment]
@Gofinge Thank you very much for your work. I have the same issue, training crashes after some epochs during `self.scaler.scale(loss).backward()`. NVIDIA A100 80GB GPU.

I tried to enable gradient clipping by setting `clip_grad = 3.0`, but the error still occurs. AMP is enabled.

**Comment by Gofinge** [comment]
This issue is caused by Flash Attention occasionally. I recently changed the dtype from fp16 to bp16, not sure whether it will help. Also, some advanced learning rate layer-wise scaler (refer to the Sonata config) would also be helpful. And widely adjusting the learning rate might also be helpful.

**Comment by ydayda** [comment]
@Gofinge hi, 
I set the env setting before run the cmd:
```
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=ALL
```
get the ERROR:
```
/opt/conda/conda-bld/pytorch_1728929546833/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [157,0,0], thread: [91,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1728929546833/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [157,0,0], thread: [92,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1728929546833/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [157,0,0], thread: [93,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1728929546833/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [157,0,0], thread: [94,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1728929546833/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [157,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
```

my train process goes well as you can see in train.log, but suddenly get the error!
train.log:
[train.log](https://github.com/user-attachments/files/25620701/train.log)



error.log:
[error.log](https://github.com/user-attachments/files/25620707/error.log)

I will try the below setting to see if it is ok!

> Yes, one known issue. Two suggestions:
> 
> 1. disable AMP;
> 2. Enable clip on gradient. (I haven't try this)
