### ISSUE TITLE
Low Accuracy on PTv3 Nuscenes dataset using pre-trained model

### ISSUE THREAD

**Issue by Bryan1203** [Pointcept/Pointcept#284]
Hi, I am trying to use the pre-trained model provided in the [exp record](https://huggingface.co/Pointcept/PointTransformerV3/tree/main/nuscenes-semseg-pt-v3m1-0-base) to do the inference on the Nuscene dataset, disabling flash attn. I am using the Nuscene mini dataset (contains 10 scenes (6 for train and 4 for validate) instead of 850 of the full dataset). However, I am getting very low accuracy Val result: mIoU/mAcc/allAcc 0.0431/0.1552/0.2255. Is this normal or am I doing something wrong? 

Is it because that I am using v1.5.2 but the released weight is for v1.5.1? 

But when I switched to v1.5.1 and running the test.py `python tools/test.py --config-file ~/pointcept_bryan/configs/nuscenes/nuscenes-semseg-pt-v3m1-0-base_config.py --options save_path=exp/nuscenes_test4/nuscenes-semseg-pt-v3m1-0-base weight=~/pointcept_bryan/exp/nuscenes/nuscenes-semseg-pt-v3m1-0-base/model_best.pth` 

I am getting this error: `Traceback (most recent call last):
  File "tools/test.py", line 13, in <module>
    from pointcept.engines.test import TESTERS
  File "/home/bryanchang/pointcept151/pointcept/engines/test.py", line 20, in <module>
    from pointcept.models import build_model
  File "/home/bryanchang/pointcept151/pointcept/models/__init__.py", line 11, in <module>
    from .octformer import *
  File "/home/bryanchang/pointcept151/pointcept/models/octformer/__init__.py", line 1, in <module>
    from .octformer_v1m1_base import OctFormer
  File "/home/bryanchang/pointcept151/pointcept/models/octformer/octformer_v1m1_base.py", line 32, in <module>
    class OctreeT(Octree):
TypeError: NoneType takes no arguments`

This is the log, config file, and the preprocess script I used:

[test.log](https://github.com/user-attachments/files/15964989/test.log)
[config file](https://github.com/Bryan1203/Pointcept/blob/main/configs/nuscenes/nuscenes-semseg-pt-v3m1-0-base_config.py)
[preprocess nuscenes](https://github.com/Bryan1203/Pointcept/blob/main/pointcept/datasets/preprocessing/nuscenes/preprocess_nuscenes_info_train_val.py)

For processing the mini dataset only generate pkl files for train and val but not test since in the config file the test dict is set to val by default.

**Comment by Bryan1203** [comment]
It turns out its the v1.5.1 model weights that need to corresponds to the correct version of the code base according to #248. 

Furthermore, the fix for the OctFormer Error `
  File "/home/bryanchang/pointcept151/pointcept/models/octformer/octformer_v1m1_base.py", line 32, in <module>
    class OctreeT(Octree):
TypeError: NoneType takes no arguments` is not commited to the v1.5.1 version. Fixed in #150. @Gofinge it might be better to include this fix in the v1.5.1 version? 

Last, I encountered ModuleNotFoundError: No module named 'pointgroup_ops' and fixed in #122

**Comment by Gofinge** [comment]
Sorry for the late response. Really too busy recently.

**Comment by smileyenot983** [comment]
Is there any update? Are the updated weights released already?
