### ISSUE TITLE
When testing minkunet34c, there is an error occurred.

### ISSUE THREAD

**Issue by Leon1207** [Pointcept/Pointcept#31]
Traceback (most recent call last):
  File "exp/scannet/semseg-minkunet34c-0-base/code/tools/test.py", line 94, in <module>
    main()
  File "exp/scannet/semseg-minkunet34c-0-base/code/tools/test.py", line 90, in main
    TEST.build(cfg.test)(cfg, test_loader, model)
  File "/userhome/lyd/PointTransformerV2-main/pcr/engines/test.py", line 71, in __call__
    pred[idx_part[bs: be], :] += pred_part[bs: be]
RuntimeError: The size of tensor a (20) must match the size of tensor b (200) at non-singleton dimension 1

**Comment by Gofinge** [comment]
Hi, could you provide the detailed config, logged at the start of the training?

**Comment by Leon1207** [comment]
Thanks for reply! I used the original code for ptv2: https://github.com/Gofinge/PointTransformerV2

Here is the config:
_base_ = ['../_base_/default_runtime.py',
          '../_base_/tests/segmentation.py']

# misc custom setting
batch_size = 12  # bs: total bs in all gpus
mix_prob = 0.8
empty_cache = False
enable_amp = True

# model settings
model = dict(
    type="MinkUNet34C",
    in_channels=9,
    out_channels=200
)

# scheduler settings
epoch = 600
optimizer = dict(type='SGD', lr=0.05, momentum=0.9, weight_decay=0.0001, nesterov=True)
scheduler = dict(type='OneCycleLR',
                 max_lr=optimizer["lr"],
                 pct_start=0.05,
                 anneal_strategy="cos",
                 div_factor=10.0,
                 final_div_factor=10000.0)


# dataset settings
dataset_type = "ScanNetDataset"
data_root = "/userhome/backup_lhj/dataset/pointcloud/data_for_PTv2/scannet"

data = dict(
    num_classes=20,
    ignore_label=255,
    names=["wall", "floor", "cabinet", "bed", "chair",
           "sofa", "table", "door", "window", "bookshelf",
           "picture", "counter", "desk", "curtain", "refridgerator",
           "shower curtain", "toilet", "sink", "bathtub", "otherfurniture"],
    train=dict(
        type=dataset_type,
        split="train",
        data_root=data_root,
        transform=[
            dict(type="CenterShift", apply_z=True),
            dict(type="RandomDropout", dropout_ratio=0.2, dropout_application_ratio=0.2),
            # dict(type="RandomRotateTargetAngle", angle=(1/2, 1, 3/2), center=[0, 0, 0], axis='z', p=0.75),
            dict(type="RandomRotate", angle=[-1, 1], axis='z', center=[0, 0, 0], p=0.5),
            dict(type="RandomRotate", angle=[-1/64, 1/64], axis='x', p=0.5),
            dict(type="RandomRotate", angle=[-1/64, 1/64], axis='y', p=0.5),
            dict(type="RandomScale", scale=[0.9, 1.1]),
            # dict(type="RandomShift", shift=[0.2, 0.2, 0.2]),
            dict(type="RandomFlip", p=0.5),
            dict(type="RandomJitter", sigma=0.005, clip=0.02),
            dict(type="ElasticDistortion", distortion_params=[[0.2, 0.4], [0.8, 1.6]]),
            dict(type="ChromaticAutoContrast", p=0.2, blend_factor=None),
            dict(type="ChromaticTranslation", p=0.95, ratio=0.05),
            dict(type="ChromaticJitter", p=0.95, std=0.05),
            # dict(type="HueSaturationTranslation", hue_max=0.2, saturation_max=0.2),
            # dict(type="RandomColorDrop", p=0.2, color_augment=0.0),
            dict(type="Voxelize", voxel_size=0.02, hash_type='fnv', mode='train', return_discrete_coord=True),
            # dict(type="SphereCrop", point_max=100000, mode='random'),
            dict(type="CenterShift", apply_z=False),
            dict(type="NormalizeColor"),
            dict(type="ShufflePoint"),
            dict(type="ToTensor"),
            dict(type="Collect", keys=("coord", "discrete_coord", "label"), feat_keys=("coord", "normal", "color"))
        ],
        test_mode=False,
    ),

    val=dict(
        type=dataset_type,
        split="val",
        data_root=data_root,
        transform=[
            dict(type="CenterShift", apply_z=True),
            dict(type="Voxelize", voxel_size=0.02, hash_type='fnv', mode='train', return_discrete_coord=True),
            # dict(type="SphereCrop", point_max=1000000, mode='center'),
            dict(type="CenterShift", apply_z=False),
            dict(type="NormalizeColor"),
            dict(type="ToTensor"),
            dict(type="Collect", keys=("coord", "discrete_coord", "label"), feat_keys=("coord", "normal", "color"))
        ],
        test_mode=False,
    ),

    test=dict(
        type=dataset_type,
        split="val",
        data_root=data_root,
        transform=[
            dict(type="CenterShift", apply_z=True),
            dict(type="NormalizeColor"),
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(type="Voxelize",
                          voxel_size=0.02,
                          hash_type="fnv",
                          mode="test",
                          return_discrete_coord=True,
                          keys=("coord", "normal", "color")
                          ),
            crop=None,
            post_transform=[
                dict(type="CenterShift", apply_z=False),
                dict(type="ToTensor"),
                dict(type="Collect", keys=("coord", "discrete_coord", "index"), feat_keys=("coord", "normal", "color"))
            ],
            aug_transform=[
                [dict(type="RandomRotateTargetAngle", angle=[0], axis='z', center=[0, 0, 0], p=1)],
                [dict(type="RandomRotateTargetAngle", angle=[1/2], axis='z', center=[0, 0, 0], p=1)],
                [dict(type="RandomRotateTargetAngle", angle=[1], axis='z', center=[0, 0, 0], p=1)],
                [dict(type="RandomRotateTargetAngle", angle=[3/2], axis='z', center=[0, 0, 0], p=1)]
            ]
        )
    ),
)

criteria = [
    dict(type="CrossEntropyLoss",
         loss_weight=1.0,
         ignore_index=data["ignore_label"])
]

Here is the logged at the start of the training:
[2023-06-04 10:41:13,626 INFO defaults.py line 167 40573] => Loading config ...
[2023-06-04 10:41:13,626 INFO defaults.py line 169 40573] Save path: exp/scannet/semseg-minkunet34c-0-base
[2023-06-04 10:41:14,974 INFO defaults.py line 170 40573] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 37868124
save_path = 'exp/scannet/semseg-minkunet34c-0-base'
num_worker = 32
batch_size = 12
batch_size_val = None
batch_size_test = 1
epoch = 600
eval_epoch = 100
save_freq = None
eval_metric = 'mIoU'
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
max_batch_points = 100000000.0
mix_prob = 0.8
param_dicts = None
test = dict(type='SegmentationTest')
model = dict(type='MinkUNet34C', in_channels=9, out_channels=200)
optimizer = dict(
    type='SGD', lr=0.05, momentum=0.9, weight_decay=0.0001, nesterov=True)
scheduler = dict(
    type='OneCycleLR',
    max_lr=0.05,
    pct_start=0.05,
    anneal_strategy='cos',
    div_factor=10.0,
    final_div_factor=10000.0)
dataset_type = 'ScanNetDataset'
data_root = '/userhome/backup_lhj/dataset/pointcloud/data_for_PTv2/scannet'
data = dict(
    num_classes=20,
    ignore_label=255,
    names=[
        'wall', 'floor', 'cabinet', 'bed', 'chair', 'sofa', 'table', 'door',
        'window', 'bookshelf', 'picture', 'counter', 'desk', 'curtain',
        'refridgerator', 'shower curtain', 'toilet', 'sink', 'bathtub',
        'otherfurniture'
    ],
    train=dict(
        type='ScanNetDataset',
        split='train',
        data_root=
        '/userhome/backup_lhj/dataset/pointcloud/data_for_PTv2/scannet',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='RandomDropout',
                dropout_ratio=0.2,
                dropout_application_ratio=0.2),
            dict(
                type='RandomRotate',
                angle=[-1, 1],
                axis='z',
                center=[0, 0, 0],
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='x',
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='y',
                p=0.5),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(
                type='ElasticDistortion',
                distortion_params=[[0.2, 0.4], [0.8, 1.6]]),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='Voxelize',
                voxel_size=0.02,
                hash_type='fnv',
                mode='train',
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ShufflePoint'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'label'),
                feat_keys=('coord', 'normal', 'color'))
        ],
        test_mode=False,
        loop=6),
    val=dict(
        type='ScanNetDataset',
        split='val',
        data_root=
        '/userhome/backup_lhj/dataset/pointcloud/data_for_PTv2/scannet',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Voxelize',
                voxel_size=0.02,
                hash_type='fnv',
                mode='train',
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'label'),
                feat_keys=('coord', 'normal', 'color'))
        ],
        test_mode=False),
    test=dict(
        type='ScanNetDataset',
        split='val',
        data_root=
        '/userhome/backup_lhj/dataset/pointcloud/data_for_PTv2/scannet',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='Voxelize',
                voxel_size=0.02,
                hash_type='fnv',
                mode='test',
                return_discrete_coord=True,
                keys=('coord', 'normal', 'color')),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'discrete_coord', 'index'),
                    feat_keys=('coord', 'normal', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomRotateTargetAngle',
                'angle': [0],
                'axis': 'z',
                'center': [0, 0, 0],
                'p': 1
            }],
                           [{
                               'type': 'RandomRotateTargetAngle',
                               'angle': [0.5],
                               'axis': 'z',
                               'center': [0, 0, 0],
                               'p': 1
                           }],
                           [{
                               'type': 'RandomRotateTargetAngle',
                               'angle': [1],
                               'axis': 'z',
                               'center': [0, 0, 0],
                               'p': 1
                           }],
                           [{
                               'type': 'RandomRotateTargetAngle',
                               'angle': [1.5],
                               'axis': 'z',
                               'center': [0, 0, 0],
                               'p': 1
                           }]])))
criteria = [dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=255)]
num_worker_per_gpu = 8
batch_size_per_gpu = 3
batch_size_val_per_gpu = 1

**Comment by Gofinge** [comment]
Aha, thanks for pointing out the issue, I will fix it soon. You can change the 'model.out_channels' in config to 20, to fix it.

**Comment by Leon1207** [comment]
Sincerely thanks for the open source!
