### ISSUE TITLE
提供的s3dis下载出错

### ISSUE THREAD

**Issue by Yuehongzhe** [Pointcept/Pointcept#311]
Downloading data: 100%|████████████████████| 2.04G/2.04G [10:08<00:00, 3.35MB/s]
Generating train split:   0%|                      | 0/1 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1750, in _prepare_split_single
    for key, record in generator:
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/packaged_modules/webdataset/webdataset.py", line 113, in _generate_examples
    for example_idx, example in enumerate(self._get_pipeline_from_tar(tar_path, tar_iterator)):
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/packaged_modules/webdataset/webdataset.py", line 49, in _get_pipeline_from_tar
    current_example[field_name] = cls.DECODERS[data_extension](current_example[field_name])
KeyError: '/Area_1/conferenceRoom_1/color.npy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xiazai3.py", line 3, in <module>
    ds = load_dataset("Pointcept/s3dis-compressed")
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/load.py", line 2616, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1029, in download_and_prepare
    self._download_and_prepare(
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1791, in _download_and_prepare
    super()._download_and_prepare(
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1124, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1629, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/wsco2/anaconda3/envs/pointcept/lib/python3.8/site-packages/datasets/builder.py", line 1786, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

**Comment by Gofinge** [comment]
应该不是下载出错，这个是因为我们不是webdataset的数据结构，huggingface自动以webdataset数据结构去读这个数据集了。
手动下载解压或者git lfs clone就好。
