### ISSUE TITLE
KeyError : "normal"

### ISSUE THREAD

**Issue by wuweichao-art** [Pointcept/Pointcept#312]
Hello, when i use the PTv3 to train my dataset（ no normal vector ）, there is a  (key Error : "normal") occurs in the traning process. Do you know how to revise the code to train a dataset with no normal vector! Look forward to your reply,  thank you very much!

**Comment by blueeaglex** [comment]
I got the similar Error when I ran a test on a PTv2 model trained on s3dis. 
```
[2024-08-03 20:14:16,750 INFO test.py line 119 4866] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "tools/test.py", line 38, in <module>
    main()
  File "tools/test.py", line 27, in main
    launch(
  File "/mnt/c/workspace/Pointcept/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "tools/test.py", line 20, in main_worker
    tester.test()
  File "/mnt/c/workspace/Pointcept/pointcept/engines/test.py", line 161, in test
    for idx, data_dict in enumerate(self.test_loader):
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/c/workspace/Pointcept/pointcept/datasets/defaults.py", line 175, in __getitem__
    return self.prepare_test_data(idx)
  File "/mnt/c/workspace/Pointcept/pointcept/datasets/defaults.py", line 142, in prepare_test_data
    data_dict = self.get_data(idx)
  File "/mnt/c/workspace/Pointcept/pointcept/datasets/defaults.py", line 120, in get_data
    np.ones(data_dict["coord"].shape[0], dtype=np.int32) * -1
KeyError: 'coord'
```

**Comment by adithyamurali** [comment]
Maybe this issue helps: https://github.com/Pointcept/Pointcept/issues/196

**Comment by Gofinge** [comment]
@blueeaglex Did you use the official config we released?

**Comment by blueeaglex** [comment]
@blueeaglex  Sorry， mine should be different from the question. I didn't use the right dataset. I've solved the problem after reading #147.
