### ISSUE TITLE
TypeError in S3DIS dataloader

### ISSUE THREAD

**Issue by Cirruscale** [Pointcept/Pointcept#33]
### Issue Description
I am trying to train the Sparse U-Net on the s3dis dataset, but there seems to be some issues with the dataloader.

The preparation of the data set is the same as in the tutorial, but the normal parsing and voxelization parts are not included. The training command is as follows:

```
# S3DIS (without normal)
sh scripts/train.sh -g 2 -d s3dis -c semseg-spunet-v1m1-0-base -n semseg-spunet-v1m1-0-base
```

Generally speaking, the first few epochs of the training process seem to have no obvious abnormalities, but the training script will throw a `TypeError` and crash after a few epochs.  Usually this error will appear in the first 10 epochs, the best time the program ran for 27 epochs. 

Currently, I tried several possible solutions. For example, voxelize point data in advance, disable dataloader cache, change configuration in data transform, etc. But these attempts can only increase or decrease the loading time of the data appropriately, the error persists.

I can't determine what the specific reason is, but it is certain that the code of other **similar research (semantic segmentation on S3DIS)**, and the **part of Pointcept on ScanNet** have no similar problems.

### Experimental Environment

- Hardware: Intel Core i9-10850K (10C20T), 64GB RAM, RTX 3090 x 2
- Host system: Ubuntu 20.04 LTS (Desktop), with Nvidia Driver Version 510 and CUDA 11.6
- Virtualization: ufoym/deepo:cu113 on Dockerhub, with miniconda3 for virtual environment

Python Packages (Partial):
```
# packages in environment at /root/miniconda3/envs/pointcept:
#
# Name                    Version                   Build  Channel
cudatoolkit               11.3.1               h2bc3f7f_2  
cumm-cu113                0.4.9                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
nvidia-ml-py3             7.352.0                  pypi_0    pypi
open3d                    0.10.0.0                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h0b41bf4_0    conda-forge
pandas                    1.4.4                    pypi_0    pypi
pillow                    9.4.0            py38h6a678d5_0  
pip                       23.0.1           py38h06a4308_0  
pointgroup-ops            0.0.0                    pypi_0    pypi
pointops                  1.0                      pypi_0    pypi
pointops2                 1.0                      pypi_0    pypi
python                    3.8.16               h7a1cb2a_3  
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-cluster           1.6.0           py38_torch_1.12.0_cu113    pyg
pytorch-metric-learning   0.9.99                   pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.1.0           py38_torch_1.12.0_cu113    pyg
pytorch-sparse            0.6.16          py38_torch_1.12.0_cu113    pyg
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboardx              2.5.1              pyhd8ed1ab_0    conda-forge
torch-geometric           1.4.3                    pypi_0    pypi
torch-points-kernels      0.6.10                   pypi_0    pypi
torch-points3d            1.3.0                    pypi_0    pypi
torchaudio                0.12.1               py38_cu113    pytorch
torchnet                  0.0.4                    pypi_0    pypi
torchsparse               2.0.0b0                  pypi_0    pypi
torchvision               0.13.1               py38_cu113    pytorch
```

### Console Log

```
[2023-06-06 19:37:59,690 INFO misc.py line 110 45444] Train: [16/100][158/510] Data 0.002 (0.228) Batch 0.298 (0.715) Remain 08:34:34 loss: 0.1350 Lr: 0.08611
[2023-06-06 19:38:00,032 INFO misc.py line 110 45444] Train: [16/100][159/510] Data 0.002 (0.227) Batch 0.342 (0.712) Remain 08:32:50 loss: 0.2400 Lr: 0.08611
[2023-06-06 19:38:00,364 INFO misc.py line 110 45444] Train: [16/100][160/510] Data 0.003 (0.225) Batch 0.330 (0.710) Remain 08:31:04 loss: 0.0785 Lr: 0.08611
[2023-06-06 19:38:00,749 INFO misc.py line 110 45444] Train: [16/100][161/510] Data 0.005 (0.224) Batch 0.386 (0.708) Remain 08:29:35 loss: 0.1246 Lr: 0.08611
[Exception|native_pair]indices=torch.Size([311111, 4]),bs=3,ss=[305, 2251799813685584, 174],algo=ConvAlgo.Native,ksize=[5, 5, 5],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[1, 1, 1],subm=True,transpose=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "scripts/train.py", line 102, in <module>
    main()
  File "scripts/train.py", line 98, in main
    invoke_training_task(args)
  File "scripts/train.py", line 86, in invoke_training_task
    launch(
  File "/Codes/Point Cloud/Pointcept/pointcept/engines/launch.py", line 72, in launch
    mp.spawn(
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/Codes/Point Cloud/Pointcept/pointcept/engines/launch.py", line 131, in _distributed_worker
    main_func(*cfg)
  File "/Codes/Point Cloud/Pointcept/scripts/train.py", line 71, in main_worker
    trainer.train()
  File "/Codes/Point Cloud/Pointcept/pointcept/engines/train.py", line 149, in train
    self.run_step()
  File "/Codes/Point Cloud/Pointcept/pointcept/engines/train.py", line 163, in run_step
    output_dict = self.model(input_dict)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Codes/Point Cloud/Pointcept/pointcept/models/default.py", line 16, in forward
    seg_logits = self.backbone(input_dict)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Codes/Point Cloud/Pointcept/pointcept/models/sparse_unet/spconv_unet_v1m1_base.py", line 176, in forward
    x = self.conv_input(x)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 297, in _conv_forward
    raise e
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 284, in _conv_forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 156, in get_indice_pairs
    num_act_out = SpconvOps.get_indice_pairs(alloc,
TypeError: get_indice_pairs(): incompatible function arguments. The following argument types are supported:
    1. (allocator: spconv.core_cc.csrc.sparse.alloc.ExternalAllocator, indices: cumm.core_cc.tensorview_bind.Tensor, batch_size: int, input_dims: List[int], algo: int, ksize: List[int], stride: List[int], padding: List[int], dilation: List[int], out_padding: List[int], subm: bool, transposed: bool, stream_int: int = 0, num_out_act_bound: int = -1, num_input_act_bound: int = -1) -> int

Invoked with: <spconv.pytorch.cppcore.TorchAllocator object at 0x7f8e4e440810>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f8e923aefb0>, 3, [305, 2251799813685584, 174], 0, [5, 5, 5], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0], True, False, 0

(pointcept) root@efc12c0f95fb:/Codes/Point Cloud/Pointcept# /root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 26 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 204 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

If you have any idea with this problem, I will be very appreciate.

**Comment by Gofinge** [comment]
Hi, what about opening an issue in SpConv Library? The error seems to be raised from SpConv and I haven't encountered a similar error report.

**Comment by Gofinge** [comment]
Usually reinstalling a conda environment is also a good choice.

**Comment by Cirruscale** [comment]
Thank you for your reply, I will try to reinstall a conda environment. 

But before raising a new issue to the SpConv library, I still want to know if there is anything else worth noting about this dataset.

The code base of SpConv does not contain the dataloader part, and the training of Sparse U-Net on ScanNet is also normal.
