### ISSUE TITLE
Model net40 file splicing error

### ISSUE THREAD

**Issue by 1748739403** [Pointcept/Pointcept#337]
(pointcept) hqu@hqu-Z590-UD:~/zj/ptv3$ sh scripts/train.sh -g 2 -d modelnet40 -c cls-pt-v3m1-0-base -n cls-pt-v3m1-0-base
Experiment name: cls-pt-v3m1-0-base
Python interpreter dir: python
Dataset: modelnet40
Config: cls-pt-v3m1-0-base
GPU Num: 2
 =========> CREATE EXP DIR <=========
Experiment dir: /home/hqu/zj/ptv3/exp/modelnet40/cls-pt-v3m1-0-base
Loading config in: configs/modelnet40/cls-pt-v3m1-0-base.py
Running code in: exp/modelnet40/cls-pt-v3m1-0-base/code
 =========> RUN TASK <=========
Traceback (most recent call last):
  File "exp/modelnet40/cls-pt-v3m1-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/modelnet40/cls-pt-v3m1-0-base/code/tools/train.py", line 25, in main
    cfg = default_config_parser(args.config_file, args.options)
  File "/home/hqu/zj/ptv3/exp/modelnet40/cls-pt-v3m1-0-base/code/pointcept/engines/defaults.py", line 115, in default_config_parser
    cfg = Config.fromfile(os.path.join(file_path[:sep], file_path[sep + 1 :]))
  File "/home/hqu/zj/ptv3/exp/modelnet40/cls-pt-v3m1-0-base/code/pointcept/utils/config.py", line 335, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename, use_predefined_variables)
  File "/home/hqu/zj/ptv3/exp/modelnet40/cls-pt-v3m1-0-base/code/pointcept/utils/config.py", line 181, in _file2dict
    check_file_exist(filename)
  File "/home/hqu/zj/ptv3/exp/modelnet40/cls-pt-v3m1-0-base/code/pointcept/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/hqu/zj/ptv3/configs/modelnet40/cls/pt-v3m1-0-base.py" does not exist

**Comment by 1748739403** [comment]
When entering the command sh scripts/train.sh - g 2- d modelnet40- c cls-pt-v3m1-0-base - n cls-pt-v3m1-0-base, a concatenation error of "/home/hqu/zj/ptv3/configs/modelnet40/cls/pt-v3m1-0-base. py" appears. However, when entering other commands such as scannet, this issue does not occur

**Comment by Gofinge** [comment]
Hi, this means both "cls-pt-v3m1-0-base. py" and "cls/pt-v3m1-0-base. py" does not exist in modelnet40 folder. Could you check if the config exists in the modelnet40 folder?
