### ISSUE TITLE
TypeError while evaluating PTv3 on S3DIS

### ISSUE THREAD

**Issue by tanmay4269** [Pointcept/Pointcept#340]
```
export PYTHONPATH=./

python -u tools/test.py \
  --config-file "./configs/s3dis/semseg-pt-v3m1-0-rpe.py" \
  --num-gpus "1" \
  --options save_path="./exp" weight=model_best_2.pth
```
Gives this error:
```
Traceback (most recent call last):                                                                 
  File "/workspace/Pointcept/tools/test.py", line 38, in <module>
    main()
  File "/workspace/Pointcept/tools/test.py", line 27, in main
    launch(
  File "/workspace/Pointcept/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "/workspace/Pointcept/tools/test.py", line 20, in main_worker
    tester.test()
  File "/workspace/Pointcept/pointcept/engines/test.py", line 315, in test
    allAcc = sum(intersection) / (sum(target) + 1e-10)
TypeError: 'numpy.float64' object is not iterable 
```
I'm using Pointcept v1.5

**Comment by Gofinge** [comment]
https://github.com/Pointcept/Pointcept/blob/main/pointcept/engines/test.py#L315

The code you are using doesn't match the one in our repo. Please make sure you are using the latest version.

**Comment by tanmay4269** [comment]
ah, my bad, i was using the wrong config file. 
pretty silly

**Comment by rechim25** [comment]
@tanmay4269 i'm facing the same error on v1.5.1 (which I understand we must use with published huggingface weights). Could you tell me how you solved the issue and what pre-processed dataset you changed?

**Comment by rechim25** [comment]
Nvm solved it, I was too using the wrong pre-processed dataset (accidentally took the data from main rather than v1.5.1). Thanks for pointing it out previously

**Comment by Gofinge** [comment]
We will soon have an update on the code and these weights. A super powerful self-supervised model weight will also be included.

**Comment by JiajieLi7012** [comment]
> We will soon have an update on the code and these weights. A super powerful self-supervised model weight will also be included.

Hi, can you confirm if the preprocessed S3DIS dataset from [here](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/wuxy_connect_hku_hk/ERtd0QAyLGNMs6vsM4XnebcBseQ8YTL0UTrMmp11PmQF3g?e=MsER95) is suitable for the v1.5.1? I tried to use this preprocessed dataset and the v1.5.1 [codebase](https://github.com/Pointcept/Pointcept/releases/tag/v1.5.1) with [pre-trained weights](https://huggingface.co/Pointcept/PointTransformerV3/tree/main) but still got the error mentioned in the issue.

**Comment by smileyenot983** [comment]
> [@tanmay4269](https://github.com/tanmay4269) i'm facing the same error on v1.5.1 (which I understand we must use with published huggingface weights). Could you tell me how you solved the issue and what pre-processed dataset you changed?

Hi. Were you able to run finally? I am having same issues at the moment
