### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

### ISSUE THREAD

**Issue by hymhymhym123** [Pointcept/Pointcept#361]
作者您好，我尝试使用单张4090 24GB在s3dis上进行训练，使用的是semseg-pt-v3m1-1-rpe.py，因为显存问题无法正常训练，所以我设置batch_size = 1以及GridSample中验证和测试的grid_size设置为0.04。

当我训练到

[2024-11-19 17:03:06,782 INFO misc.py line 118 6912] Train: [5/100][223/6120] Data 0.005 (0.005) Batch 0.190 (0.389) Remain 63:29:24 loss: 1.5560 Lr: 0.00549

的时候报错如下：

Traceback (most recent call last):
File "exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/tools/train.py", line 38, in <module>
main()
File "exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/tools/train.py", line 27, in main
launch(
File "/root/autodl-tmp/Pointcept/exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/pointcept/engines/launch.py", line 89, in launch
main_func(*cfg)
File "exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/tools/train.py", line 20, in main_worker
trainer.train()
File "/root/autodl-tmp/Pointcept/exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/pointcept/engines/train.py", line 168, in train
self.run_step()
File "/root/autodl-tmp/Pointcept/exp/s3dis/semseg-pt-v3m1-1-rpe-result/code/pointcept/engines/train.py", line 186, in run_step
self.scaler.scale(loss).backward()
File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
torch.autograd.backward(
File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/autograd/init.py", line 251, in backward
Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

我的具体配置是：

[2024-11-19 14:17:51,625 INFO train.py line 128 6912] => Loading config ...
[2024-11-19 14:17:51,625 INFO train.py line 130 6912] Save path: exp/s3dis/semseg-pt-v3m1-1-rpe-result
[2024-11-19 14:17:52,391 INFO train.py line 131 6912] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 50798151
save_path = 'exp/s3dis/semseg-pt-v3m1-1-rpe-result'
num_worker = 24
batch_size = 1
batch_size_val = None
batch_size_test = None
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = True
empty_cache_per_epoch = False
find_unused_parameters = False
mix_prob = 0.8
param_dicts = [dict(keyword='block', lr=0.0006)]
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
train = dict(type='DefaultTrainer')
test = dict(type='SemSegTester', verbose=True)
model = dict(
    type='DefaultSegmentorV2',
    num_classes=13,
    backbone_out_channels=64,
    backbone=dict(
        type='PT-v3m1',
        in_channels=3,
        order=['z', 'z-trans', 'hilbert', 'hilbert-trans'],
        stride=(2, 2, 2, 2),
        enc_depths=(2, 2, 2, 6, 2),
        enc_channels=(32, 64, 128, 256, 512),
        enc_num_head=(2, 4, 8, 16, 32),
        enc_patch_size=(128, 128, 128, 128, 128),
        dec_depths=(2, 2, 2, 2),
        dec_channels=(64, 64, 128, 256),
        dec_num_head=(4, 4, 8, 16),
        dec_patch_size=(128, 128, 128, 128),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=True,
        enable_flash=False,
        upcast_attention=True,
        upcast_softmax=True,
        cls_mode=False,
        pdnorm_bn=False,
        pdnorm_ln=False,
        pdnorm_decouple=True,
        pdnorm_adaptive=False,
        pdnorm_affine=True,
        pdnorm_conditions=('ScanNet', 'S3DIS', 'Structured3D')),
    criteria=[
        dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1),
        dict(
            type='LovaszLoss',
            mode='multiclass',
            loss_weight=1.0,
            ignore_index=-1)
    ])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(
    type='OneCycleLR',
    max_lr=[0.006, 0.0006],
    pct_start=0.05,
    anneal_strategy='cos',
    div_factor=10.0,
    final_div_factor=1000.0)
dataset_type = 'S3DISDataset'
data_root = '/root/autodl-tmp/s3dis_preprocessing'
data = dict(
    num_classes=13,
    ignore_index=-1,
    names=[
        'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
        'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter'
    ],
    train=dict(
        type='S3DISDataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='/root/autodl-tmp/s3dis_preprocessing',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='RandomDropout',
                dropout_ratio=0.2,
                dropout_application_ratio=0.2),
            dict(
                type='RandomRotate',
                angle=[-1, 1],
                axis='z',
                center=[0, 0, 0],
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='x',
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='y',
                p=0.5),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.02,
                hash_type='fnv',
                mode='train',
                return_grid_coord=True),
            dict(type='SphereCrop', sample_rate=0.6, mode='random'),
            dict(type='SphereCrop', point_max=204800, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'segment'),
                feat_keys='color')
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='/root/autodl-tmp/s3dis_preprocessing',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord',
                               segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                return_grid_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'segment'),
                offset_keys_dict=dict(
                    offset='coord', origin_offset='origin_coord'),
                feat_keys='color')
        ],
        test_mode=False),
    test=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='/root/autodl-tmp/s3dis_preprocessing',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_grid_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'grid_coord', 'index'),
                    feat_keys='color')
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 24
batch_size_per_gpu = 1
batch_size_val_per_gpu = 1
batch_size_test_per_gpu = 1

希望作者能帮忙解答，感谢

**Comment by hymhymhym123** [comment]
喔对了，我还将empty_cache 设置为True，不知道为什么会在第五轮突然出现这个问题

**Comment by Gofinge** [comment]
不建议打开rpe（关闭FlashAttention）时候单卡训练，我们马上会有一个无监督预训练的PTv3，这个PTv3完全不需要rpe或者bn layer，可以在S3DIS上达到非常高的结果，等待我们一个月后的更新吧。
