### ISSUE TITLE
Matterport3D Ground Truth  samples have no labels

### ISSUE THREAD

**Issue by SpeedyGonzales949** [Pointcept/Pointcept#368]
Hi! I tried training PTv3 with the available  Matterport3d preprocessed data from hugginface. However, it crashes during first inference. 

```
[2024-11-24 22:47:41,810 INFO evaluator.py line 159 424911] Test: [152/234] Loss 0.5161 
[2024-11-24 22:47:41,964 ERROR events.py line 611 424911] Traceback (most recent call last):
  File "Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/engines/train.py", line 173, in train
    self.after_epoch()
  File "/Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/engines/train.py", line 215, in after_epoch
    h.after_epoch()
  File "Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/engines/hooks/evaluator.py", line 109, in after_epoch
    self.eval()
  File "Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/engines/hooks/evaluator.py", line 119, in eval
    output_dict = self.trainer.model(input_dict)
  File "/.conda/envs/pointcept-torch2.1.0-cu118/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".conda/envs/pointcept-torch2.1.0-cu118/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/models/default.py", line 69, in forward
    loss = self.criteria(seg_logits, input_dict["segment"])
  File "Pointcept/exp/matterport3d/semseg-pt-v3m1-0-base/code/pointcept/models/losses/builder.py", line 26, in __call__
    loss += c(pred, target)
RuntimeError: output with shape [] doesn't match the broadcast shape [0, 21]

```

After careful examination, I realised this was always happening at step 152. I loaded the 152th validation sample ("X7HyMhZNoso_10") and noticed it has no "real label". All labels are  -1, ignore_indices.

```python
>>> x = np.load("X7HyMhZNoso_10/segment.npy")
>>> x.shape
(35980,)
>>> x
array([-1, -1, -1, ..., -1, -1, -1], dtype=int16)
>>> sum(x==-1)
35980
```

Same result for test sample UwV83HsGsw3_14.

**Comment by SpeedyGonzales949** [comment]
Hi! I removed the specified sample from the validation data and the training works. Its the only sample that has only -1. But I think some kind of strategy needs to be implemented for this unique sample.  Either remove it completely from the dataset or change a bit the preprocessing script.

**Comment by Gofinge** [comment]
Oh, yes. The matterport dataset quality is not so good. I also failed to use it in my latest self-supervised pre-training due to some unknowed reason. I will push the preprocessing code recently and you can take a look if interest.

**Comment by SpeedyGonzales949** [comment]
Thanks for the help. @Gofinge 

I will take a look at Matterport preprocessing code when you upload it.

Good to know that the quality of the dataset is not so good.
