### ISSUE TITLE
'DefaultSegmentor is not in the models registry'

### ISSUE THREAD

**Issue by BITEHS** [Pointcept/Pointcept#372]
Experiment name: semseg-pt-v2m2-0-base
Python interpreter dir: python
Dataset: s3dis
Config: semseg-pt-v2m2-0-base
 =========> CREATE EXP DIR <=========
Experiment dir: /media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base
Loading config in: configs/s3dis/semseg-pt-v2m2-0-base.py
Running code in: exp/s3dis/semseg-pt-v2m2-0-base/code
 =========> RUN TASK <=========
[2024-12-04 20:30:43,955 INFO defaults.py line 167 2199428] => Loading config ...
[2024-12-04 20:30:43,955 INFO defaults.py line 169 2199428] Save path: exp/s3dis/semseg-pt-v2m2-0-base
[2024-12-04 20:30:44,537 INFO defaults.py line 170 2199428] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 45629828
save_path = 'exp/s3dis/semseg-pt-v2m2-0-base'
num_worker = 32
batch_size = 12
batch_size_val = None
batch_size_test = 1
epoch = 3000
eval_epoch = 100
save_freq = None
eval_metric = 'mIoU'
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
max_batch_points = 100000000.0
mix_prob = 0.8
param_dicts = None
model = dict(
    type='DefaultSegmentor',
    backbone=dict(
        type='PT-v2m2',
        in_channels=6,
        num_classes=10,
        patch_embed_depth=2,
        patch_embed_channels=48,
        patch_embed_groups=6,
        patch_embed_neighbours=16,
        enc_depths=(2, 6, 2),
        enc_channels=(96, 192, 384),
        enc_groups=(12, 24, 48),
        enc_neighbours=(16, 16, 16),
        dec_depths=(1, 1, 1),
        dec_channels=(48, 96, 192),
        dec_groups=(6, 12, 24),
        dec_neighbours=(16, 16, 16),
        grid_sizes=(0.1, 0.2, 0.4),
        attn_qkv_bias=True,
        pe_multiplier=False,
        pe_bias=True,
        attn_drop_rate=0.0,
        drop_path_rate=0.3,
        enable_checkpoint=False,
        unpool_backend='interp'),
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(type='MultiStepLR', milestones=[0.6, 0.8], gamma=0.1)
dataset_type = 'S3DISDataset'
data_root = 'data/s3dis'
data = dict(
    num_classes=10,
    ignore_index=-1,
    names=[
        'car', 'ground', 'groundline', 'highline', 'house', 'lowline',
        'obstacle', 'road', 'tower', 'tree'
    ],
    train=dict(
        type='S3DISDataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_grid_coord=True),
            dict(type='SphereCrop', point_max=80000, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord',
                               segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_grid_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'segment'),
                offset_keys_dict=dict(offset='coord'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False),
    test=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_grid_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'grid_coord', 'index'),
                    feat_keys=('coord', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 32
batch_size_per_gpu = 12
batch_size_val_per_gpu = 1

[2024-12-04 20:30:44,537 INFO defaults.py line 172 2199428] => Building model ...
Traceback (most recent call last):
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 34, in <module>
    main()
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 23, in main
    launch(
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/engines/launch.py", line 87, in launch
    main_func(*cfg)
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 15, in main_worker
    trainer = Trainer(cfg)
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/engines/defaults.py", line 173, in __init__
    self.model = self.build_model()
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/engines/defaults.py", line 422, in build_model
    model = build_model(self.cfg.model)
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/models/builder.py", line 16, in build_model
    return MODELS.build(cfg)
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/media/wsc/16B68EBDB68E9CBD/Han_PTv2/ptv2/PointTransformerV2-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pcr/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'DefaultSegmentor is not in the models registry'
请问这是什么原因

**Comment by atimogus** [comment]
did you solve this?

**Comment by fsigriehgiruewhwruh** [comment]
i have encountered the same problem
