### ISSUE TITLE
About adapting this codebase to shapenet part segmentation.

### ISSUE THREAD

**Issue by Ma-Weijian** [Pointcept/Pointcept#46]
Hi there,

Wonderful codebase to Point Transformer series and other fantastice work!

Recently I've tried to use this codebase to perform shapenet part segementation. I followed the config code you provided in this issue https://github.com/Gofinge/PointTransformerV2/issues/28 and tried to adapt the code to this codebase.

The config file is shown as follows.
```
_base_ = [
    # '../_base_/datasets/shapenet_part.py',
    # '../_base_/schedulers/multi-step_sgd.py',
    # '../_base_/tests/part_segmentation.py',
    '../_base_/default_runtime.py'
]

batch_size = 32
batch_size_val = 16
metric = "cat_mIoU"
# enable_amp = True

epochs = 100
start_epoch = 0
optimizer = dict(type='SGD', lr=0.5, momentum=0.9, weight_decay=0.0001, nesterov=True)
scheduler = dict(type="MultiStepLR", milestones=[0.6, 0.8], gamma=0.1)

model = dict(
    type="DefaultSegmentor",
    backbone=dict(
        type='PointTransformer-PartSeg50',
        num_shape_classes=16,
        in_channels=6,
        num_classes=50,
    ),
    criteria = [
    dict(type="CrossEntropyLoss",
         loss_weight=1.0,
         ignore_index=-1)
    ]
)

# dataset settings
dataset_type = "ShapeNetPartDataset"
data_root = "data/shapenetcore_partanno_segmentation_benchmark_v0_normal"
cache_data = False
names = ["Airplane_{}".format(i) for i in range(4)] + \
        ["Bag_{}".format(i) for i in range(2)] + \
        ["Cap_{}".format(i) for i in range(2)] + \
        ["Car_{}".format(i) for i in range(4)] + \
        ["Chair_{}".format(i) for i in range(4)] + \
        ["Earphone_{}".format(i) for i in range(3)] + \
        ["Guitar_{}".format(i) for i in range(3)] + \
        ["Knife_{}".format(i) for i in range(2)] + \
        ["Lamp_{}".format(i) for i in range(4)] + \
        ["Laptop_{}".format(i) for i in range(2)] + \
        ["Motorbike_{}".format(i) for i in range(6)] + \
        ["Mug_{}".format(i) for i in range(2)] + \
        ["Pistol_{}".format(i) for i in range(3)] + \
        ["Rocket_{}".format(i) for i in range(3)] + \
        ["Skateboard_{}".format(i) for i in range(3)] + \
        ["Table_{}".format(i) for i in range(3)]

data = dict(
    num_classes=50,
    ignore_index=-1,  # dummy ignore
    names=names,
    train=dict(
        type=dataset_type,
        split=["train", "val"],
        data_root=data_root,
        transform=[
            dict(type="NormalizeCoord"),
            # dict(type="CenterShift", apply_z=True),
            # dict(type="RandomRotate", angle=[-1, 1], axis='z', center=[0, 0, 0], p=0.5),
            # dict(type="RandomRotate", angle=[-1 / 24, 1 / 24], axis='x', p=0.5),
            # dict(type="RandomRotate", angle=[-1 / 24, 1 / 24], axis='y', p=0.5),
            # dict(type="RandomScale", scale=[0.9, 1.1]),
            # dict(type="RandomFlip", p=0.5),
            # dict(type="RandomJitter", sigma=0.005, clip=0.02),
            # dict(type="RandomShift", shift=[0.2, 0.2, 0.2]),
            # dict(type="ElasticDistortion", distortion_params=[[0.2, 0.4], [0.8, 1.6]]),

            # dict(type="Voxelize", voxel_size=0.01, hash_type='fnv', mode='train'),
            # dict(type="SphereCrop", point_max=2500, mode='random'),
            dict(type="ShufflePoint"),
            dict(type="ToTensor"),
            dict(type="Collect", keys=("coord", "cls_token", "segment"), feat_keys=("coord", "norm"))
        ],
        loop=2,
        test_mode=False,
    ),

    val=dict(
        type=dataset_type,
        split="test",
        data_root=data_root,
        transform=[
            dict(type="NormalizeCoord"),
            dict(type="ToTensor"),
            dict(type="Collect", keys=("coord", "cls_token", "segment"), feat_keys=("coord", "norm"))
        ],
        loop=1,
        test_mode=False,
    ),

    test=dict(
        type=dataset_type,
        split="test",
        data_root=data_root,
        transform=[
            dict(type="NormalizeCoord"),
            # dict(type="CenterShift", apply_z=True),
        ],
        loop=1,
        test_mode=True,
        test_cfg=dict(
            post_transform=[
                dict(type="ToTensor"),
                dict(type="Collect", keys=("coord", "cls_token"), feat_keys=("coord", "norm"))
            ],
            aug_transform=[
                [dict(type="RandomShift2", shift=((0, 0), (0, 0), (0, 0)))]
            ]
        )
    ),
)

# hooks
hooks = [
    dict(type="CheckpointLoader"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    dict(type="PartSegmentationEvaluator"),
    dict(type="CheckpointSaver", save_freq=None)
]

# tester
test = dict(
    type="PartSegTester"
)
```

As the evaluation code of part segmentation is not provided, I implemented `PartSegmentationEvaluator` as follows.
```
@HOOKS.register_module()
class PartSegmentationEvaluator(HookBase):
    """PartSegmentationTest
    """

    def after_epoch(self):
        if self.trainer.cfg.evaluate:
            self.eval()

    def eval(self):
        self.trainer.logger.info('>>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>')
        self.trainer.model.eval()
        for i, input_dict in enumerate(self.trainer.val_loader):
            for key in input_dict.keys():
                if isinstance(input_dict[key], torch.Tensor):
                    input_dict[key] = input_dict[key].cuda(non_blocking=True)
            with torch.no_grad():
                output_dict = self.trainer.model(input_dict)
            output = output_dict["seg_logits"]
            loss = output_dict["loss"]
            pred = output.max(1)[1]
            segment = input_dict["segment"]
            if "origin_coord" in input_dict.keys():
                idx, _ = pointops.knn_query(1, input_dict["coord"].float(), input_dict["offset"].int(),
                                            input_dict["origin_coord"].float(), input_dict["origin_offset"].int())
                pred = pred[idx.flatten().long()]
                segment = input_dict["origin_segment"]
            intersection, union, target = \
                intersection_and_union_gpu(
                    pred, segment, self.trainer.cfg.data.num_classes, self.trainer.cfg.data.ignore_index)
            if comm.get_world_size() > 1:
                dist.all_reduce(intersection), dist.all_reduce(union), dist.all_reduce(target)
            intersection, union, target = intersection.cpu().numpy(), union.cpu().numpy(), target.cpu().numpy()
            # Here there is no need to sync since sync happened in dist.all_reduce
            self.trainer.storage.put_scalar("val_intersection", intersection)
            self.trainer.storage.put_scalar("val_union", union)
            self.trainer.storage.put_scalar("val_target", target)
            self.trainer.storage.put_scalar("val_loss", loss.item())
            info = "Test: [{iter}/{max_iter}] ".format(iter=i + 1, max_iter=len(self.trainer.val_loader))
            if "origin_coord" in input_dict.keys():
                info = "Precise " + info
            self.trainer.logger.info(info + 'Loss {loss:.4f} '.format(iter=i + 1,
                                                                      max_iter=len(self.trainer.val_loader),
                                                                      loss=loss.item()))
        loss_avg = self.trainer.storage.history("val_loss").avg
        intersection = self.trainer.storage.history("val_intersection").total
        union = self.trainer.storage.history("val_union").total
        target = self.trainer.storage.history("val_target").total
        iou_class = intersection / (union + 1e-10)
        acc_class = intersection / (target + 1e-10)
        m_iou = np.mean(iou_class)
        m_acc = np.mean(acc_class)
        ins_iou = sum(intersection) / (sum(union) + 1e-10)
        all_acc = sum(intersection) / (sum(target) + 1e-10)
        self.trainer.logger.info('Val result: mIoU/insIoU/mAcc/allAcc {:.4f}/{:.4f}/{:.4f}/{:.4f}.'.format(
            m_iou, ins_iou, m_acc, all_acc))
        for i in range(self.trainer.cfg.data.num_classes):
            self.trainer.logger.info('Class_{idx}-{name} Result: intersection/union/target/iou/accuracy {intersection}/{union}/{target}/{iou:.4f}/{accuracy:.4f}'.format(
                idx=i, name=self.trainer.cfg.data.names[i], intersection = intersection[i], union=union[i], target=target[i], iou=iou_class[i], accuracy=acc_class[i]))
        current_epoch = self.trainer.epoch + 1
        if self.trainer.writer is not None:
            self.trainer.writer.add_scalar('val/loss', loss_avg, current_epoch)
            self.trainer.writer.add_scalar('val/mIoU', m_iou, current_epoch)
            self.trainer.writer.add_scalar('val/insIoU', ins_iou, current_epoch)
            self.trainer.writer.add_scalar('val/mAcc', m_acc, current_epoch)
            self.trainer.writer.add_scalar('val/allAcc', all_acc, current_epoch)
        self.trainer.logger.info('<<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<')
        self.trainer.comm_info["current_metric_value"] = m_iou  # save for saver
        self.trainer.comm_info["current_metric_name"] = "mIoU"  # save for saver

    def after_train(self):
        self.trainer.logger.info('Best {}: {:.4f}'.format(
            "mIoU", self.trainer.best_metric_value))
```

The part segmentation code then runs well, but it seems that the result of shapenet part segmentation differs greatly from the reported result in the ptv1 paper. The Category mIoU is quite lower than reported while the Instance mIoU has reached 87.4%, which is beyond the reported result.

I wonder if there is anything wrong with my implementation, or if there is some hyperparameters missing.

Anything helps, a million thanks!

**Comment by Gofinge** [comment]
Hi, the example config might not be the best setting, tuning augmentation (whether distort, scale level, crop point number), learning rate, and weight decay are needed. Also maybe adding a TTA test process will make the performance better. It has been a long time since I last time running the ShapeNet part segmentation, and I will try to tune a better setting when I have some time. Thanks for being interested in our code.

**Comment by Ma-Weijian** [comment]
Looking forward to the tuned setting~

**Comment by Ma-Weijian** [comment]
Thanks for your timely reply!
Looking forward to the tuned setting and the adaptation of ptv2 to part segmentation~

**Comment by KLM1109** [comment]
I try training this, but i have problems with shapenet_part.py : 'ShapeNetPartDataset' object has no attribute 'data_idx'
more detail:

Traceback (most recent call last):
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/datasets/shapenet_part.py", line 89, in __init__
    len(self.data_idx), self.loop, split
AttributeError: 'ShapeNetPartDataset' object has no attribute 'data_idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/train.py", line 137, in __init__
    self.train_loader = self.build_train_loader()
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/train.py", line 223, in build_train_loader
    train_data = build_dataset(self.cfg.data.train)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/datasets/builder.py", line 16, in build_dataset
    return DATASETS.build(cfg)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
AttributeError: ShapeNetPartDataset: 'ShapeNetPartDataset' object has no attribute 'data_idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "exp/shapenet_part/partseg-pt-v1-0-base/code/tools/train.py", line 19, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lkm/Pointcept/exp/shapenet_part/partseg-pt-v1-0-base/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
AttributeError: Trainer: ShapeNetPartDataset: 'ShapeNetPartDataset' object has no attribute 'data_idx'
