### ISSUE TITLE
Config name protocol issue.

### ISSUE THREAD

**Issue by blueeaglex** [Pointcept/Pointcept#53]
[](https://github.com/Pointcept/Pointcept/blob/d60a9779cd68be94b33e163bd3aa24170ea3a9da/pointcept/engines/defaults.py#L98C1-L117C15)

Even though the code above says:  config name protocol: dataset_name/model_name-exp_name, I got these error:
`Experiment name: semseg-ptv2m2-0-base
Python interpreter dir: python
Dataset: scannet
Config: semseg-ptv2m2-0-base
GPU Num: 1
 =========> CREATE EXP DIR <=========
Experiment dir: /mnt/c/workspace/Pointcept/exp/scannet/semseg-ptv2m2-0-base
Loading config in: configs/scannet/semseg-ptv2m2-0-base.py
Running code in: exp/scannet/semseg-ptv2m2-0-base/code
 =========> RUN TASK <=========
Traceback (most recent call last):
  File "exp/scannet/semseg-ptv2m2-0-base/code/tools/train.py", line 34, in <module>
    main()
  File "exp/scannet/semseg-ptv2m2-0-base/code/tools/train.py", line 21, in main
    cfg = default_config_parser(args.config_file, args.options)
  File "/mnt/c/workspace/Pointcept/exp/scannet/semseg-ptv2m2-0-base/code/pointcept/engines/defaults.py", line 108, in default_config_parser
    cfg = Config.fromfile(file_path)
  File "/mnt/c/workspace/Pointcept/exp/scannet/semseg-ptv2m2-0-base/code/pointcept/utils/config.py", line 330, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/mnt/c/workspace/Pointcept/exp/scannet/semseg-ptv2m2-0-base/code/pointcept/utils/config.py", line 181, in _file2dict
    check_file_exist(filename)
  File "/mnt/c/workspace/Pointcept/exp/scannet/semseg-ptv2m2-0-base/code/pointcept/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/mnt/c/workspace/Pointcept/configs/scannet/semseg/ptv2m2-0-base.py" does not exist`

And I tried to search in my filesystem, I got file with path of '/xxx/configs/scannet/semseg-ptv2m2-0-base.py' but not '/xxx/semseg/ptv2m2-0-base.py'.  I think there is something about the path protocol that was missing', isn't that?

**Comment by Gofinge** [comment]
Hi, my apology for this inconvenience, I rename "ptv2m2" to "pt-v2m2" to unify the model name protocol of Pointcept.

**Comment by blueeaglex** [comment]
> Hi, my apology for this inconvenience, I rename "ptv2m2" to "pt-v2m2" to unify the model name protocol of Pointcept.
Well， I've committed this pull request for the issue. Check it if you need.
