### ISSUE TITLE
Failed to load pretrained model

### ISSUE THREAD

**Issue by blueeaglex** [Pointcept/Pointcept#56]
I just tried to launch a test as the Readme said using [pretrained model](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/wuxy_connect_hku_hk/Ed3wwHgE5RdHqBRuejIvxdkB8H6VFVSyX_t2hTYYjZeyjQ?e=JXKade)  which offered by @Gofinge in https://github.com/Pointcept/Pointcept/issues/42. 
An error occured:
```
[2023-07-13 16:16:37,336 INFO test.py line 37 17360] => Building model ...
[2023-07-13 16:16:38,541 INFO test.py line 40 17360] Num params: 3908641
MODEL_PATH:/mnt/c/workspace/Pointcept/pretrained_model/semseg-s3dis-ptv2m2.pth
Traceback (most recent call last):
  File "tools/test.py", line 95, in <module>
    main()
  File "tools/test.py", line 84, in main
    launch(
  File "/mnt/c/workspace/Pointcept/pointcept/engines/launch.py", line 87, in launch
    main_func(*cfg)
  File "tools/test.py", line 57, in main_worker
    model.load_state_dict(new_state_dict, strict=True)
  File "/home/owl/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DefaultSegmentor:
        Missing key(s) in state_dict: "backbone.patch_embed.proj.0.weight", "backbone.patch_embed.proj.1.norm.weight", 
```

Any ideas while be much appreciate.

**Comment by Gofinge** [comment]
It might be because the weight is from an old version of the codebase. I suggest training S3DIS again or using another shared weight trained on SemanticKITTI (I trained it recently)

**Comment by blueeaglex** [comment]
> It might be because the weight is from an old version of the codebase. I suggest training S3DIS again or using another shared weight trained on SemanticKITTI (I trained it recently)

OK，Thanks， I’ll try it
