### ISSUE TITLE
RuntimeError: unable to open shared memory object <> in read-write mode: Too many open files (24)

### ISSUE THREAD

**Issue by JingShuju** [Pointcept/Pointcept#61]
Thanks for author‘s perfect work!!!
When i  use  sh scripts/train.sh -g 1 -d s3dis -c semseg-pt-v1-0-base -n semseg-pt-v1-0-base for train,  train and val parts are successful,but test part always failed.

 >>>>>>>>>>>>>>>> Start Precise Evaluation >>>>>>>>>>>>>>>>
[2023-07-25 17:38:39,433 INFO misc.py line 211 602893] => Building test dataset & dataloader ...
[2023-07-25 17:38:39,434 INFO j1dataset.py line 49 602893] Totally 6 x 1 samples in Area_5 set.
[2023-07-25 17:38:39,434 INFO misc.py line 230 602893] => Testing on model_best ...
[2023-07-25 17:38:39,703 INFO test.py line 34 602893] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
then:

unable to mmap 118824 bytes from file </torch_587100_2809015737_63446>: Cannot allocate memory (12)
unable to open shared memory object </torch_587103_358076008_500> in read-write mode: Too many open files (24)`

were appeared. 
could you provide some advice with me? thanks!!! 
These happened on both  server and my pc.

**Comment by Gofinge** [comment]
Hi, could you provide the config exported by Pointcept (in your exp folder) and more detailed error output for reference?

**Comment by JingShuju** [comment]
(pointcept) [jingshuju@skku01 Pointcept-main]$ sh scripts/train.sh -g 2 -d j1dataset -c semseg-pt-v1-0-base -n semseg-pt-v1-0-base
Experiment name: semseg-pt-v1-0-base
Python interpreter dir: python
Dataset: j1dataset
Config: semseg-pt-v1-0-base
GPU Num: 2
 =========> CREATE EXP DIR <=========
Experiment dir: /hdd_4tb/jingshuju/servertrain/Pointcept-main/exp/j1dataset/semseg-pt-v1-0-base
Loading config in: configs/j1dataset/semseg-pt-v1-0-base.py
Running code in: exp/j1dataset/semseg-pt-v1-0-base/code
 =========> RUN TASK <=========
[2023-07-25 17:59:04,694 INFO train.py line 115 608201] => Loading config ...
[2023-07-25 17:59:04,694 INFO train.py line 117 608201] Save path: exp/j1dataset/semseg-pt-v1-0-base
[2023-07-25 17:59:05,264 INFO train.py line 118 608201] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 57274114
save_path = 'exp/j1dataset/semseg-pt-v1-0-base'
num_worker = 16
batch_size = 2
batch_size_val = None
batch_size_test = None
epoch = 2
eval_epoch = 2
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
mix_prob = 0.8
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
test = dict(type='SemSegTester')
model = dict(
    type='DefaultSegmentor',
    backbone=dict(type='PointTransformer-Seg50', in_channels=6, num_classes=5),
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(type='MultiStepLR', milestones=[0.6, 0.8], gamma=0.1)
dataset_type = 'j1dataset'
data_root = 'data/j1dataset'
data = dict(
    num_classes=5,
    ignore_index=-1,
    names=['canglebar', 'cabletray', 'pipe', 'rod', 'tube'],
    train=dict(
        type='j1dataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='data/j1dataset',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='SphereCrop', point_max=100000, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False,
        loop=1),
    val=dict(
        type='j1dataset',
        split='Area_5',
        data_root='data/j1dataset',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord',
                               segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                offset_keys_dict=dict(offset='coord'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False),
    test=dict(
        type='j1dataset',
        split='Area_5',
        data_root='data/j1dataset',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_discrete_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'discrete_coord', 'index'),
                    feat_keys=('coord', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 8
batch_size_per_gpu = 1
batch_size_val_per_gpu = 1
batch_size_test_per_gpu = 1

[2023-07-25 17:59:05,264 INFO train.py line 119 608201] => Building model ...
[2023-07-25 17:59:05,328 INFO train.py line 193 608201] Num params: 7767465
[2023-07-25 17:59:05,386 INFO train.py line 121 608201] => Building writer ...
[2023-07-25 17:59:05,392 INFO train.py line 201 608201] Tensorboard writer logging dir: exp/j1dataset/semseg-pt-v1-0-base
[2023-07-25 17:59:05,392 INFO train.py line 123 608201] => Building train dataset & dataloader ...
[2023-07-25 17:59:05,393 INFO j1dataset.py line 49 608201] Totally 26 x 1 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6') set.
[2023-07-25 17:59:05,393 INFO train.py line 125 608201] => Building val dataset & dataloader ...
[2023-07-25 17:59:05,394 INFO j1dataset.py line 49 608201] Totally 6 x 1 samples in Area_5 set.
[2023-07-25 17:59:05,394 INFO train.py line 127 608201] => Building optimize, scheduler, scaler(amp) ...
[2023-07-25 17:59:05,395 INFO train.py line 131 608201] => Building hooks ...
[2023-07-25 17:59:05,396 INFO misc.py line 180 608201] => Loading checkpoint & weight ...
[2023-07-25 17:59:05,396 INFO misc.py line 199 608201] No weight found at: None
[2023-07-25 17:59:05,396 INFO train.py line 138 608201] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
[2023-07-25 17:59:15,982 INFO misc.py line 115 608201] Train: [1/2][1/13] Data 9.428 (9.428) Batch 10.423 (10.423) Remain 00:04:20 loss: 1.5929 Lr: 0.00600
[2023-07-25 17:59:16,296 INFO misc.py line 115 608201] Train: [1/2][2/13] Data 0.002 (0.002) Batch 0.313 (0.313) Remain 00:00:07 loss: 1.5984 Lr: 0.00600
[2023-07-25 17:59:16,630 INFO misc.py line 115 608201] Train: [1/2][3/13] Data 0.002 (0.002) Batch 0.333 (0.333) Remain 00:00:07 loss: 1.5674 Lr: 0.00600
[2023-07-25 17:59:16,921 INFO misc.py line 115 608201] Train: [1/2][4/13] Data 0.003 (0.003) Batch 0.291 (0.291) Remain 00:00:06 loss: 1.5894 Lr: 0.00600
[2023-07-25 17:59:17,210 INFO misc.py line 115 608201] Train: [1/2][5/13] Data 0.003 (0.003) Batch 0.289 (0.290) Remain 00:00:06 loss: 1.5182 Lr: 0.00600
[2023-07-25 17:59:17,516 INFO misc.py line 115 608201] Train: [1/2][6/13] Data 0.003 (0.003) Batch 0.306 (0.296) Remain 00:00:05 loss: 1.4031 Lr: 0.00600
[2023-07-25 17:59:17,933 INFO misc.py line 115 608201] Train: [1/2][7/13] Data 0.003 (0.003) Batch 0.416 (0.326) Remain 00:00:06 loss: 1.3773 Lr: 0.00600
[2023-07-25 17:59:18,217 INFO misc.py line 115 608201] Train: [1/2][8/13] Data 0.004 (0.003) Batch 0.285 (0.317) Remain 00:00:05 loss: 1.3346 Lr: 0.00600
[2023-07-25 17:59:18,524 INFO misc.py line 115 608201] Train: [1/2][9/13] Data 0.003 (0.003) Batch 0.306 (0.316) Remain 00:00:05 loss: 1.1975 Lr: 0.00600
[2023-07-25 17:59:18,810 INFO misc.py line 115 608201] Train: [1/2][10/13] Data 0.003 (0.003) Batch 0.286 (0.311) Remain 00:00:04 loss: 1.1782 Lr: 0.00600
[2023-07-25 17:59:19,239 INFO misc.py line 115 608201] Train: [1/2][11/13] Data 0.004 (0.003) Batch 0.430 (0.326) Remain 00:00:04 loss: 1.2380 Lr: 0.00600
[2023-07-25 17:59:19,594 INFO misc.py line 115 608201] Train: [1/2][12/13] Data 0.003 (0.003) Batch 0.355 (0.329) Remain 00:00:04 loss: 1.3771 Lr: 0.00600
[2023-07-25 17:59:19,863 INFO misc.py line 115 608201] Train: [1/2][13/13] Data 0.002 (0.003) Batch 0.269 (0.323) Remain 00:00:04 loss: 0.9530 Lr: 0.00600
[2023-07-25 17:59:19,864 INFO misc.py line 129 608201] Train result: loss: 1.3789
[2023-07-25 17:59:19,864 INFO evaluator.py line 84 608201] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2023-07-25 17:59:28,745 INFO evaluator.py line 115 608201] Test: [1/3] Loss 33.5832
[2023-07-25 17:59:28,829 INFO evaluator.py line 115 608201] Test: [2/3] Loss 70.9417
[2023-07-25 17:59:28,919 INFO evaluator.py line 115 608201] Test: [3/3] Loss 42.7456
[2023-07-25 17:59:29,488 INFO evaluator.py line 127 608201] Val result: mIoU/mAcc/allAcc 0.1174/0.2000/0.5872.
[2023-07-25 17:59:29,489 INFO evaluator.py line 130 608201] Class_0-canglebar Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:29,489 INFO evaluator.py line 130 608201] Class_1-cabletray Result: iou/accuracy 0.5872/1.0000
[2023-07-25 17:59:29,489 INFO evaluator.py line 130 608201] Class_2-pipe Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:29,489 INFO evaluator.py line 130 608201] Class_3-rod Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:29,489 INFO evaluator.py line 130 608201] Class_4-tube Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:29,489 INFO evaluator.py line 138 608201] <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
[2023-07-25 17:59:29,490 INFO misc.py line 150 608201] Best validation mIoU updated to: 0.1174
[2023-07-25 17:59:29,490 INFO misc.py line 152 608201] Currently Best mIoU: 0.1174
[2023-07-25 17:59:29,490 INFO misc.py line 156 608201] Saving checkpoint to: exp/j1dataset/semseg-pt-v1-0-base/model/model_last.pth
[2023-07-25 17:59:31,563 INFO misc.py line 115 608201] Train: [2/2][1/13] Data 0.771 (0.771) Batch 1.301 (1.301) Remain 00:00:15 loss: 1.3411 Lr: 0.00600
[2023-07-25 17:59:31,868 INFO misc.py line 115 608201] Train: [2/2][2/13] Data 0.005 (0.005) Batch 0.306 (0.306) Remain 00:00:03 loss: 1.5596 Lr: 0.00600
[2023-07-25 17:59:32,843 INFO misc.py line 115 608201] Train: [2/2][3/13] Data 0.640 (0.640) Batch 0.975 (0.975) Remain 00:00:09 loss: 1.1329 Lr: 0.00600
[2023-07-25 17:59:35,050 INFO misc.py line 115 608201] Train: [2/2][4/13] Data 0.003 (0.003) Batch 2.207 (2.207) Remain 00:00:19 loss: 0.8490 Lr: 0.00600
[2023-07-25 17:59:35,337 INFO misc.py line 115 608201] Train: [2/2][5/13] Data 0.003 (0.003) Batch 0.287 (1.247) Remain 00:00:09 loss: 1.2470 Lr: 0.00600
[2023-07-25 17:59:35,642 INFO misc.py line 115 608201] Train: [2/2][6/13] Data 0.003 (0.003) Batch 0.305 (0.933) Remain 00:00:06 loss: 0.8455 Lr: 0.00600
[2023-07-25 17:59:35,932 INFO misc.py line 115 608201] Train: [2/2][7/13] Data 0.003 (0.003) Batch 0.290 (0.772) Remain 00:00:04 loss: 0.9010 Lr: 0.00600
[2023-07-25 17:59:36,280 INFO misc.py line 115 608201] Train: [2/2][8/13] Data 0.003 (0.003) Batch 0.349 (0.688) Remain 00:00:03 loss: 0.9200 Lr: 0.00600
[2023-07-25 17:59:36,556 INFO misc.py line 115 608201] Train: [2/2][9/13] Data 0.003 (0.003) Batch 0.276 (0.619) Remain 00:00:02 loss: 0.7451 Lr: 0.00600
[2023-07-25 17:59:36,876 INFO misc.py line 115 608201] Train: [2/2][10/13] Data 0.002 (0.003) Batch 0.320 (0.576) Remain 00:00:01 loss: 0.7274 Lr: 0.00600
[2023-07-25 17:59:37,138 INFO misc.py line 115 608201] Train: [2/2][11/13] Data 0.002 (0.003) Batch 0.262 (0.537) Remain 00:00:01 loss: 0.6754 Lr: 0.00600
[2023-07-25 17:59:37,464 INFO misc.py line 115 608201] Train: [2/2][12/13] Data 0.002 (0.003) Batch 0.326 (0.514) Remain 00:00:00 loss: 0.6990 Lr: 0.00600
[2023-07-25 17:59:37,751 INFO misc.py line 115 608201] Train: [2/2][13/13] Data 0.003 (0.003) Batch 0.287 (0.491) Remain 00:00:00 loss: 0.6606 Lr: 0.00600
[2023-07-25 17:59:37,752 INFO misc.py line 129 608201] Train result: loss: 0.9464
[2023-07-25 17:59:37,752 INFO evaluator.py line 84 608201] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2023-07-25 17:59:46,716 INFO evaluator.py line 115 608201] Test: [1/3] Loss 955.8360
[2023-07-25 17:59:46,791 INFO evaluator.py line 115 608201] Test: [2/3] Loss 736.4613
[2023-07-25 17:59:46,880 INFO evaluator.py line 115 608201] Test: [3/3] Loss 1096.4163
[2023-07-25 17:59:47,450 INFO evaluator.py line 127 608201] Val result: mIoU/mAcc/allAcc 0.0116/0.2000/0.0582.
[2023-07-25 17:59:47,450 INFO evaluator.py line 130 608201] Class_0-canglebar Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:47,450 INFO evaluator.py line 130 608201] Class_1-cabletray Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:47,450 INFO evaluator.py line 130 608201] Class_2-pipe Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:47,450 INFO evaluator.py line 130 608201] Class_3-rod Result: iou/accuracy 0.0582/1.0000
[2023-07-25 17:59:47,450 INFO evaluator.py line 130 608201] Class_4-tube Result: iou/accuracy 0.0000/0.0000
[2023-07-25 17:59:47,450 INFO evaluator.py line 138 608201] <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
[2023-07-25 17:59:47,451 INFO misc.py line 152 608201] Currently Best mIoU: 0.1174
[2023-07-25 17:59:47,451 INFO misc.py line 156 608201] Saving checkpoint to: exp/j1dataset/semseg-pt-v1-0-base/model/model_last.pth
[2023-07-25 17:59:47,726 INFO evaluator.py line 143 608201] Best mIoU: 0.1174
[2023-07-25 17:59:47,726 INFO misc.py line 208 608201] >>>>>>>>>>>>>>>> Start Precise Evaluation >>>>>>>>>>>>>>>>
[2023-07-25 17:59:47,727 INFO misc.py line 211 608201] => Building test dataset & dataloader ...
[2023-07-25 17:59:47,727 INFO j1dataset.py line 49 608201] Totally 6 x 1 samples in Area_5 set.
[2023-07-25 17:59:47,727 INFO misc.py line 230 608201] => Testing on model_best ...
[2023-07-25 17:59:48,009 INFO test.py line 34 608201] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
RuntimeError: unable to open shared memory object </torch_610348_2370406573_2036> in read-write mode: Too many open files (24)
Traceback (most recent call last):
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/hdd_4tb/jingshuju/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
RuntimeError: unable to open shared memory object </torch_610351_3583583817_2036> in read-write mode: Too many open files (24)

**Comment by Gofinge** [comment]
Hi, the discussion here might be helpful (https://discuss.pytorch.org/t/runtimeerror-unable-to-open-shared-memory-object-depending-on-the-model/116090). It might cause by system share memory limitation.

**Comment by JingShuju** [comment]
> Hi, the discussion here might be helpful (https://discuss.pytorch.org/t/runtimeerror-unable-to-open-shared-memory-object-depending-on-the-model/116090). It might cause by system share memory limitation.

Thank for your reply~   **Too many open files (24)** has been resloved, but **unable to mmap 118824 bytes from file </torch_587100_2809015737_63446>: Cannot allocate memory (12)**  still could be resloved, aithough i try it in different device.

**Comment by YOOOOOL** [comment]
Hello, I also met the same problem, may I ask what method you finally solved it

**Comment by cheylong** [comment]
1. use more share memory
2. detete some  test-on-aug  in config file

**Comment by JingShuju** [comment]
> Hello, I also met the same problem, may I ask what method you finally solved it
if it work, please reply to me:
It was too long time ago, I am not sure, please try to add the code below:
import torch.multiprocessing 
torch.multiprocessing.set_sharing_strategy('file_system')

**Comment by cheylong** [comment]
要么加共享内存和最大文件句柄要么删掉 config 文件里面 test 那里面的增强选项



---- Replied Message ----
| From | Jing ***@***.***> |
| Date | 10/23/2023 19:52 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Pointcept/Pointcept] RuntimeError: unable to open shared memory object <> in read-write mode: Too many open files (24) (Issue #61) |

Hello, I also met the same problem, may I ask what method you finally solved it
if it work, please reply to me:
It was too long time ago, I am not sure, please try to add the code below:
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

**Comment by YOOOOOL** [comment]
> > Hello, I also met the same problem, may I ask what method you finally solved it
> > if it work, please reply to me:
> > It was too long time ago, I am not sure, please try to add the code below:
> > import torch.multiprocessing
> > torch.multiprocessing.set_sharing_strategy('file_system')
Thanks for your reply, I set ulimit-n 640000 and import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

**Comment by lemon44567** [comment]
Hi, I also encountered a similar error, but I was able to use the command `export PYTHONPATH=./ python tools/test.py --config-file configs/scannet/semseg-pt-v2m2-0-base.py --options save_path=exp/scannet/semseg-pt-v2m2-0-base weight=exp/scannet/semseg-pt-v2m2-0-base/model/model_best.pth` to test the metrics and obtain results. I wanted to ask if the metrics obtained from testing are the same as those from "Start Precise Evaluation".

**Comment by RayYoh** [comment]
> Hi, I also encountered a similar error, but I was able to use the command `export PYTHONPATH=./ python tools/test.py --config-file configs/scannet/semseg-pt-v2m2-0-base.py --options save_path=exp/scannet/semseg-pt-v2m2-0-base weight=exp/scannet/semseg-pt-v2m2-0-base/model/model_best.pth` to test the metrics and obtain results. I wanted to ask if the metrics obtained from testing are the same as those from "Start Precise Evaluation".

I have encountered the same problem. I tried testing this command when using one GPU. I think it is same, but it is a little bit complex for each config file.
