### ISSUE TITLE
RuntimeError: Function 'AddmmBackward0' returned nan values in its 2th output. PointTransformerV1

### ISSUE THREAD

**Issue by joao-alemao** [Pointcept/Pointcept#62]
I am trying to run Point Transformer v1 (specifically, PointTransformerSeg26) with a local dataset.

After a few batches (and always before a full epoch of training is reached) a problem arises where the weights of self.linear2 in self.dec5 become `nan`, thus outputting  a tensor full of `nans` down to the output of the network.

 Why this happens I have not figured out but I have been able to isolate it to this line: 
`self.linear2 = nn.Sequential(nn.Linear(in_planes, in_planes), nn.ReLU(inplace=True))` in `TransitionUp`. It happens in the Linear layer. Suddenly after an update that layers  weights become fully nan.

I have tried:
- Using  different optimizers and schedulers as well as GradScaler in different combinatios.
- Lowering the learning rate.
- Clipping the gradients of the model.
- Providing randomly generated data instead of my dataset.
- Different losses (CrossEntropy and Dice).
- Install different conda env with different pytorch version.

However, the problem keeps appearing. Do you have any idea of what might be happening? I have not modified the architecture at all so find this quite strange, specially that it does not seem related to the data as I reach the same state even if using random inputs.

------------------------------------------
Using torch's set_detect_anomaly(True), I get the following stack trace:

Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "main.py", line 88, in <module>
    train(
  File "/home/joal/code/Training/train.py", line 66, in train
    model_output = model(sample)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joal/code/Training/models/point_transformerv1_semantic_segmentation.py", line 359, in forward
    x5 = self.dec5[1:]([p5, self.dec5[0]([p5, x5, o5]), o5])[1]
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joal/code/Training/models/point_transformerv1_semantic_segmentation.py", line 196, in forward
    x_b = torch.cat((x_b, self.linear2(x_b.sum(0, True) / cnt).repeat(cnt, 1)), 1)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
 
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    train(
  File "/home/joal/code/Training/train.py", line 88, in train
    loss.backward()
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/joal/.conda/envs/pointcept/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'AddmmBackward0' returned nan values in its 2th output.

**Comment by Gofinge** [comment]
What about training your custom dataset with PointTransformerV2? And could you provide the detailed training config and a sample point cloud of your custom dataset? The transformer is sensitive to training parameters and exploding gradient problems occur occasionally.

**Comment by joao-alemao** [comment]
I tried PointTransformerV2 and am not running into the same issue anymore (for the same settings).

**Comment by yangfy0608** [comment]
I meet same question, do you have any new finding can solve the question? @joao-alemao

**Comment by Gofinge** [comment]
With the PTv1?

**Comment by yangfy0608** [comment]
Thank you for your reply, I have resolved the issue. 
We need to make sure that each data in the dataset contains at least 256 points in order to run the transitiondown module correctly, otherwise there will be a divide by 0 problem causing the gradient explosion.

**Comment by Gofinge** [comment]
> Thank you for your reply, I have resolved the issue. We need to make sure that each data in the dataset contains at least 256 points in order to run the transitiondown module correctly, otherwise there will be a divide by 0 problem causing the gradient explosion.

Yeah, then you should try PTv2 or PTv3. There is no restriction in these factors.
