### ISSUE TITLE
Error at the 'forward' stage. RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by LuZaiJiaoXiaL** [Pointcept/Pointcept#7]
Hi, I met this problem when implementing your code. The error was found in the 'forward' stage.

May I know how to solve it?

[2023-03-31 11:27:32,544 INFO train.py line 112 22760] => Loading config ...
[2023-03-31 11:27:32,545 INFO train.py line 114 22760] Save path: /lustre1/g/rec_yy/model_train_log/point_transformer/results/
[2023-03-31 11:27:33,180 INFO train.py line 115 22760] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 31796434
save_path = '/lustre1/g/rec_yy/model_train_log/point_transformer/results/'
num_worker = 4
batch_size = 1
batch_size_val = 1
batch_size_test = 1
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
max_batch_points = 100000000.0
mix_prob = 0.8
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None)
]
test = dict(type='SegmentationTest')
model = dict(
    type='DefaultSegmentor',
    backbone=dict(
        type='PTv2m2',
        in_channels=6,
        num_classes=7,
        patch_embed_depth=2,
        patch_embed_channels=48,
        patch_embed_groups=6,
        patch_embed_neighbours=16,
        enc_depths=(2, 6, 2),
        enc_channels=(96, 192, 384),
        enc_groups=(12, 24, 48),
        enc_neighbours=(16, 16, 16),
        dec_depths=(1, 1, 1),
        dec_channels=(48, 96, 192),
        dec_groups=(6, 12, 24),
        dec_neighbours=(16, 16, 16),
        grid_sizes=(0.1, 0.2, 0.4),
        attn_qkv_bias=True,
        pe_multiplier=False,
        pe_bias=True,
        attn_drop_rate=0.0,
        drop_path_rate=0.3,
        enable_checkpoint=False,
        unpool_backend='interp'),
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(type='MultiStepLR', milestones=[0.6, 0.8], gamma=0.1)
dataset_type = 'HongKongDataset'
data_root = '/lustre1/g/rec_yy/data_processing/point_transformer/'
data = dict(
    num_classes=7,
    ignore_index=-1,
    names=[
        'ground', 'terrain', 'building', 'vehicle', 'vegetation', 'water',
        'facility'
    ],
    train=dict(
        type='HongKongDataset',
        split=('Tile', 'tile'),
        data_root='/lustre1/g/rec_yy/data_processing/point_transformer/',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='Voxelize',
                voxel_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='SphereCrop', point_max=80000, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='HongKongDataset',
        split='0_',
        data_root='/lustre1/g/rec_yy/data_processing/point_transformer/',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord', segment='origin_label')),
            dict(
                type='Voxelize',
                voxel_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                offset_keys_dict=dict(offset='coord'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False),
    test=dict(
        type='HongKongDataset',
        split='1_',
        data_root='/lustre1/g/rec_yy/data_processing/point_transformer/',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='Voxelize',
                voxel_size=0.04,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_discrete_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'discrete_coord', 'index'),
                    feat_keys=('coord', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 4
batch_size_per_gpu = 1
batch_size_val_per_gpu = 1

[2023-03-31 11:27:33,181 INFO train.py line 116 22760] => Building model ...
[2023-03-31 11:27:33,546 INFO train.py line 190 22760] Num params: 3908347
[2023-03-31 11:27:45,604 INFO train.py line 118 22760] => Building writer ...
[2023-03-31 11:27:45,641 INFO train.py line 198 22760] Tensorboard writer logging dir: /lustre1/g/rec_yy/model_train_log/point_transformer/results/
[2023-03-31 11:27:45,641 INFO train.py line 120 22760] => Building train dataset & dataloader ...
[2023-03-31 11:27:45,644 INFO ISPRS_HK.py line 49 22760] Totally 416 x 30 samples in ('Tile', 'tile') set.
[2023-03-31 11:27:45,645 INFO train.py line 122 22760] => Building val dataset & dataloader ...
[2023-03-31 11:27:45,646 INFO ISPRS_HK.py line 49 22760] Totally 92 x 1 samples in 0_ set.
[2023-03-31 11:27:45,646 INFO train.py line 124 22760] => Building optimize, scheduler, scaler(amp) ...
[2023-03-31 11:27:45,648 INFO train.py line 128 22760] => Building hooks ...
[2023-03-31 11:27:45,649 INFO misc.py line 175 22760] => Loading checkpoint & weight ...
[2023-03-31 11:27:45,649 INFO misc.py line 194 22760] No weight found at: None
[2023-03-31 11:27:45,649 INFO train.py line 135 22760] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    main()
  File "train.py", line 23, in main
    launch(
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/engines/launch.py", line 87, in launch
    main_func(*cfg)
  File "train.py", line 16, in main_worker
    trainer.train()
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/engines/train.py", line 149, in train
    self.run_step()
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/engines/train.py", line 163, in run_step
    output_dict = self.model(input_dict)
  File "/lustre1/g/rec_yy/anaconda/transformer111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/models/default.py", line 16, in forward
    seg_logits = self.backbone(input_dict)
  File "/lustre1/g/rec_yy/anaconda/transformer111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/models/point_transformer_v2/point_transformer_v2m2_base.py", line 520, in forward
    points, cluster = self.enc_stages[i](points)
  File "/lustre1/g/rec_yy/anaconda/transformer111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/models/point_transformer_v2/point_transformer_v2m2_base.py", line 326, in forward
    points, cluster = self.down(points)
  File "/lustre1/g/rec_yy/anaconda/transformer111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxx/3dSegmentation/pointcept/Pointcept-main/pointcept/models/point_transformer_v2/point_transformer_v2m2_base.py", line 238, in forward
    cluster = voxel_grid(pos=coord - start[batch], size=self.grid_size, batch=batch, start=0)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Gofinge** [comment]
Hi, usually, it was caused by a mismatch of PyTorch, CUDA, CUDNN, or Nvidia Driver versions. Please try the following script to check if is cuda available with your current toolchain:

```
torch.cuda.is_available()
```

**Comment by zongshun21** [comment]
Input Command:python setup.py install

`running install
/home/wzs/anaconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/wzs/anaconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating pointops.egg-info
writing pointops.egg-info/PKG-INFO
writing dependency_links to pointops.egg-info/dependency_links.txt
writing requirements to pointops.egg-info/requires.txt
writing top-level names to pointops.egg-info/top_level.txt
writing manifest file 'pointops.egg-info/SOURCES.txt'
reading manifest file 'pointops.egg-info/SOURCES.txt'
writing manifest file 'pointops.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/pointops
copying functions/attention.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/interpolation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/subtraction.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/__init__.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/query.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/sampling.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/utils.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/aggregation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/grouping.py -> build/lib.linux-x86_64-cpython-38/pointops
running build_ext
error: [Errno 2] No such file or directory: '/home/wzs/anaconda3/envs/pointcept/bin/nvcc'`

May I know how to solve it?

**Comment by Gofinge** [comment]
Hi, try `nvcc -V` to check if CUDA success installed on your machine.

**Comment by zongshun21** [comment]
It has been resolved because the version of CUDA is inconsistent with Torch. Thank you very much for your answer, the world is wonderful because of you @Gofinge

**Comment by YOOOOOL** [comment]
> It has been resolved because the version of CUDA is inconsistent with Torch. Thank you very much for your answer, the world is wonderful because of you @Gofinge

hi ,When I set batchsize=1, the result is not as good as that in the paper. I would like to ask what your result is like

**Comment by Gofinge** [comment]
Which result? @YOOOOOL

**Comment by YOOOOOL** [comment]
@Gofinge When I ran the s3dis dataset of the pt2v2 model, the result was not very good. I set the batchsize to 1. I guess it was because I reduced the batchsize, but the learning rate did not change, leading to the bad result
