### ISSUE TITLE
Error in Swin3D on Structured3D

### ISSUE THREAD

**Issue by antao97** [Pointcept/Pointcept#75]
Hi, I run your code for Swin3D on the Structured3D dataset, and I have this error.

```
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/pointcept/engines/train.py", line 162, in train
    self.run_step()
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/pointcept/engines/train.py", line 176, in run_step
    output_dict = self.model(input_dict)
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/pointcept/models/default.py", line 15, in forward
    seg_logits = self.backbone(input_dict)
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-0-small/code/pointcept/models/swin3d/swin3d_v1m1_base.py", line 121, in forward
    coord_feat = data_dict["coord_feat"]
KeyError: 'coord_feat'
```

This error is similar to #60, but this happens on the Structured3D dataset. I run SpUNet and PTv2 on Structured3D properly in this environment.

**Comment by antao97** [comment]
Error occurs both in Swin-S and Swin-L.

**Comment by Gofinge** [comment]
Hi, thanks for your reminder, I just fixed the config for Swin3D + Structured3D. You can check the difference with the following commit: https://github.com/Pointcept/Pointcept/commit/589eeee4e4d9bae09bad3195618682f4fdff31db.

**Comment by antao97** [comment]
The error is solved now. Thanks for your reply!
