### ISSUE TITLE
Fine-tune pretrained model from Structured3D

### ISSUE THREAD

**Issue by antao97** [Pointcept/Pointcept#77]
Hi, I pretrained SpUNet and PTv2 on the Structured3D dataset using your provided commands in README. When I try to fine-tune it on the ScanNet dataset, I find a conflict in the network output layer size. It is just a loading error, but I think adding some special code in this repo would be better.

```
Traceback (most recent call last):
  File "exp/scannet/semseg-spunet-v1m1-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/scannet/semseg-spunet-v1m1-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/pointcept/engines/launch.py", line 75, in launch
    mp.spawn(
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/pointcept/engines/launch.py", line 138, in _distributed_worker
    main_func(*cfg)
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/pointcept/engines/train.py", line 144, in train
    self.before_train()
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/pointcept/engines/train.py", line 82, in before_train
    h.before_train()
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-spunet-v1m1-0-base/code/pointcept/engines/hooks/misc.py", line 232, in before_train
    load_state_info = self.trainer.model.load_state_dict(
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        size mismatch for module.backbone.final.weight: copying a param with shape torch.Size([25, 1, 1, 1, 96]) from checkpoint, the shape in current model is torch.Size([20, 1, 1, 1, 96]).
        size mismatch for module.backbone.final.bias: copying a param with shape torch.Size([25]) from checkpoint, the shape in current model is torch.Size([20]).
```

Also, I find your fine-tuning command all use models from `exp/structured3d/semseg-swin3d-v1m1-1-large/model/model_last.pth`. It seems that some should use `semseg-swin3d-v1m1-1-small`. Furthermore, I wonder why using model last not model best.

**Comment by Gofinge** [comment]
_< "It is just a loading error, but I think adding some special code in this repo would be better."_
Currently, you can use the following code to replace the CheckpointLoader hook. Thanks for your suggestion, I will further refine this case in the CheckpointLoader.
```
dict(type="CheckpointLoader", keywords="backbone.final, replacement="backbone.unused"),
```

_< "Furthermore, I wonder why using model last not model best."_

For pre-training, there is no much difference between `last` and `best`, and our code just sets `last` as default, you can choose which weight to load by `-w`.

**Comment by antao97** [comment]
Thanks for your reply!

**Comment by antao97** [comment]
Hi, I follow your instructions to avoid loading the final layer of weights. Specifically, I added the following config in `configs/scannet/semseg-swin3d-v1m1-0-small.py`:
```
hooks = [
    dict(type="CheckpointLoader", unload_keywords="backbone.classifier"),
]
```
I also modified `CheckpointLoader` in `pointcept/engines/hooks/misc.py` into:
```
@HOOKS.register_module()
class CheckpointLoader(HookBase):
    def __init__(self, keywords="", unload_keywords="", replacement=None, strict=False):
        self.keywords = keywords
        self.unload_keywords = unload_keywords
        self.replacement = replacement if replacement is not None else keywords
        self.strict = strict

    def before_train(self):
        self.trainer.logger.info("=> Loading checkpoint & weight ...")
        if self.trainer.cfg.weight and os.path.isfile(self.trainer.cfg.weight):
            self.trainer.logger.info(f"Loading weight at: {self.trainer.cfg.weight}")
            checkpoint = torch.load(
                self.trainer.cfg.weight,
                map_location=lambda storage, loc: storage.cuda(),
            )
            weight = checkpoint["state_dict"].items()
            if self.keywords != "":
                self.trainer.logger.info(
                    f"Loading layer weights with keyword: {self.keywords}, "
                    f"replace keyword with: {self.replacement}"
                )
                new_weight = OrderedDict(
                    [
                        (key.replace(self.keywords, self.replacement), value)
                        for key, value in weight
                        if self.keywords in key
                    ]
                )
                weight = new_weight
            if self.unload_keywords != "":
                self.trainer.logger.info(
                    f"Unloading layer weights with keyword: {self.unload_keywords}"
                )
                new_weight = OrderedDict()
                for key, value in weight:
                    if self.unload_keywords in key:
                        new_key = key.replace(self.unload_keywords, "backbone.unused")
                        new_weight[new_key] = value
                    else:
                        new_weight[key] = value
                weight = new_weight
            load_state_info = self.trainer.model.load_state_dict(
                weight, strict=self.strict
            )
            self.trainer.logger.info(f"Missing keys: {load_state_info[0]}")
            if self.trainer.cfg.resume:
                self.trainer.logger.info(
                    f"Resuming train at eval epoch: {checkpoint['epoch']}"
                )
                self.trainer.start_epoch = checkpoint["epoch"]
                self.trainer.best_metric_value = checkpoint["best_metric_value"]
                self.trainer.optimizer.load_state_dict(checkpoint["optimizer"])
                self.trainer.scheduler.load_state_dict(checkpoint["scheduler"])
                if self.trainer.cfg.enable_amp:
                    self.trainer.scaler.load_state_dict(checkpoint["scaler"])
        else:
            self.trainer.logger.info(f"No weight found at: {self.trainer.cfg.weight}")
```

I solved the weight loading error, but I found I could not start training on ScanNet. I ran this command
```
sh scripts/train.sh -g 4 -d scannet -w exp/structured3d/semseg-swin3d-v1m1-0-small/model/model_last.pth -c semseg-swin3d-v1m1-0-small -n semseg-swin3d-v1m1-0-small
```
and got this log [train.log](https://github.com/Pointcept/Pointcept/files/12595186/train.log).
Meanwhile, I tried other tasks on ScanNet such as SpUNet, and it ran properly.

**Comment by antao97** [comment]
The GPU cards were occupied normally, but the training process was not started properly.

**Comment by Gofinge** [comment]
Could you provide the error report as I cannot find the error report in train.log.

**Comment by antao97** [comment]
I waited for about 5 minutes and stopped running.
```
[2023-09-13 16:31:23,843 INFO train.py line 138 1590022] => Building hooks ...                                                                                
[2023-09-13 16:31:23,843 INFO misc.py line 217 1590022] => Loading checkpoint & weight ...
[2023-09-13 16:31:23,843 INFO misc.py line 219 1590022] Loading weight at: exp/structured3d/semseg-swin3d-v1m1-0-small/model/model_last.pth
[2023-09-13 16:31:25,670 INFO misc.py line 239 1590022] Unloading layer weights with keyword: backbone.classifier                         
[2023-09-13 16:31:25,695 INFO misc.py line 253 1590022] Missing keys: ['module.backbone.classifier.0.weight', 'module.backbone.classifier.0.bias', 'module.bac
kbone.classifier.1.weight', 'module.backbone.classifier.1.bias', 'module.backbone.classifier.1.running_mean', 'module.backbone.classifier.1.running_var', 'mod
ule.backbone.classifier.3.weight', 'module.backbone.classifier.3.bias']                                                                                       
[2023-09-13 16:31:25,700 INFO train.py line 145 1590022] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
^CTraceback (most recent call last):                                                                                                                          
  File "exp/scannet/semseg-swin3d-v1m1-0-small/code/tools/train.py", line 38, in <module>
    main()                                                                     
  File "exp/scannet/semseg-swin3d-v1m1-0-small/code/tools/train.py", line 27, in main                     
    launch(        
  File "/data1/antao/Documents/Pointcept/exp/scannet/semseg-swin3d-v1m1-0-small/code/pointcept/engines/launch.py", line 75, in launch
    mp.spawn(                                                                  
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')                          
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():                                                                                                                                 
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 109, in join
    ready = multiprocessing.connection.wait(                                                                                                                  
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)                                                                                                                          
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)                                                                                                              
KeyboardInterrupt                   
^CError in atexit._run_exitfuncs:                                                                                                                             
Traceback (most recent call last):                                             
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)       
KeyboardInterrupt  
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7facea265f70>
Traceback (most recent call last):
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fe45e525f70>                                                                     
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__                              
Traceback (most recent call last):                                                                                                                            
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__                              
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3f52f65f70>                                                                     
Traceback (most recent call last):                                                                                                                            
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__                              
    self._shutdown_workers()                                                                                                                                  
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers                    
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)                                                                                                           
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 149, in join                                                    
    res = self._popen.wait(timeout)                                            
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait                                                  
    self._shutdown_workers()                                                                                                                                  
    if not wait([self.sentinel], timeout):                                                                                                                    
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 931, in wait                                                 
    self._shutdown_workers()                                                                                                                                  
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers                    
    ready = selector.select(timeout)                                                                                                                          
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/selectors.py", line 415, in select                                                                
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)                                                                                                           
    fd_event_list = self._selector.poll(timeout)                               
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 149, in join
KeyboardInterrupt: 
    res = self._popen.wait(timeout)                                                                                                                           
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)                            
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait                 
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 149, in join
    if not wait([self.sentinel], timeout):                                                                                                                    
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 931, in wait                                                 
    res = self._popen.wait(timeout)                                                                                                                           
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait                                                  
    if not wait([self.sentinel], timeout):                                                                                                                    
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/multiprocessing/connection.py", line 931, in wait                                                 
    ready = selector.select(timeout)                                                                                                                          
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/selectors.py", line 415, in select                                                                
    ready = selector.select(timeout)
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/selectors.py", line 415, in select                                                                
    fd_event_list = self._selector.poll(timeout)                               
KeyboardInterrupt:                                                                                                                                            
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt: 
```

**Comment by Gofinge** [comment]
“Start Training” is logged in `pointcept.engine.train` L152, could you use breakpoint or print to check that the program is blocked from where?

**Comment by antao97** [comment]
The problem is strange. I add print in code:
```
# => run_epoch
for (
    self.comm_info["iter"],
    self.comm_info["input_dict"],
) in self.data_iterator:
    # => before_step
    self.before_step()
    print("ok1")
    # => run_step
    self.run_step()
    print("ok2")
    # => after_step
    self.after_step()
    print("ok3")
# => after epoch
self.after_epoch()
print("ok")
```
My code runs properly and it continues printing.
```
[2023-09-13 18:06:46,143 INFO train.py line 145 1623449] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>                                                     
ok1                                                                                                                                                           
ok1                                                                                                                                                           
ok1                                                                                                                                                           
ok1                                                                                                                                                           
ok2                                                                                                                                                           
ok3                                                                                                                                                           
ok1                                                                                                                                                           
ok2                                                                                                                                                           
ok3                                                                                                                                                           
ok1                                                                                                                                                           
ok2                                                                                                                                                           
ok3                                                                                                                                                           
ok1                                                                                                                                                           
ok2                                                                                                                                                           
ok3
```
But the regular training log still disappears. I add print in function `before_step` defined in `InformationWriter` at `misc.py`, but the print does not work.

**Comment by antao97** [comment]
It seems that only one process runs properly printing ok1, ok2, and ok3.

**Comment by Gofinge** [comment]
Aha, I know the reason: you overwrote the default hook setting, and InformationWriter did not exist in your new hook list.

**Comment by antao97** [comment]
Oh I know your meaning. So the default hooks are :
```
hooks = [
    dict(type="CheckpointLoader"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    dict(type="SemSegEvaluator"),
    dict(type="CheckpointSaver", save_freq=None),
    dict(type="PreciseEvaluator", test_last=False),
]
```
I should add these hooks in my config:
```
hooks = [
    dict(type="CheckpointLoader", unload_keywords="backbone.classifier"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    dict(type="SemSegEvaluator"),
    dict(type="CheckpointSaver", save_freq=None),
    dict(type="PreciseEvaluator", test_last=False),
]
```

**Comment by Gofinge** [comment]
Exactly!

**Comment by antao97** [comment]
The log appears! Thanks very much!
