### ISSUE TITLE
Saving checkpoint error

### ISSUE THREAD

**Issue by cheylong** [Pointcept/Pointcept#78]
Hi, I met this problem when run your code. The error was found in the 'Saving checkpoint' stage.

I train on nuscenes with 
sh scripts/train.sh -p /opt/conda/envs/pointcept/bin/python -g 2 -d nuscenes -c semseg-spunet-v1m1-0-base -n nuscene_spunet
then meet some error,

log is below:

[2023-09-06 06:31:37,008 INFO misc.py line 161 121463] Best validation mIoU updated to: 0.5427
[2023-09-06 06:31:37,009 INFO misc.py line 166 121463] Currently Best mIoU: 0.5427
[2023-09-06 06:31:37,009 INFO misc.py line 175 121463] Saving checkpoint to: exp/nuscenes/nuscene_spunet/model/model_last.pth
Traceback (most recent call last):
  File "exp/nuscenes/nuscene_spunet/code/tools/train.py", line 38, in <module>
    main()
  File "exp/nuscenes/nuscene_spunet/code/tools/train.py", line 27, in main
    launch(
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/pointcept/engines/train.py", line 168, in train
    self.after_train()
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/pointcept/engines/train.py", line 106, in after_train
    h.after_train()
  File "/workspace/Pointcept/exp/nuscenes/nuscene_spunet/code/pointcept/engines/hooks/misc.py", line 287, in after_train
    checkpoint = torch.load(best_path)
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/opt/conda/envs/pointcept/lib/python3.8/site-packages/torch/serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
RuntimeError: PytorchStreamReader failed reading file data/2: file read failed

**Comment by Gofinge** [comment]
I think the error occurred in `PreciseEvaluation` hook, the hook loads the `model last` when the `model last` is still saving. I just tried to fix the issue with the following commit: https://github.com/Pointcept/Pointcept/commit/05587ad924391d730b1789455554f88d33e7ff7e

BTW: The current released version of Pointcept can not test on NuScenes properly, you might need to email me to access the v1.4.0 code to operate precise tests on NuScenes
