### ISSUE TITLE
Error occurs during testing Structured3D

### ISSUE THREAD

**Issue by antao97** [Pointcept/Pointcept#84]
Hi, I find testing Structured3D dataset fails every time. I use 6 3090 cards. 
```
[2023-09-18 10:17:08,490 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 114/186
[2023-09-18 10:17:09,513 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 115/186
[2023-09-18 10:17:10,589 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 116/186
[2023-09-18 10:17:11,621 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 117/186
[2023-09-18 10:17:12,658 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 118/186
[2023-09-18 10:17:13,672 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 119/186
[2023-09-18 10:17:14,851 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 120/186
[2023-09-18 10:17:56,700 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 121/186
[2023-09-18 10:17:57,832 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 122/186
[2023-09-18 10:17:58,950 INFO test.py line 111 3206353] Test: 18/296-scene_03173_room_31289, Batch: 123/186
Traceback (most recent call last):
  File "exp/structured3d/semseg-swin3d-v1m1-1-large/code/tools/train.py", line 38, in <module>
    main()
  File "exp/structured3d/semseg-swin3d-v1m1-1-large/code/tools/train.py", line 27, in main
    launch(
  File "/data1/antao/Documents/Pointcept/exp/structured3d/semseg-swin3d-v1m1-1-large/code/pointcept/engines/launch.py", line 75, in launch
    mp.spawn(
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data1/antao/anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL
```

**Comment by Gofinge** [comment]
Hi, I have never encountered a similar error, it is strange that it only returns with the signal SIGKILL instead of other error information. Could you provide more detail?

**Comment by Gofinge** [comment]
That's really strange, I need some time to rerun the experiment on my machine to check whether the error occurs in my machine.
