### ISSUE TITLE
Problem running PTv2

### ISSUE THREAD

**Issue by emmalzw** [Pointcept/Pointcept#88]
After configuring the environment, we successfully ran PTv1. However, when attempting to train PTv2 with the following two training commands, there were both errors with no training record, as following:
`sh scripts/train.sh -g 4 -d s3dis -c semseg-pt-v2m2-0-base -n semseg-pt-v2m2-0-base`
`sh scripts/train.sh -g 4 -d s3dis -c semseg-pt-v2m1-0-base -n semseg-pt-v2m1-0-base`

Experiment name: semseg-pt-v2m2-0-base
Python interpreter dir: python
Dataset: s3dis
Config: semseg-pt-v2m2-0-base
GPU Num: 4
 =========> CREATE EXP DIR <=========
Experiment dir: /root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base
Loading config in: configs/s3dis/semseg-pt-v2m2-0-base.py
Running code in: exp/s3dis/semseg-pt-v2m2-0-base/code
 =========> RUN TASK <=========
[2023-09-28 17:20:46,654 INFO train.py line 123 13836] => Loading config ...
[2023-09-28 17:20:46,654 INFO train.py line 125 13836] Save path: exp/s3dis/semseg-pt-v2m2-0-base
[2023-09-28 17:20:47,472 INFO train.py line 126 13836] Config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 33068591
save_path = 'exp/s3dis/semseg-pt-v2m2-0-base'
num_worker = 16
batch_size = 12
batch_size_val = None
batch_size_test = None
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
mix_prob = 0.8
param_dicts = None
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
test = dict(type='SemSegTester')
model = dict(
    type='DefaultSegmentor',
    backbone=dict(
        type='PT-v2m2',
        in_channels=6,
        num_classes=13,
        patch_embed_depth=2,
        patch_embed_channels=48,
        patch_embed_groups=6,
        patch_embed_neighbours=16,
        enc_depths=(2, 6, 2),
        enc_channels=(96, 192, 384),
        enc_groups=(12, 24, 48),
        enc_neighbours=(16, 16, 16),
        dec_depths=(1, 1, 1),
        dec_channels=(48, 96, 192),
        dec_groups=(6, 12, 24),
        dec_neighbours=(16, 16, 16),
        grid_sizes=(0.1, 0.2, 0.4),
        attn_qkv_bias=True,
        pe_multiplier=False,
        pe_bias=True,
        attn_drop_rate=0.0,
        drop_path_rate=0.3,
        enable_checkpoint=False,
        unpool_backend='interp'),
    criteria=[dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1)])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(type='MultiStepLR', milestones=[0.6, 0.8], gamma=0.1)
dataset_type = 'S3DISDataset'
data_root = 'data/s3dis'
data = dict(
    num_classes=13,
    ignore_index=-1,
    names=[
        'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
        'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter'
    ],
    train=dict(
        type='S3DISDataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='SphereCrop', point_max=80000, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord',
                               segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'color', 'segment'),
                return_discrete_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'discrete_coord', 'segment'),
                offset_keys_dict=dict(offset='coord'),
                feat_keys=['coord', 'color'])
        ],
        test_mode=False),
    test=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color'),
                return_discrete_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'discrete_coord', 'index'),
                    feat_keys=('coord', 'color'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))
num_worker_per_gpu = 4
batch_size_per_gpu = 3
batch_size_val_per_gpu = 1
batch_size_test_per_gpu = 1

[2023-09-28 17:20:47,472 INFO train.py line 127 13836] => Building model ...
[2023-09-28 17:20:47,547 INFO train.py line 204 13836] Num params: 3908641
[2023-09-28 17:20:49,348 INFO train.py line 129 13836] => Building writer ...
[2023-09-28 17:20:49,349 INFO train.py line 214 13836] Tensorboard writer logging dir: exp/s3dis/semseg-pt-v2m2-0-base
[2023-09-28 17:20:49,349 INFO train.py line 131 13836] => Building train dataset & dataloader ...
[2023-09-28 17:20:49,350 INFO s3dis.py line 55 13836] Totally 0 x 30 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6') set.
[2023-09-28 17:20:49,351 INFO train.py line 133 13836] => Building val dataset & dataloader ...
[2023-09-28 17:20:49,351 INFO s3dis.py line 55 13836] Totally 0 x 1 samples in Area_5 set.
[2023-09-28 17:20:49,351 INFO train.py line 135 13836] => Building optimize, scheduler, scaler(amp) ...
[2023-09-28 17:20:49,354 INFO train.py line 139 13836] => Building hooks ...
[2023-09-28 17:20:49,354 INFO misc.py line 214 13836] => Loading checkpoint & weight ...
[2023-09-28 17:20:49,354 INFO misc.py line 247 13836] No weight found at: None
[2023-09-28 17:20:49,354 INFO train.py line 146 13836] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
[2023-09-28 17:20:49,545 INFO misc.py line 137 13836] Train result: 
[2023-09-28 17:20:49,545 INFO evaluator.py line 112 13836] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 167, in train
    self.after_epoch()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 100, in after_epoch
    h.after_epoch()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 109, in after_epoch
    self.eval()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 165, in eval
    loss_avg = self.trainer.storage.history("val_loss").avg
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/utils/events.py", line 392, in history
    raise KeyError("No history metric available for {}!".format(name))
KeyError: 'No history metric available for val_loss!'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13895) is killed by signal: Terminated. 
Traceback (most recent call last):
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 167, in train
    self.after_epoch()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 100, in after_epoch
    h.after_epoch()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 109, in after_epoch
    self.eval()
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 165, in eval
    loss_avg = self.trainer.storage.history("val_loss").avg
  File "/root/Pointcept-main/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/utils/events.py", line 392, in history
    raise KeyError("No history metric available for {}!".format(name))
KeyError: 'No history metric available for val_loss!'

Is there a problem with the configuration file?

**Comment by emmalzw** [comment]
We have identified the problem~

**Comment by Stronger-Huang** [comment]
> We have identified the problem~

same problem, how to solve?

**Comment by Laventna** [comment]
same as you,  how to solve? please

**Comment by Gofinge** [comment]
> "[2023-09-28 17:20:49,350 INFO s3dis.py line 55 13836] Totally 0 x 30 samples in ('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6') set."

Please check your data path: data/s3dis/

**Comment by Gofinge** [comment]
Wow, so sorry for the late response! I just noticed the issue.
