### ISSUE TITLE
Problem with evaluation 

### ISSUE THREAD

**Issue by doloresgarcia** [Pointcept/Pointcept#94]
I am running the training as:
`sh scripts/train.sh -p python -d s3dis -c semseg-pt-v2m2-0-base -n semseg-pt-v2m2-0-base -g 4`
The first epoch finishes correctly and outputs a loss:
`[2023-10-24 16:25:02,449 INFO misc.py line 123 44561] Train: [1/100][110/110] Data 0.004 (0.004) Batch 2.582 (2.596) Remain 07:51:08 loss: 0.6349 Lr: 0.00600
[2023-10-24 16:25:02,451 INFO misc.py line 140 44561] Train result: loss: 0.8315`
However when evaluation starts the training breaks. The error message is a fix of many things. Is there anything specific that could result in this behavior?
`Traceback (most recent call last):
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.compat._inspect import getargspec
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/compat/__init__.py", line 11, in <module>
    from . import _inspect
ImportError: cannot import name '_inspect' from partially initialized module 'numpy.compat' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 8, in <module>
    from pointcept.engines.defaults import (
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/defaults.py", line 14, in <module>
    from torch.nn.parallel import DistributedDataParallel
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/__init__.py", line 656, in <module>
    from .storage import _StorageBase, _TypedStorage, _LegacyStorage, _UntypedStorage
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/storage.py", line 11, in <module>
    import numpy as np
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/eos/user/m/mgarciam/envs/pointcept1/bin/python"
Original error was: cannot import name '_inspect' from partially initialized module 'numpy.compat' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/compat/__init__.py)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    prepare(preparation_data)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    exitcode = _main(fd, parent_sentinel)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    prepare(preparation_data)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 265, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return _run_module_code(code, init_globals, run_name,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 97, in _run_module_code
    main_content = runpy.run_path(main_path,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 265, in run_path
    _run_code(code, mod_globals, init_globals,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_module_code(code, init_globals, run_name,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 97, in _run_module_code
    exec(code, run_globals)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 8, in <module>
    _run_code(code, mod_globals, init_globals,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 87, in _run_code
    from pointcept.engines.defaults import (
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/defaults.py", line 14, in <module>
    from torch.nn.parallel import DistributedDataParallel
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/__init__.py", line 656, in <module>
    exec(code, run_globals)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 8, in <module>
    from .storage import _StorageBase, _TypedStorage, _LegacyStorage, _UntypedStorage
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/storage.py", line 11, in <module>
    from pointcept.engines.defaults import (
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/defaults.py", line 14, in <module>
    from torch.nn.parallel import DistributedDataParallel
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/__init__.py", line 656, in <module>
    import numpy as np
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/__init__.py", line 144, in <module>
    from .storage import _StorageBase, _TypedStorage, _LegacyStorage, _UntypedStorage
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/storage.py", line 11, in <module>
    from . import lib
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/lib/__init__.py", line 20, in <module>
    import numpy as np
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/lib/__init__.py", line 20, in <module>
    from . import mixins
ImportError: cannot import name 'mixins' from partially initialized module 'numpy.lib' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/lib/__init__.py)
    from . import mixins
ImportError: cannot import name 'mixins' from partially initialized module 'numpy.lib' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/lib/__init__.py)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 8, in <module>
    from pointcept.engines.defaults import (
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/defaults.py", line 14, in <module>
    from torch.nn.parallel import DistributedDataParallel
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/__init__.py", line 656, in <module>
    from .storage import _StorageBase, _TypedStorage, _LegacyStorage, _UntypedStorage
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/storage.py", line 11, in <module>
    import numpy as np
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import fft
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/fft/__init__.py", line 203, in <module>
    from . import _pocketfft, helper
ImportError: cannot import name '_pocketfft' from partially initialized module 'numpy.fft' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/fft/__init__.py)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 8, in <module>
    from pointcept.engines.defaults import (
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/defaults.py", line 14, in <module>
    from torch.nn.parallel import DistributedDataParallel
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/__init__.py", line 656, in <module>
    from .storage import _StorageBase, _TypedStorage, _LegacyStorage, _UntypedStorage
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/storage.py", line 11, in <module>
    import numpy as np
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/__init__.py", line 154, in <module>
    from . import ma
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/ma/__init__.py", line 42, in <module>
    from . import core
ImportError: cannot import name 'core' from partially initialized module 'numpy.ma' (most likely due to a circular import) (/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/numpy/ma/__init__.py)
Traceback (most recent call last):
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 39, in <module>
    main()
  File "exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6208) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/launch.py", line 138, in _distributed_worker
    main_func(*cfg, local_rank = local_rank)
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 168, in train
    self.after_epoch()
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 100, in after_epoch
    h.after_epoch()
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 109, in after_epoch
    self.eval()
  File "/eos/home-m/mgarciam/REPOS/UD_pointcept/exp/s3dis/semseg-pt-v2m2-0-base/code/pointcept/engines/hooks/evaluator.py", line 114, in eval
    for i, input_dict in enumerate(self.trainer.val_loader):
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1315, in _get_data
    success, data = self._try_get_data()
  File "/eos/user/m/mgarciam/envs/pointcept1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 6208) exited unexpectedly`

**Comment by Gofinge** [comment]
Hi, my apology for the late response. Could you provide a detailed error message?
