### ISSUE TITLE
ModuleNotFoundError: No module named 'pointops._C'

### ISSUE THREAD

**Issue by RoozbehSanaei** [Pointcept/Pointcept#96]
The command python setup.py install executes successfully, however, it encounters an issue locating pointops._C. Despite this, a shared object file is generated at ./build/lib.linux-x86_64-cpython-39/pointops/_C.cpython-39-x86_64-linux-gnu.so. 

Traceback (most recent call last):
  File "/drive2/src/pointcloud/repositories/Pointcept/tools/train.py", line 13, in <module>
    from pointcept.engines.train import Trainer
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointcept/engines/train.py", line 23, in <module>
    from .hooks import HookBase, build_hooks
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointcept/engines/hooks/__init__.py", line 3, in <module>
    from .evaluator import *
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointcept/engines/hooks/evaluator.py", line 11, in <module>
    import pointops
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointops/__init__.py", line 1, in <module>
    from .functions import *
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointops/functions/__init__.py", line 1, in <module>
    from .query import knn_query, ball_query, random_ball_query
  File "/drive2/src/pointcloud/repositories/Pointcept/libs/pointops/functions/query.py", line 4, in <module>
    from pointops._C import knn_query_cuda, random_ball_query_cuda, ball_query_cuda
ModuleNotFoundError: No module named 'pointops._C'

**Comment by Gofinge** [comment]
Hi, I can not reproduce the issue, could you try to reinstall an environment?

**Comment by bututoubaobei-0108** [comment]
i have encounted the similar problem but for pointops._C: "no module named pointops._C". I solved using the following steps:

change the name pointops._C to something not with dot, such as "pointops_cuda" being what i have used in "libs/pointops/setup.py"
change the pointops._C in directory "libs/pointops/functions/" to "pointops_cuda"
in "libs/pointops/functions/utils.py", change "from pointops import knn_query, ball_query, grouping" to "from .query import knn_query, ball_query" and "from .grouping import grouping"
after the above procedure, my code works.
Hope that the answer helps you :)
