### ISSUE TITLE
Testing was stuck when multi GPU syncing

### ISSUE THREAD

**Issue by JinyuanShao** [Pointcept/Pointcept#97]
Hi, very appreciate this nice codebase!

I met a problem when I was running the example for s3dis: sh `scripts/train.sh -g 4 -d s3dis -c semseg-spunet-v1m1-0-cn-base -n semseg-spunet-v1m1-0-cn-base`

Everything was fine when training, but in the last step my progress wa stuck for 12 hours. 

Here are the last several lines in the train log:

`[2023-11-05 05:08:30,204 INFO test.py line 111 2786102] Test: 17/17-hallway_4, Batch: 717/722`
`[2023-11-05 05:08:30,236 INFO test.py line 111 2786102] Test: 17/17-hallway_4, Batch: 718/722`
`[2023-11-05 05:08:30,267 INFO test.py line 111 2786102] Test: 17/17-hallway_4, Batch: 719/722`
`[2023-11-05 05:08:30,299 INFO test.py line 111 2786102] Test: 17/17-hallway_4, Batch: 720/722`
`[2023-11-05 05:08:30,331 INFO test.py line 111 2786102] Test: 17/17-hallway_4, Batch: 721/722`
`[2023-11-05 05:08:30,392 INFO test.py line 138 2786102] Test: hallway_4 [17/17]-1027382 Batch 22.825 (35.943) Accuracy 0.9201 (0.7335) mIoU 0.4620 (0.6769)`
`[2023-11-05 05:08:30,894 INFO test.py line 194 2786102] Syncing ...`

It seems like the progress is stuck when the Python program trying to sync GPU. 

Is there any way to solve this? I used the default config in this code base.

**Comment by Gofinge** [comment]
Hi, syncing does need a bit longer time, as multiple GPUs are separated testing without syncing each step. If you want to accelerate the testing process, you can try our test config for NuScenes (dual grid sampling).

**Comment by Gofinge** [comment]
> Hi, syncing does need a bit longer time, as multiple GPUs are separated testing without syncing each step. If you want to accelerate the testing process, you can try our test config for NuScenes (dual grid sampling).

Oops, I forgot to update our test config for NuScenes which adopts a dual grid sampling strategy, which is much faster. I will update it after a few weeks.

**Comment by aldinorizaldy** [comment]
Hi @JinyuanShao have you solved the problem?

**Comment by Gofinge** [comment]
> Hi @JinyuanShao have you solved the problem?

The updated config should be much faster. Also, the aforementioned case is not a bug. Some datasets do need a lot of time to wait for for all GPUs to finish their tasks and then syncing. We only log the process on the main process

**Comment by aldinorizaldy** [comment]
Hi @Gofinge thanks for being here. I am using s3dis dataset and the example script for testing: `sh scripts/test.sh -g 4 -p python -d s3dis -n semseg-spunet-v1m1-0-base -w model_best`. I just checked the config file and it is the same as the one on this repo. I waited for hours but still stuck with `Syncing ...`

I tried to change the number of gpu = 1, but then it was stuck here:

```
[2024-04-04 12:15:35,278 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 15/906
[2024-04-04 12:15:35,346 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 16/906
[2024-04-04 12:15:35,417 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 17/906
[2024-04-04 12:15:35,467 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 18/906
[2024-04-04 12:15:35,509 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 19/906
[2024-04-04 12:15:35,579 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 20/906
[2024-04-04 12:15:35,651 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 21/906
[2024-04-04 12:15:35,720 INFO test.py line 196 41939] Test: 3/68-conferenceRoom_3, Batch: 22/906
```

Then I repeat the testing, and it could go further before stuck on somewhere else:

```
[2024-04-04 12:30:01,367 INFO test.py line 119 42505] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-04-04 12:30:18,751 INFO test.py line 168 42505] 1/68: conferenceRoom_1, loaded pred and label.
[2024-04-04 12:30:18,814 INFO test.py line 230 42505] Test: conferenceRoom_1 [1/68]-1047554 Batch 0.064 (0.064) Accuracy 0.7703 (0.4913) mIoU 0.5139 (0.4349)
[2024-04-04 12:31:15,329 INFO test.py line 168 42505] 2/68: conferenceRoom_2, loaded pred and label.
[2024-04-04 12:31:15,457 INFO test.py line 230 42505] Test: conferenceRoom_2 [2/68]-1922357 Batch 0.134 (0.099) Accuracy 0.8423 (0.6245) mIoU 0.5984 (0.5478)
[2024-04-04 12:31:40,779 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 0/906
[2024-04-04 12:31:40,847 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 1/906
[2024-04-04 12:31:40,915 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 2/906
[2024-04-04 12:31:40,985 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 3/906
...
...
[2024-04-04 12:32:42,349 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 902/906
[2024-04-04 12:32:42,419 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 903/906
[2024-04-04 12:32:42,489 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 904/906
[2024-04-04 12:32:42,559 INFO test.py line 196 42505] Test: 3/68-conferenceRoom_3, Batch: 905/906
[2024-04-04 12:32:42,626 INFO test.py line 230 42505] Test: conferenceRoom_3 [3/68]-1507439 Batch 64.884 (21.694) Accuracy 0.8277 (0.6244) mIoU 0.4716 (0.5388)
```



I know it is not a bug from the code. But any ideas why I faced this thing?
Thanks.

**Comment by aldinorizaldy** [comment]
Seems like I have memory issue here when I continued testing after a few times got stuck.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 338, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: Broken pipe
terminate called after throwing an instance of 'std::system_error'
  what():  Broken pipe
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1011, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 43140) is killed by signal: Aborted. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/test.py", line 38, in <module>
    main()
  File "tools/test.py", line 27, in main
    launch(
  File "/home/rizald42/containers/Pointcept/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "tools/test.py", line 20, in main_worker
    tester.test()
  File "/home/rizald42/containers/Pointcept/pointcept/engines/test.py", line 160, in test
    for idx, data_dict in enumerate(self.test_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1207, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1024, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 43140) exited unexpectedly
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=6323.1. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: fwgegpu05: task 0: Out Of Memory
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=6323.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

```

**Comment by Gofinge** [comment]
Hi, discussion here contains several instruction on accelerating testing process (https://github.com/Pointcept/Pointcept/issues/108#issuecomment-1893709522)
